### ISSUE TITLE
Coursier resolves/evicts the wrong version of sbt plugin

### ISSUE THREAD

**Issue by dragos** [coursier/coursier#1017]
I tried Coursier as part of the meta-build, for resolving sbt-plugins. It results in a binary-incompatible resolution, leading to Sbt crash:

```
[error] Caused by: java.lang.ClassNotFoundException: org.vafer.jdeb.Console
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:20)
[error] 	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:27)
[error] 	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:31)
[error] 	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:414)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1167)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1157)
[error] 	at scala.collection.generic.Growable.loop$1(Growable.scala:53)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:57)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:49)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:185)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:43)
[error] 	at scala.collection.TraversableLike.$plus$plus(TraversableLike.scala:146)
[error] 	at scala.collection.TraversableLike.$plus$plus$(TraversableLike.scala:142)
[error] 	at scala.collection.immutable.List.$plus$plus(List.scala:206)
[error] 	at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:56)
[error] 	at sbt.internal.Load$.loadPlugins(Load.scala:1318)
[error] 	at sbt.internal.Load$.loadPluginDefinition(Load.scala:1263)
[error] 	at sbt.internal.Load$.buildPlugins(Load.scala:1242)
[error] 	at sbt.internal.Load$.plugins(Load.scala:1225)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:694)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:694)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:688)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:484)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:176)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:241)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:546)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:562)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:492)
[error] 	at sbt.internal.Load$.load(Load.scala:471)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:251)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.apply(Load.scala:251)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:800)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoClassDefFoundError: org/vafer/jdeb/Console
[error] Use 'last' for the full log.
```

Use this:

```
// project/plugins.sbt
libraryDependencies ++= Seq(
  "org.scala-sbt" %% "scripted-plugin" % sbtVersion.value
)

addSbtPlugin("de.heikoseeberger" % "sbt-header" % "5.0.0")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.8.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-license-report" % "1.2.0")
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.3")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.7")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.6")
addSbtCoursier
```

and

```
// project/project/plugins.sbt
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M9")
```

(I couldn't try `1.1.0-M10` because it can't be found/resolved). Same error happens with 1.0.3

**Comment by alexarchambault** [comment]
Should be fixed by https://github.com/coursier/sbt-coursier/pull/28, which will be included in the upcoming `1.1.0-M10` release of the plugins. (The plugins are released in sync with the core of coursier, `1.1.0-M10` shouldn't have been in the doc for the plugins.)
