### ISSUE TITLE
Classloader breakage between 1.1.0-M10 and 1.1.0-M11

### ISSUE THREAD

**Issue by Ferada** [coursier/coursier#1058]
I was using the instructions for [scalafmt](https://scalameta.org/scalafmt/docs/installation.html) for setting up a nailgun server.

```
$ wget https://github.com/coursier/coursier/releases/download/v1.1.0-M10/coursier
$ chmod a+rx coursier
$ ./coursier bootstrap com.geirsson:scalafmt-cli_2.12:1.5.1 -o scalafmt --standalone --main com.martiansoftware.nailgun.NGServer -r bintray:scalameta/maven -f
$ ./scalafmt_ng
NGServer 0.9.1 started on all interfaces, port 2113.
```

^ this works, while the following doesn't anymore (only change is version of `coursier` downloaded):

```
$ wget https://github.com/coursier/coursier/releases/download/v1.1.0-M11/coursier
$ chmod a+rx coursier
$ ./coursier bootstrap com.geirsson:scalafmt-cli_2.12:1.5.1 -o scalafmt --standalone --main com.martiansoftware.nailgun.NGServer -r bintray:scalameta/maven -f
$ ./scalafmt_ng
NGServer 0.9.1 started on all interfaces, port 2113.
java.lang.NoClassDefFoundError: com/martiansoftware/nailgun/NGOutputStream
        at com.martiansoftware.nailgun.NGSessionPool.take(NGSessionPool.java:84)
        at com.martiansoftware.nailgun.NGServer.run(NGServer.java:417)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.martiansoftware.nailgun.NGOutputStream
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: com/martiansoftware/nailgun/NailStats
        at com.martiansoftware.nailgun.NGServer.getOrCreateStatsFor(NGServer.java:244)
        at com.martiansoftware.nailgun.NGServer.shutdown(NGServer.java:339)
        at com.martiansoftware.nailgun.NGServer$NGServerShutdowner.run(NGServer.java:537)
Caused by: java.lang.ClassNotFoundException: com.martiansoftware.nailgun.NailStats
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
```

**Comment by alexarchambault** [comment]
@Ferada I'll look into it. As a workaround, you can either remove the `--standalone` option, to generate a thin launcher, or pass the `--assembly` option instead, to generate an actual assembly. Both seems to make the nailgun server start fine.

**Comment by alexarchambault** [comment]
cc @olafurpg

**Comment by Ferada** [comment]
@alexarchambault thanks for the quick fix!
