### ISSUE TITLE
SAXParseException; lineNumber: 1874; columnNumber: 24; The prefix "Xlint" for element "Xlint:-unchecked" is not bound

### ISSUE THREAD

**Issue by samidalouche** [coursier/coursier#1089]
How to reproduce
```
# build.sbt
libraryDependencies +=  "org.apache.hadoop" % "hadoop-client" % "3.2.0"

# project/build.properties
sbt.version=1.2.8

#project/plugins.sbt
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M13")

sbt compile
```

With sbt-coursier, this is the error I get. Works fine without sbt-coursier

```
[Fatal Error] :1874:24: The prefix "Xlint" for element "Xlint:-unchecked" is not bound.
[error] org.xml.sax.SAXParseException; lineNumber: 1874; columnNumber: 24; The prefix "Xlint" for element "Xlint:-unchecked" is not bound.
[error] 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
[error] 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
[error] 	at coursier.core.compatibility.package$.xmlParseSax(package.scala:64)
[error] 	at coursier.maven.MavenRepository$.parseRawPomSax(MavenRepository.scala:70)
[error] 	at coursier.maven.MavenRepository.$anonfun$findVersioning$1(MavenRepository.scala:332)
[error] 	at coursier.util.EitherT.$anonfun$flatMap$1(EitherT.scala:16)
[error] 	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:11)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (coursierResolutions) org.xml.sax.SAXParseException; lineNumber: 1874; columnNumber: 24; The prefix "Xlint" for element "Xlint:-unchecked" is not bound.
[error] Total time: 0 s, completed 6-Mar-2019 11:26:02 AM
```

**Comment by alexarchambault** [comment]
I found what caused that issue. I'll push a fix tomorrow.

**Comment by samidalouche** [comment]
Great! Thank you!

**Comment by alexarchambault** [comment]
https://github.com/coursier/coursier/pull/1088/commits/3578de1e195936756925377aa7975c991c39134f fixes that. The upcoming `1.1.0-M13-1` will fix that.
