### ISSUE TITLE
Coursier fails to authorize to Artifactory when using api key

### ISSUE THREAD

**Issue by misja-alma** [coursier/coursier#1101]
When using an Artifactory api key instead of a password in the sbt credentials, Artifactory fails to authorize when the Coursier plugin attempting to download artifacts.
To verify that this is a problem of the Coursier plugin, I have:

- compiled my sbt project without the Coursier plugin and using the api key instead of the password. This succesfully downloads dependencies from Artifactory
- compiled my sbt project with the Coursier plugin but using the (encrypted) password in the sbt credentials. This downloads dependencies as well.
- compiled my sbt project with Coursier plugin and with api-key instead of password. This fails to authorize, Artifactory returns a http 403.

I have tried on multiple machines, they all show the same error.

I am using version 1.1.0-M11 of the Coursier plugin and Sbt version 1.2.3.

**Comment by SethTisue** [comment]
Is there a standalone reproduction?

**Comment by dsebban** [comment]
Let me add some context  here if I try 
```cs fetch -r https:/<art-url>/artifactory/maven-dev <my_artifact> --use-env-credentials=false --credential-file ~/.config/coursier/credentials.properties
```
I set the credentials to the correct values (it works for sbt as it has a similar credential file)
I get 
```Exception in thread "main" coursier.install.AppArtifacts$ScalaDependenciesNotFound: Can't find a scala version suffix for <artifact-name> (likely a non existing module or version)
        at coursier.install.AppDescriptor.$anonfun$processDependencies$9(AppDescriptor.scala:231)
        at scala.Option.toRight(Option.scala:485)
        at coursier.install.AppDescriptor.processDependencies(AppDescriptor.scala:231)
        at coursier.cli.resolve.Resolve$.$anonfun$depsAndReposOrError$4(Resolve.scala:92)
```

**Comment by martin-stone** [comment]
I'm also getting this issue when trying to run coursier setup. Credentials here are Artifactory username:password...

```bash
curl -fL -u $artifactory_credentials "https://artifactory.mycompany.com/artifactory/github-remote/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz" | gzip -d > /tmp/cs \
    && chmod +x /tmp/cs \
    && /tmp/cs setup -y --apps coursier -J-Djavax.net.ssl.trustStore=/usr/lib/jvm/java-1.17.0-openjdk-amd64/lib/security/cacerts \
         --credentials "artifactory.mycompany.com(Artifactory Realm) $artifactory_credentials" \
    && rm /tmp/cs
...
 	at java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596)
 	at java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)
 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:902)
 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:878)
 Caused by: coursier.install.AppArtifacts$ScalaDependenciesNotFound: Can't find a scala version suffix for io.get-coursier::coursier-cli:latest.release (likely a non existing module or version)
 	at coursier.install.AppDescriptor.$anonfun$processDependencies$9(AppDescriptor.scala:234)
 	at scala.Option.toRight(Option.scala:593)
 	at coursier.install.AppDescriptor.processDependencies(AppDescriptor.scala:234)
 	at coursier.install.AppDescriptor.artifacts(AppDescriptor.scala:104)
 	... 23 more
```
