### ISSUE TITLE
can't parse pom files missing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

### ISSUE THREAD

**Issue by kostaskougios** [coursier/coursier#1104]
Hi,
I have an issue with one project that uses aws-java-lambda-libs. The pom file of that dependency doesn't contain the xsi declaration and fails with an exception.

I've opened bug https://github.com/aws/aws-lambda-java-libs/issues/85 but also it would be helpful to be fixed on coursier's end so that older deps can be imported.

Thanks

**Comment by kostaskougios** [comment]
I am getting an error like this below with M13 but it is indeed fixed for M13-2:

https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar
  100.0% [##########] 5.5 MiB (527.0 KiB / s)
https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.12/scala-reflect-2.11.12.jar
  100.0% [##########] 4.4 MiB (361.3 KiB / s)
[info] Fetched artifacts of commonConfig
[error] org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 107; The prefix "xsi" for attribute "xsi:schemaLocation" associated with an element type "project" is not bound.
[error] 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
[error] 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
[error] 	at coursier.core.compatibility.package$.xmlParseSax(package.scala:64)
[error] 	at coursier.maven.MavenRepository$.parseRawPomSax(MavenRepository.scala:70)
[error] 	at coursier.maven.MavenRepository.$anonfun$findVersioning$1(MavenRepository.scala:332)
[error] 	at coursier.util.EitherT.$anonfun$flatMap$1(EitherT.scala:16)
[error] 	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:11)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
