### ISSUE TITLE
Coursier and Ivy => None.get

### ISSUE THREAD

**Issue by joan38** [coursier/coursier#1204]
I thought I'll open the issue here too:
https://github.com/sbt/sbt/issues/4798

## steps
sbt version: 1.3.0-RC2

## problem
```
> update
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@31361a63 rejected from java.util.concurrent.ThreadPoolExecutor@3ff1f235[Shutting down, pool size = 6, active threads = 1, queued tasks = 0, completed tasks = 32280]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
  | => pat scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.$anonfun$tryCompleteWith$1(Promise.scala:75)
	at scala.concurrent.Promise.$anonfun$tryCompleteWith$1$adapted(Promise.scala:75)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:874)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:872)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:372)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:371)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:379)
	at scala.concurrent.Promise.tryCompleteWith(Promise.scala:75)
	at scala.concurrent.Promise.tryCompleteWith$(Promise.scala:73)
	at scala.concurrent.impl.Promise$DefaultPromise.tryCompleteWith(Promise.scala:187)
	at scala.concurrent.Promise.completeWith(Promise.scala:67)
	at scala.concurrent.Promise.completeWith$(Promise.scala:67)
	at scala.concurrent.impl.Promise$DefaultPromise.completeWith(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:44)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] java.util.NoSuchElementException: None.get
[error] 	at scala.None$.get(Option.scala:366)
[error] 	at scala.None$.get(Option.scala:364)
[error] 	at lmcoursier.internal.shaded.coursier.maven.PomParser$$anon$5.end(PomParser.scala:517)
[error] 	at lmcoursier.internal.shaded.coursier.maven.PomParser.$anonfun$endElement$1(PomParser.scala:53)
[error] 	at lmcoursier.internal.shaded.coursier.maven.PomParser.$anonfun$endElement$1$adapted(PomParser.scala:47)
[error] 	at scala.Option.foreach(Option.scala:274)
[error] 	at lmcoursier.internal.shaded.coursier.maven.PomParser.endElement(PomParser.scala:47)
[error] 	at lmcoursier.internal.shaded.coursier.core.compatibility.package$XmlHandler.endElement(package.scala:48)
[error] 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
[error] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
[error] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
[error] 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
[error] 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
[error] 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
[error] 	at lmcoursier.internal.shaded.coursier.core.compatibility.package$.xmlParseSax(package.scala:64)
[error] 	at lmcoursier.internal.shaded.coursier.maven.MavenRepository$.parseRawPomSax(MavenRepository.scala:70)
[error] 	at lmcoursier.internal.shaded.coursier.maven.MavenRepository.$anonfun$findVersioning$1(MavenRepository.scala:358)
[error] 	at lmcoursier.internal.shaded.coursier.util.EitherT.$anonfun$flatMap$1(EitherT.scala:16)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:11)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) java.util.NoSuchElementException: None.get
[error] Total time: 0 s, completed Jun 11, 2019 9:18:39 AM
```

The `.get`: https://github.com/coursier/coursier/blob/6d0e24205a6c8d3ecf2c0d4674984a4366b1cd59/modules/core/shared/src/main/scala/coursier/maven/PomParser.scala#L517

Sounds like it tries to resolve it as a maven dependency whereas my repo config has `isMavenCompatible = false`:
```
val repoPattern = Patterns(
  Vector("[orgPath]/[module]/[revision]/[module]-[revision]-ivy.[ext]"),
  Vector("[orgPath]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]"),
  isMavenCompatible = false,
  descriptorOptional = false,
  skipConsistencyCheck = true
)
```

Related PR:
https://github.com/coursier/coursier/pull/221
But couldn't find any code checking the `isMavenCompatible`:
https://github.com/coursier/coursier/search?q=isMavenCompatible&unscoped_q=isMavenCompatible

## Workaround

Disabling coursier:
```
useCoursier := false
```

**Comment by eed3si9n** [comment]
@joan38 Do you have a public project we can use to reproduce the error on our machine?

**Comment by joan38** [comment]
@eed3si9n I've been trying to reproduce it with a public repo without success. I'm still trying tho.
Do you have any other way going forward? Is it possible to somehow breakpoint or monkey patch to add println?

**Comment by joan38** [comment]
I can see it happens only when we have a transitive dependency that is also on our internal Ivy repo.

**Comment by eed3si9n** [comment]
According to stacktrace the error is happening around here https://github.com/coursier/coursier/blob/4f0e7623a3830f54291a7aec1892c6d29a8d76cd/modules/core/shared/src/main/scala/coursier/maven/PomParser.scala#L511-L520

so we are actually looking for your POM files in which there is `<exclusion>` element, but missing `<groupId>` under it. I have not looked if that's considered illegal or if Coursier should handle this gracefully as some default value like `*`.

**Comment by joan38** [comment]
There we go:
https://github.com/joan38/coursier-issue-1204

**Comment by alexarchambault** [comment]
Reproduction with the CLI:
```bash
$ coursier fetch com.netflix.karyon:karyon-eureka:1.0.28
Exception in thread "main" java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:366)
	at scala.None$.get(Option.scala:364)
	at coursier.maven.PomParser$$anon$5.end(PomParser.scala:517)
	at coursier.maven.PomParser.$anonfun$endElement$1(PomParser.scala:53)
	at coursier.maven.PomParser.$anonfun$endElement$1$adapted(PomParser.scala:47)
	at scala.Option.foreach(Option.scala:274)
	at coursier.maven.PomParser.endElement(PomParser.scala:47)
	at coursier.core.compatibility.package$XmlHandler.endElement(package.scala:48)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at coursier.core.compatibility.package$.xmlParseSax(package.scala:64)
	at coursier.maven.MavenRepository$.parseRawPomSax(MavenRepository.scala:70)
	at coursier.maven.MavenRepository.$anonfun$findVersioning$1(MavenRepository.scala:358)
	at coursier.util.EitherT.$anonfun$flatMap$1(EitherT.scala:16)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by eed3si9n** [comment]
voilà - http://repo1.maven.org/maven2/com/netflix/karyon/karyon-spi/1.0.28/karyon-spi-1.0.28.pom

```xml
<exclusions>
  <exclusion>
    <artifactId>archaius-core</artifactId>
  </exclusion>
</exclusions>
```

**Comment by joan38** [comment]
Is this an illegal pom? Are coursier should be getting it?
Thanks guys for looking into this BTW.

**Comment by joan38** [comment]
I tried look up this. It sounds like it should be a required field. But that's blocking in a bad way since it's deep in the dependency tree.
