### ISSUE TITLE
Latest-wins conflict resolution rules

### ISSUE THREAD

**Issue by eed3si9n** [coursier/coursier#1284]
## steps

https://github.com/eed3si9n/lagom-samples/commit/6f5bd56ae34c5f35d9ec7fee6d926bbda4451930

## problem

https://travis-ci.org/eed3si9n/lagom-samples/jobs/562204770

```
[error] lmcoursier.internal.shaded.coursier.error.ResolutionError$ConflictingDependencies: Conflicting dependencies:
[error] io.grpc:grpc-core:1.16.1:default(compile)
[error] io.grpc:grpc-core:1.20.0:default(compile)
[error] io.grpc:grpc-core:[1.16.1]:default(compile)
[error] io.grpc:grpc-core:[1.20.0]:default(compile)
[error] 	at lmcoursier.internal.shaded.coursier.Resolve$.validate(Resolve.scala:394)
[error] 	at lmcoursier.internal.shaded.coursier.Resolve.validate0$1(Resolve.scala:140)
[error] 	at lmcoursier.internal.shaded.coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:184)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (hello-impl / update) lmcoursier.internal.shaded.coursier.error.ResolutionError$ConflictingDependencies: Conflicting dependencies:
[error] io.grpc:grpc-core:1.16.1:default(compile)
[error] io.grpc:grpc-core:1.20.0:default(compile)
[error] io.grpc:grpc-core:[1.16.1]:default(compile)
[error] io.grpc:grpc-core:[1.20.0]:default(compile)
```

## expectation

Smoother transition.

Is there a way to configure the conflict resolution rules so that it automatically uses the latest? For example in the case of the above, use `io.grpc:grpc-core:1.20.0`?

**Comment by alexarchambault** [comment]
Support for that could definitely be added, but it's not there yet. (Should require some tweaking around [this method](https://github.com/coursier/coursier/blob/afb6378b48bdc2c609b7fb1c16be55324556af1d/modules/core/shared/src/main/scala/coursier/core/Resolution.scala#L217).)

About enabling it from sbt, maybe `conflictManager` (or a rework of it) could do? I recently [added support](https://github.com/coursier/sbt-coursier/pull/99) for a strict conflict manager in coursier, not yet wired in the coursier support in sbt AFAIK.

It would be nice to be able to setup both a default conflict manager (like `conflictManager` allows), and a per module conflict manager, so that users can choose the strict one for some modules, and the "ignore conflicts" one (the one you propose to add above) for others, if they feel like it.

**Comment by eed3si9n** [comment]
How do I write a failing test case for this?

```scala
    'latestWins - {
      * - async {

        val params = ResolutionParams()
          .withScalaVersion("2.12.8")
          // .addRule(
          //   something
          //   RuleResolution.TryResolve
          // )

        val res = await {
          Resolve()
            .noMirrors
            .addDependencies(
              dep"org.typelevel:cats-effect_2.12:1.3.1",
              dep"org.typelevel:cats-core_2.12:1.5.0"
            )
            .addRepositories(Repositories.central)
            .withResolutionParams(params)
            .withCache(cache)
            .future()
        }

        await(validateDependencies(res, params))
      }
    }
```

This gets me

```
X coursier.ResolveRulesTests.latestWins.0 339ms
  coursier.error.ResolutionError$CantDownloadModule: Error downloading org.typelevel:cats-effect_2.12:1.3.1
    Not found: /Users/eed3si9n/.ivy2/local/org.typelevel/cats-effect_2.12/1.3.1/ivys/ivy.xml (No such file or directory)
    not found: modules/tests/metadata/https/repo1.maven.org/maven2/org/typelevel/cats-effect_2.12/1.3.1/cats-effect_2.12-1.3.1.pom
```

**Comment by eed3si9n** [comment]
Here's my PR https://github.com/coursier/coursier/pull/1293
