### ISSUE TITLE
scala-xml in scala-tool configuration gets evicted, causing NoClassDefFoundError on doc task

### ISSUE THREAD

**Issue by eed3si9n** [coursier/coursier#1340]
_Originally posted by @xuwei-k in https://github.com/scala/scala-xml/pull/348#issuecomment-525703962_

## steps

In scala/scala-xml using sbt 1.3.0-RC4

```
sbt
> xml/doc
> show xml/updateFull
```

## problem

https://travis-ci.org/scala/scala-xml/jobs/577682776#L485

<details>

<summary>

```
[error] java.lang.NoClassDefFoundError: scala/xml/NodeSeq
```
</summary>

```
model contains 132 documentable templates
[error] java.lang.NoClassDefFoundError: scala/xml/NodeSeq
[error] 	at scala.tools.nsc.doc.html.HtmlFactory.writeTemplates(HtmlFactory.scala:168)
[error] 	at scala.tools.nsc.doc.html.HtmlFactory.generate(HtmlFactory.scala:156)
[error] 	at scala.tools.nsc.doc.html.Doclet.generateImpl(Doclet.scala:30)
[error] 	at scala.tools.nsc.doc.doclet.Generator.generate(Generator.scala:35)
[error] 	at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:135)
[error] 	at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:138)
[error] 	at xsbt.Runner.run(ScaladocInterface.scala:34)
[error] 	at xsbt.ScaladocInterface.run(ScaladocInterface.scala:19)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:177)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:158)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:39)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:39)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:83)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:76)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$3(RawCompileLike.scala:67)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$3$adapted(RawCompileLike.scala:65)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:72)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:55)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1588)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: scala.xml.NodeSeq
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at scala.tools.nsc.doc.html.HtmlFactory.writeTemplates(HtmlFactory.scala:168)
[error] 	at scala.tools.nsc.doc.html.HtmlFactory.generate(HtmlFactory.scala:156)
[error] 	at scala.tools.nsc.doc.html.Doclet.generateImpl(Doclet.scala:30)
[error] 	at scala.tools.nsc.doc.doclet.Generator.generate(Generator.scala:35)
[error] 	at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:135)
[error] 	at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:138)
[error] 	at xsbt.Runner.run(ScaladocInterface.scala:34)
[error] 	at xsbt.ScaladocInterface.run(ScaladocInterface.scala:19)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:177)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:158)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:39)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:39)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:83)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:76)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$3(RawCompileLike.scala:67)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$3$adapted(RawCompileLike.scala:65)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:72)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:55)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1588)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (xml / Compile / doc) java.lang.NoClassDefFoundError: scala/xml/NodeSeq
```

</details>

`sbt ++2.12.9 doc` fail with sbt 1.3.0-RC4. (success with sbt 1.3.0-RC3)

## expectation

it works.

A sandbox configuration that does not extend `Compile` or `Runtime` should not be affected by the eviction in those configurations. 

## notes by eed3si9n

Here's `show xml/updateFull` results:

### useCoursier

```
[info] 	scala-tool:
....
[info] 	org.scala-lang.modules:scala-xml_2.12
[info] 		- 1.0.6
[info] 			evicted: true
[info] 			evictedData: version selection
[info] 			extraAttributes: Map(info.apiURL -> https://scala.github.io/scala-xml/api/2.0.0/)
[info] 			configurations: plugin, pom, test, provided, compile-internal, docs, optional, compile, test-internal, scala-tool, sources, runtime, runtime-internal
[info] 			callers: org.scala-lang:scala-compiler:2.12.9
[info]
```

### ThisBuild / useCoursier := false

```
[info] 	scala-tool:
...
[info] 	org.scala-lang.modules:scala-xml_2.12
[info] 		- 1.0.6
[info] 			status: release
[info] 			publicationDate: 2016-11-01T10:21:05-04:00
[info] 			resolver: sbt-chain
[info] 			artifactResolver: sbt-chain
[info] 			evicted: false
[info] 			homepage: http://www.scala-lang.org/
[info] 			isDefault: false
[info] 			configurations: compile, runtime(*), master(compile), runtime, compile(*), master
[info] 			licenses: (BSD 3-clause,Some(http://opensource.org/licenses/BSD-3-Clause))
[info] 			callers: org.scala-lang:scala-compiler:2.12.9
```

So with Ivy eviction is localized to a configuration. It appears Coursier is not after https://github.com/coursier/sbt-coursier/pull/101.

**Comment by eed3si9n** [comment]
More report related to this on https://github.com/sbt/sbt/issues/4995. It seems to affect more project than was originally assumed. Not just scala-xml, but likely any build that depends on it.
