### ISSUE TITLE
Exception trying to run coursier on Windows 10

### ISSUE THREAD

**Issue by utahkay** [coursier/coursier#1366]
I get an exception trying to run coursier on Windows 10.

I downloaded coursier with `curl -Lo coursier https://git.io/coursier-cli"

Running from git-bash I get
```$ ./coursier
Exception in thread "main" java.lang.ExceptionInInitializerError
        at coursier.bootstrap.launcher.d.c(Unknown Source)
        at coursier.bootstrap.launcher.a.a(Unknown Source)
        at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "powershell.exe": CreateProcess error=5, Access is denied
        at coursier.bootstrap.launcher.l.a(Unknown Source)
        at coursier.bootstrap.launcher.l.a(Unknown Source)
        at coursier.bootstrap.launcher.j.a(Unknown Source)
        at coursier.bootstrap.launcher.h.a(Unknown Source)
        at coursier.bootstrap.launcher.g.a(Unknown Source)
        at coursier.bootstrap.launcher.b.<clinit>(Unknown Source)
        ... 3 more
Caused by: java.io.IOException: Cannot run program "powershell.exe": CreateProcess error=5, Access is denied
        at java.lang.ProcessBuilder.start(Unknown Source)
        ... 9 more
Caused by: java.io.IOException: CreateProcess error=5, Access is denied
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 10 more```

I get the same exception running coursier.bat from Windows Command Prompt.

I can run powershell.exe myself with no problem.

I'm running Java 8
```$ java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)```

Do you have any ideas what else I might try? Is there perhaps a workaround where I can tell coursier what shell to use?

**Comment by alexarchambault** [comment]
This handled by @soc's [directories-jvm](https://github.com/soc/directories-jvm) library, powershell is run [around here](https://github.com/soc/directories-jvm/blob/d455c96fe31206fd9f52c450c04c3c3b2b73b8a1/src/main/java/io/github/soc/directories/Util.java#L120).

I'm not sure why or how we can get that error.

**Comment by alexarchambault** [comment]
Could this be a corrupt `powershell.exe` like described [here](https://stackoverflow.com/questions/34912830/windows-8-1-cant-start-powershell-from-a-cmd-or-powershell-prompt-this-app-c) or [there](https://stackoverflow.com/questions/32115313/command-prompt-access-denied-when-run-powershell)?

**Comment by utahkay** [comment]
> Could this be a corrupt `powershell.exe` like described here or there?

I don't _think_ so, because I can run powershell.exe just fine from an elevated or non-elevated command prompt,  or also from bash. 

Thanks for the pointer to the relevant code. Does coursier require powershell?

**Comment by soc** [comment]
@utahkay Yes, PowerShell is required. Any further debugging hints are appreciated to identify the root cause.

**Comment by alexarchambault** [comment]
@soc Maybe directories-jvm could accept a custom path to `powershell.exe`, via a Java property say? That would be helpful to debug those cases.

**Comment by soc** [comment]
@alexarchambault Sure, if it helps! But I think it's weird because we are simply relying on the PowerShell that the system gives us ... even if we could specify the path explicitly, I have a bad feeling about second-guessing the operating system.

@utahkay Is there anything special about your system? Developer settings on? WSL1/WSL2 installed? etc.
