### ISSUE TITLE
inter-project dependency with configuration scoping

### ISSUE THREAD

**Issue by eed3si9n** [coursier/coursier#1442]
## steps

scripted test `compiler-project/src-dep-plugin`
https://github.com/sbt/sbt/tree/v1.3.3/sbt/src/sbt-test/compiler-project/src-dep-plugin

## problem

@bjaglin reported in https://github.com/sbt/sbt/pull/5199 that it fails as follows:

https://travis-ci.org/sbt/sbt/jobs/599607627

<details>

<summary>

```scala
Running compiler-project/src-dep-plugin
[info] [info] Loading project definition from /tmp/sbt_a1e8cc4e/project
[info] [info] Compiling 1 Scala source to /tmp/sbt_a1e8cc4e/project/target/scala-2.12/sbt-1.0/classes ...
[info] [info] Done compiling.
[info] [info] Loading settings for project sbt_a1e8cc4e from build.sbt ...
[info] [info] Loading settings for project def from build.sbt ...
[info] [info] Set current project to sbt_a1e8cc4e (in build file:/tmp/sbt_a1e8cc4e/)
[info] [info] Set current project to src-dep-plugin (in build file:/tmp/sbt_a1e8cc4e/)
[info] [warn] 
[info] [warn] 	Note: Unresolved dependencies path:
[info] [error] sbt.librarymanagement.ResolveException: Error downloading org.example:demo-compiler-plugin_2.12:0.1
[info] [error]   Not found
[info] [error]   not found: /home/travis/.ivy2/local/org.example/demo-compiler-plugin_2.12/0.1/ivys/ivy.xml
[info] [error]   not found: https://repo1.maven.org/maven2/org/example/demo-compiler-plugin_2.12/0.1/demo-compiler-plugin_2.12-0.1.pom
```

</summary>

```scala
Running compiler-project/src-dep-plugin
[info] [info] Loading project definition from /tmp/sbt_a1e8cc4e/project
[info] [info] Compiling 1 Scala source to /tmp/sbt_a1e8cc4e/project/target/scala-2.12/sbt-1.0/classes ...
[info] [info] Done compiling.
[info] [info] Loading settings for project sbt_a1e8cc4e from build.sbt ...
[info] [info] Loading settings for project def from build.sbt ...
[info] [info] Set current project to sbt_a1e8cc4e (in build file:/tmp/sbt_a1e8cc4e/)
[info] [info] Set current project to src-dep-plugin (in build file:/tmp/sbt_a1e8cc4e/)
[info] [warn] 
[info] [warn] 	Note: Unresolved dependencies path:
[info] [error] sbt.librarymanagement.ResolveException: Error downloading org.example:demo-compiler-plugin_2.12:0.1
[info] [error]   Not found
[info] [error]   not found: /home/travis/.ivy2/local/org.example/demo-compiler-plugin_2.12/0.1/ivys/ivy.xml
[info] [error]   not found: https://repo1.maven.org/maven2/org/example/demo-compiler-plugin_2.12/0.1/demo-compiler-plugin_2.12-0.1.pom
[info] [error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:245)
[info] [error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:214)
[info] [error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[info] [error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:214)
[info] [error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[info] [error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[info] [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[info] [error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[info] [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[info] [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[info] [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[info] [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[info] [error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[info] [error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[info] [error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2946)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[info] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[info] [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[info] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[info] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[info] [error] 	at sbt.Execute.work(Execute.scala:290)
[info] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[info] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info] [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info] [error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[info] [error] (use / update) sbt.librarymanagement.ResolveException: Error downloading org.example:demo-compiler-plugin_2.12:0.1
[info] [error]   Not found
[info] [error]   not found: /home/travis/.ivy2/local/org.example/demo-compiler-plugin_2.12/0.1/ivys/ivy.xml
[info] [error]   not found: https://repo1.maven.org/maven2/org/example/demo-compiler-plugin_2.12/0.1/demo-compiler-plugin_2.12-0.1.pom
[info] [error] Total time: 1 s, completed Oct 18, 2019, 12:29:20 PM
[error] x compiler-project/src-dep-plugin 
[error]  Cause of test exception: {line 2}  Command failed: use/compile failed
```

</details>

## expectation

The test passes.

## notes

```scala
import Configurations.{CompilerPlugin => CPlugin}

lazy val use = project.dependsOn(RootProject(file("def")) % CPlugin).settings(
  autoCompilerPlugins := true
)
```

This requires that the `CompilerPlugin` configuration of `use` to depend on the `Compile` configuration of `def` subproject, which I think is similar to the concern I raised in https://github.com/coursier/sbt-coursier/pull/136#discussion_r324250741.

Fixing this requires `interProjectDependencies` to carry over the source and target configuration (for example `CompilerPlugin` depending on `Compile` configuration) so during the resolution it can force the version of subproject hopefully without triggering https://github.com/coursier/coursier/issues/1340 again (scala-xml getting evicted during `doc` in scala-xml build).

**Comment by eed3si9n** [comment]
I have a PR for this - https://github.com/coursier/sbt-coursier/pull/158
