### ISSUE TITLE
java.io.IOException: Resource deadlock would occur

### ISSUE THREAD

**Issue by gmarti** [coursier/coursier#1444]
sbt version: 1.3.3

## steps
Running parallel build (2 different jvm) in CI with sbt compile/test in 2 different projects

## problem
Sbt fail with a resource deadlock on coursier cache (not often... difficult to reproduce)

## expectation
It should be possible to run two concurrent build without having coursier deadlock

## notes

<details>

<summary>stack trace</summary>

```
Executing command:sbt -Dprotobufnoembedded clean ${{SBT_DOCKER}} < /dev/null
[info] Loading settings for project dispatch-service-build from plugins.sbt,scalapb.sbt ...
[info] Loading project definition from /codefresh/volume/dispatch-service/project
[info] Loading settings for project dispatch-service from build.sbt ...   
[success] Total time: 1 s, completed Nov 22, 2019 12:00:56 PM
[info] Formatting 74 Scala sources...
[info] Formatting 32 Scala sources...
[info] Formatting 1 Scala sources...
[info] Formatting 31 Scala sources...
[info] Formatting 66 Scala sources...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Compiling 31 Scala sources to /codefresh/volume/dispatch-service/plans/target/scala-2.12/classes ...
[info] Compiling 32 Scala sources to /codefresh/volume/dispatch-service/api/target/scala-2.12/classes ...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@6f8c396 rejected from java.util.concurrent.ThreadPoolExecutor@83f3d39[Shutting down, pool size = 5, active threads = 5, queued tasks = 0, completed tasks = 7797]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@52b1c4b6 rejected from java.util.concurrent.ThreadPoolExecutor@83f3d39[Shutting down, pool size = 4, active threads = 4, queued tasks = 0, completed tasks = 7798]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@6e73c92e rejected from java.util.concurrent.ThreadPoolExecutor@83f3d39[Shutting down, pool size = 3, active threads = 3, queued tasks = 0, completed tasks = 7799]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@38a201c5 rejected from java.util.concurrent.ThreadPoolExecutor@83f3d39[Shutting down, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 7800]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.8. Compiling...
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@516baabf rejected from java.util.concurrent.ThreadPoolExecutor@83f3d39[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 7801]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[info]   Compilation completed in 23.519s.
Waiting for lock on /codefresh/volume/caches/sbt/boot/scala-2.12.10/org.scala-sbt/sbt/1.3.3/sbt.components.lock to be available...
[info] Done compiling.
[info] Done compiling.
[info] Compiling 66 Scala sources to /codefresh/volume/dispatch-service/domain/target/scala-2.12/classes ...
[info] Done compiling.
[error] java.io.IOException: Resource deadlock would occur
[error] 	at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
[error] 	at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:94)
[error] 	at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1072)
[error] 	at java.nio.channels.FileChannel.lock(FileChannel.java:1053)
[error] 	at lmcoursier.internal.shaded.coursier.paths.CachePath.withStructureLock(CachePath.java:132)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withStructureLock(CacheLocks.scala:21)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:38)
[error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$32(FileCache.scala:553)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (infrastructure / update) java.io.IOException: Resource deadlock would occur
[error] Total time: 195 s (03:15), completed Nov 22, 2019 12:04:12 PM
```

</details>

Difficult to reproduce, i have this in only one project for the moment, if you have some clue how i can reduce this to a minimal failing case, help is welcomed

**Comment by alexarchambault** [comment]
@gmarti coursier is supposed to be fine with mulitple processes accessing its cache (or even accessing / trying to download the same file in cache). Do you have more details about your build, the plugins it uses in particular? Some (old versions of some) sbt plugins are known to access the coursier cache in a way that creates such conflicts, like sbt-scalafmt before `2.0.6` or sbt-scalafix before `0.9.7-2`.

**Comment by alexarchambault** [comment]
Some more investigation: this seems to be thrown around [here](https://github.com/openjdk/jdk/blob/7e42642939c0c3b8b872d72890fbb5aab4c3e507/src/java.base/unix/native/libnio/ch/FileDispatcherImpl.c#L260). So that corresponds to a `EDEADLK` returned by a call to [`fcntl`](http://man7.org/linux/man-pages/man2/fcntl.2.html). The [`fcntl` man page](http://man7.org/linux/man-pages/man2/fcntl.2.html) says these can occur when two processes could have deadlocked each other, and I'm not sure how that could happen here…

**Comment by gmarti** [comment]
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.0.6")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.0")
addSbtPlugin("com.codacy" % "sbt-codacy-coverage" % "1.3.15")
addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "1.0.0")
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "2.4.2")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.10")
addSbtPlugin("org.scala-sbt" % "sbt-autoversion" % "1.0.0")⏎
addSbtPlugin("se.marcuslonnberg" % "sbt-docker" % "1.5.0")
This is the plugins we are using in this project

**Comment by alexarchambault** [comment]
@gmarti Is it possible for you to try without sbt-scalafmt? If ever the error never happens without it, that would greatly narrow the parts of the code that could be faulty here.

**Comment by gmarti** [comment]
@alexarchambault Tested without scalafmt and i have the same error (on the other build this time)

Maybe some more logs could help : here are the 2 parallels execution with the logs of the working one and the logs of the failing one.
Same project checked out in 2 different folder
[parallel execution 1, working](https://github.com/coursier/coursier/files/3885608/pipeline_working.log)
[parallel execution 2, failing](https://github.com/coursier/coursier/files/3885610/pipeline_failing.log)

**Comment by eed3si9n** [comment]
I noticed it says:

```
Waiting for lock on /codefresh/volume/caches/sbt/boot/scala-2.12.10/org.scala-sbt/sbt/1.3.3/sbt.components.lock to be available...
```

That's likely from sbt launcher
- https://github.com/sbt/launcher/blob/fbe82523cdfe5453642f1dccbd2415cc806093a1/launcher-implementation/src/main/scala/xsbt/boot/Launch.scala#L256
- https://github.com/sbt/launcher/blob/1.x/launcher-implementation/src/main/scala/xsbt/boot/Locks.scala#L90

So at some point in time two instances of sbt would end up holding on to sbt launcher's lock or Coursier's lock each both waiting on each other? Does that scenario make sense?

**Comment by alexarchambault** [comment]
The workaround for https://github.com/sbt/sbt/issues/650 (linked [here](https://github.com/sbt/launcher/blob/1.x/launcher-implementation/src/main/scala/xsbt/boot/Locks.scala#L55)) can totally be added to the locking logic in coursier.

If that's really the problem, then the [coursier-based sbt launcher](https://github.com/coursier/sbt-launcher) should not have that problem. It [doesn't rely on those file locks](https://github.com/coursier/sbt-launcher/blob/01cda3cda5307508a9135b912e3b1092b8ca07a7/sbt-launcher/src/main/scala/coursier/sbtlauncher/implem/InMemoryGlobalLock.scala#L6), unlike the default launcher.

@gmarti Is it possible for you to try with the [coursier-based sbt launcher](https://github.com/coursier/sbt-launcher), that can be run via [its customized sbt-extras script](https://github.com/coursier/sbt-extras/blob/master/sbt)?

**Comment by gmarti** [comment]
Ok so documentation on coursier/sbt-extras is wrong, it doesn't download the last version.... had to figure this out first :D 
I tried first with https://git.io/sbt and it failed the same
Now i'm using https://raw.githubusercontent.com/coursier/sbt-extras/master/sbt 
and i got `Error while downloading https://repo1.maven.org/maven2/com/github/alexarchambault/case-app-annotations_2.12/2.0.0-M9/case-app-annotations_2.12-2.0.0-M9.jar: Ongoing concurrent downlo
ad for https://repo1.maven.org/maven2/com/github/alexarchambault/case-app-annotations_2.12/2.0.0-M9/case-app-annotations_2.12-2.0.0-M9.jar, ignoring it`

**Comment by gmarti** [comment]
@alexarchambault 
Anything else i can try ?

**Comment by gmarti** [comment]
Anything new here ? @alexarchambault
