### ISSUE TITLE
Transitive dependency on bom poms doesn't download correctly

### ISSUE THREAD

**Issue by anilkumarmyla** [coursier/coursier#1502]
Originally reported as https://github.com/sbt/sbt/issues/5379

## steps
sbt version: 1.3.7

## problem
Any project including bom (bill of materials) pom of aws sdk transitively fails to update with the following error message

build.sbt
```
libraryDependencies +=  "com.yahoo.athenz" % "athenz-zts-java-client-core" % "1.8.43"
resolvers += "bintray-yahoo-maven" at "https://yahoo.bintray.com/maven/"
```

```
sbt update
..
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.amazonaws:aws-java-sdk-sts:${awsjavasdk.version}
[error]   Not found
[error]   Not found
[error]   not found: /Users/anilkumarmyla/.ivy2/local/com.amazonaws/aws-java-sdk-sts/${awsjavasdk.version}/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-sts/${awsjavasdk.version}/aws-java-sdk-sts-${awsjavasdk.version}.pom
[error]   not found: https://yahoo.bintray.com/maven/com/amazonaws/aws-java-sdk-sts/${awsjavasdk.version}/aws-java-sdk-sts-${awsjavasdk.version}.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:246)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:215)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:215)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2947)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:830)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.amazonaws:aws-java-sdk-sts:${awsjavasdk.version}
[error]   Not found
[error]   Not found
[error]   not found: /Users/anilkumarmyla/.ivy2/local/com.amazonaws/aws-java-sdk-sts/${awsjavasdk.version}/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-sts/${awsjavasdk.version}/aws-java-sdk-sts-${awsjavasdk.version}.pom
[error]   not found: https://yahoo.bintray.com/maven/com/amazonaws/aws-java-sdk-sts/${awsjavasdk.version}/aws-java-sdk-sts-${awsjavasdk.version}.pom
```

**Comment by alexarchambault** [comment]
Thanks for the report. That seems to be a regression in `2.0.0-RC5-4`.

**Comment by anilkumarmyla** [comment]
thanks @alexarchambault for the quick fix!
