### ISSUE TITLE
ClassNotFoundException: com.oracle.svm.hosted.NativeImageSystemClassLoader when running cs bootstrap --native-image

### ISSUE THREAD

**Issue by julienrf** [coursier/coursier#1606]
~~~ sh
$ cs bootstrap --native-image scalafmt -o scalafmt
[…]
Error occurred during initialization of VM
java.lang.Error: java.lang.ClassNotFoundException: com.oracle.svm.hosted.NativeImageSystemClassLoader
        at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1463)
        at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1430)
Caused by: java.lang.ClassNotFoundException: com.oracle.svm.hosted.NativeImageSystemClassLoader
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at java.lang.SystemClassLoaderAction.run(ClassLoader.java:2214)
        at java.lang.SystemClassLoaderAction.run(ClassLoader.java:2200)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1450)
        at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1430)

Error: Image build request failed with exit status 1
Exception in thread "main" java.lang.RuntimeException: Error running native-image (exit code: 1)
        at scala.sys.package$.error(package.scala:30)
        at coursier.launcher.NativeImageGenerator$.generate(NativeImageGenerator.scala:106)
        at coursier.launcher.Generator$.generate(Generator.scala:14)
        at coursier.cli.bootstrap.Bootstrap$.run(Bootstrap.scala:364)
        at coursier.cli.Coursier$.$anonfun$runA$2(Coursier.scala:96)
        at coursier.cli.Coursier$.$anonfun$runA$2$adapted(Coursier.scala:94)
        at coursier.cli.CommandAppPreA.run(CommandAppPreA.scala:22)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5(CommandAppWithPreCommand.scala:99)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5$adapted(CommandAppWithPreCommand.scala:99)
        at scala.util.Either.fold(Either.scala:191)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3(CommandAppWithPreCommand.scala:99)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3$adapted(CommandAppWithPreCommand.scala:85)
        at scala.Option.foreach(Option.scala:407)
        at caseapp.core.app.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:85)
        at coursier.cli.Coursier$.main(Coursier.scala:69)
        at coursier.cli.Coursier.main(Coursier.scala)
~~~

I’m happy to provide any other relevant information for reproducing the problem.

**Comment by alexarchambault** [comment]
Try with `--graalvm 19.3`. The graalvm version is used at two places, and there's possibly a mismatch between them now that graalvm 20 is out.

**Comment by julienrf** [comment]
With `--graalvm 19.3` I get the following error instead:

~~~
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.scalafmt.internal.FormatWriter.reflMethod$Method1(java.lang.Class) 
Parsing context:
        parsing org.scalafmt.internal.FormatWriter.alignmentTokens(FormatWriter.scala:564)
        parsing org.scalafmt.internal.FormatWriter$FormatLocations.<init>(FormatWriter.scala:258)
        parsing org.scalafmt.internal.FormatWriter.getFormatLocations(FormatWriter.scala:154)
        parsing org.scalafmt.internal.FormatWriter.mkString(FormatWriter.scala:26)
        parsing org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:73)
        parsing org.scalafmt.cli.ScalafmtCoreRunner$.unsafeHandleFile(ScalafmtCoreRunner.scala:87)
        parsing org.scalafmt.cli.ScalafmtCoreRunner$.handleFile(ScalafmtCoreRunner.scala:66)
        parsing org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$3(ScalafmtCoreRunner.scala:44)
        parsing org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$3$adapted(ScalafmtCoreRunner.scala:43)
        parsing org.scalafmt.cli.ScalafmtCoreRunner$$$Lambda$142/457052412.apply(Unknown Source)
        parsing scopt.Validation$.$anonfun$validateValue$1(options.scala:133)
        parsing scopt.Validation$$$Lambda$116/322201892.apply(Unknown Source)
        parsing scala.collection.immutable.List.map(List.scala:219)
        parsing scopt.OptionParser.showTryHelp(options.scala:259)
        parsing scopt.OptionParser.parse(options.scala:563)
        parsing org.scalafmt.cli.Cli$.getConfig(Cli.scala:75)
        parsing org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:68)
        parsing org.scalafmt.cli.Cli$.main(Cli.scala:58)
        parsing org.scalafmt.cli.Cli.main(Cli.scala)
        parsing com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
        parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
        parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

        at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:327)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
        at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:511)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of scala.runtime.StructuralCallSite are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.checkImageHeapInstance(ClassInitializationFeature.java:173)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:534)
        at com.oracle.svm.hosted.analysis.flow.SVMMethodTypeFlowBuilder.registerUsedElements(SVMMethodTypeFlowBuilder.java:82)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:229)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
        ... 10 more
warning: unknown anonymous info of class scala.meta.tokens.Token$Constant$Float, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by scala.meta.tokens.Token$Constant$Float which is not following the naming convention.
warning: unknown anonymous info of class scala.meta.tokens.Token$Constant$Double, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by scala.meta.tokens.Token$Constant$Double which is not following the naming convention.
Error: Image build request failed with exit status 1
Exception in thread "main" java.lang.RuntimeException: Error running native-image (exit code: 1)
        at scala.sys.package$.error(package.scala:30)
        at coursier.launcher.NativeImageGenerator$.generate(NativeImageGenerator.scala:106)
        at coursier.launcher.Generator$.generate(Generator.scala:14)
        at coursier.cli.bootstrap.Bootstrap$.run(Bootstrap.scala:364)
        at coursier.cli.Coursier$.$anonfun$runA$2(Coursier.scala:96)
        at coursier.cli.Coursier$.$anonfun$runA$2$adapted(Coursier.scala:94)
        at coursier.cli.CommandAppPreA.run(CommandAppPreA.scala:22)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5(CommandAppWithPreCommand.scala:99)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5$adapted(CommandAppWithPreCommand.scala:99)
        at scala.util.Either.fold(Either.scala:191)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3(CommandAppWithPreCommand.scala:99)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3$adapted(CommandAppWithPreCommand.scala:85)
        at scala.Option.foreach(Option.scala:407)
        at caseapp.core.app.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:85)
        at coursier.cli.Coursier$.main(Coursier.scala:69)
        at coursier.cli.Coursier.main(Coursier.scala)
~~~

**Comment by julienrf** [comment]
With `--graalvm 19.3` I get the following error instead:

~~~
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.scalafmt.internal.FormatWriter.reflMethod$Method1(java.lang.Class) 
Parsing context:
        parsing org.scalafmt.internal.FormatWriter.alignmentTokens(FormatWriter.scala:564)
        parsing org.scalafmt.internal.FormatWriter$FormatLocations.<init>(FormatWriter.scala:258)
        parsing org.scalafmt.internal.FormatWriter.getFormatLocations(FormatWriter.scala:154)
        parsing org.scalafmt.internal.FormatWriter.mkString(FormatWriter.scala:26)
        parsing org.scalafmt.Scalafmt$.formatCode(Scalafmt.scala:73)
        parsing org.scalafmt.cli.ScalafmtCoreRunner$.unsafeHandleFile(ScalafmtCoreRunner.scala:87)
        parsing org.scalafmt.cli.ScalafmtCoreRunner$.handleFile(ScalafmtCoreRunner.scala:66)
        parsing org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$3(ScalafmtCoreRunner.scala:44)
        parsing org.scalafmt.cli.ScalafmtCoreRunner$.$anonfun$run$3$adapted(ScalafmtCoreRunner.scala:43)
        parsing org.scalafmt.cli.ScalafmtCoreRunner$$$Lambda$142/457052412.apply(Unknown Source)
        parsing scopt.Validation$.$anonfun$validateValue$1(options.scala:133)
        parsing scopt.Validation$$$Lambda$116/322201892.apply(Unknown Source)
        parsing scala.collection.immutable.List.map(List.scala:219)
        parsing scopt.OptionParser.showTryHelp(options.scala:259)
        parsing scopt.OptionParser.parse(options.scala:563)
        parsing org.scalafmt.cli.Cli$.getConfig(Cli.scala:75)
        parsing org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:68)
        parsing org.scalafmt.cli.Cli$.main(Cli.scala:58)
        parsing org.scalafmt.cli.Cli.main(Cli.scala)
        parsing com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:151)
        parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
        parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

        at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:327)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
        at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:511)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of scala.runtime.StructuralCallSite are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.checkImageHeapInstance(ClassInitializationFeature.java:173)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:534)
        at com.oracle.svm.hosted.analysis.flow.SVMMethodTypeFlowBuilder.registerUsedElements(SVMMethodTypeFlowBuilder.java:82)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:229)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
        ... 10 more
warning: unknown anonymous info of class scala.meta.tokens.Token$Constant$Float, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by scala.meta.tokens.Token$Constant$Float which is not following the naming convention.
warning: unknown anonymous info of class scala.meta.tokens.Token$Constant$Double, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by scala.meta.tokens.Token$Constant$Double which is not following the naming convention.
Error: Image build request failed with exit status 1
Exception in thread "main" java.lang.RuntimeException: Error running native-image (exit code: 1)
        at scala.sys.package$.error(package.scala:30)
        at coursier.launcher.NativeImageGenerator$.generate(NativeImageGenerator.scala:106)
        at coursier.launcher.Generator$.generate(Generator.scala:14)
        at coursier.cli.bootstrap.Bootstrap$.run(Bootstrap.scala:364)
        at coursier.cli.Coursier$.$anonfun$runA$2(Coursier.scala:96)
        at coursier.cli.Coursier$.$anonfun$runA$2$adapted(Coursier.scala:94)
        at coursier.cli.CommandAppPreA.run(CommandAppPreA.scala:22)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5(CommandAppWithPreCommand.scala:99)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5$adapted(CommandAppWithPreCommand.scala:99)
        at scala.util.Either.fold(Either.scala:191)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3(CommandAppWithPreCommand.scala:99)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3$adapted(CommandAppWithPreCommand.scala:85)
        at scala.Option.foreach(Option.scala:407)
        at caseapp.core.app.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:85)
        at coursier.cli.Coursier$.main(Coursier.scala:69)
        at coursier.cli.Coursier.main(Coursier.scala)
~~~

**Comment by alexarchambault** [comment]
`scalafmt` [as an app](https://github.com/coursier/apps/blob/master/apps/resources/scalafmt.json) isn't meant to be passed to native-image as is. You'll have to find the combination of graalvm options (can then be passed each at a time with `--graalvm-opt`) that works.

It seems scalafmt builds its native-image with [these options](https://github.com/scalameta/scalafmt/blob/b7a1b0fec579992210de6a25aa514b73fe12af65/build.sbt#L192-L203). These options could be embedded in the scalafmt JARs, like [it's done in coursier](https://github.com/coursier/coursier/blob/master/modules/cli/src/main/resources/META-INF/native-image/io.get-coursier/coursier-cli/native-image.properties).
