### ISSUE TITLE
Fix graalvm / install related issues

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#1613]
Seems the following doesn't work:
```bash
$ cs install echo-graalvm
Error occurred during initialization of VM
java.lang.Error: java.lang.ClassNotFoundException: com.oracle.svm.hosted.NativeImageSystemClassLoader
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1463)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1430)
Caused by: java.lang.ClassNotFoundException: com.oracle.svm.hosted.NativeImageSystemClassLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.lang.SystemClassLoaderAction.run(ClassLoader.java:2214)
	at java.lang.SystemClassLoaderAction.run(ClassLoader.java:2200)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1450)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1430)

Error: Image build request failed with exit status 1
Exception in thread "main" java.lang.RuntimeException: Error running native-image (exit code: 1)
	at scala.sys.package$.error(package.scala:30)
	at coursier.launcher.NativeImageGenerator$.generate(NativeImageGenerator.scala:106)
	at coursier.launcher.Generator$.generate(Generator.scala:14)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$27(InstallDir.scala:285)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at coursier.install.InstallDir$.coursier$install$InstallDir$$writing(InstallDir.scala:449)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$12(InstallDir.scala:285)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$12$adapted(InstallDir.scala:159)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$29(InstallDir.scala:314)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$29$adapted(InstallDir.scala:313)
	at coursier.install.Updatable$.get$1(Updatable.scala:74)
	at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:115)
	at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:59)
	at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:84)
	at coursier.install.Updatable$.writing(Updatable.scala:115)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:313)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:77)
	at coursier.cli.install.Install$.$anonfun$run$9(Install.scala:112)
	at coursier.cli.install.Install$.$anonfun$run$9$adapted(Install.scala:99)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at coursier.cli.install.Install$.run(Install.scala:99)
	at coursier.cli.Coursier$.$anonfun$runA$2(Coursier.scala:102)
	at coursier.cli.Coursier$.$anonfun$runA$2$adapted(Coursier.scala:94)
	at coursier.cli.CommandAppPreA.run(CommandAppPreA.scala:22)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5(CommandAppWithPreCommand.scala:99)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5$adapted(CommandAppWithPreCommand.scala:99)
	at scala.util.Either.fold(Either.scala:191)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3(CommandAppWithPreCommand.scala:99)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3$adapted(CommandAppWithPreCommand.scala:85)
	at scala.Option.foreach(Option.scala:407)
	at caseapp.core.app.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:85)
	at coursier.cli.Coursier$.main(Coursier.scala:69)
	at coursier.cli.Coursier.main(Coursier.scala)
```

Passing an explicit graalvm version doesn't fix it:
```bash
$ cs install echo-graalvm --graalvm-default-version 19.3
https://repo1.maven.org/maven2/io/get-coursier/echo/maven-metadata.xml
  No new update since 2019-05-28 21:08:32
https://github.com/shyiko/jabba/raw/master/index.json
  No modified time in response
https://repo1.maven.org/maven2/org/graalvm/nativeimage/svm-driver/maven-metadat…
  No new update since 2020-02-18 19:09:48
Error occurred during initialization of VM
java.lang.Error: java.lang.ClassNotFoundException: com.oracle.svm.hosted.NativeImageSystemClassLoader
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1463)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1430)
Caused by: java.lang.ClassNotFoundException: com.oracle.svm.hosted.NativeImageSystemClassLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.lang.SystemClassLoaderAction.run(ClassLoader.java:2214)
	at java.lang.SystemClassLoaderAction.run(ClassLoader.java:2200)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1450)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1430)

Error: Image build request failed with exit status 1
Exception in thread "main" java.lang.RuntimeException: Error running native-image (exit code: 1)
	at scala.sys.package$.error(package.scala:30)
	at coursier.launcher.NativeImageGenerator$.generate(NativeImageGenerator.scala:106)
	at coursier.launcher.Generator$.generate(Generator.scala:14)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$27(InstallDir.scala:285)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at coursier.install.InstallDir$.coursier$install$InstallDir$$writing(InstallDir.scala:449)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$12(InstallDir.scala:285)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$12$adapted(InstallDir.scala:159)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$29(InstallDir.scala:314)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$29$adapted(InstallDir.scala:313)
	at coursier.install.Updatable$.get$1(Updatable.scala:74)
	at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:115)
	at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:59)
	at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:84)
	at coursier.install.Updatable$.writing(Updatable.scala:115)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:313)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:77)
	at coursier.cli.install.Install$.$anonfun$run$9(Install.scala:112)
	at coursier.cli.install.Install$.$anonfun$run$9$adapted(Install.scala:99)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at coursier.cli.install.Install$.run(Install.scala:99)
	at coursier.cli.Coursier$.$anonfun$runA$2(Coursier.scala:102)
	at coursier.cli.Coursier$.$anonfun$runA$2$adapted(Coursier.scala:94)
	at coursier.cli.CommandAppPreA.run(CommandAppPreA.scala:22)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5(CommandAppWithPreCommand.scala:99)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5$adapted(CommandAppWithPreCommand.scala:99)
	at scala.util.Either.fold(Either.scala:191)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3(CommandAppWithPreCommand.scala:99)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3$adapted(CommandAppWithPreCommand.scala:85)
	at scala.Option.foreach(Option.scala:407)
	at caseapp.core.app.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:85)
	at coursier.cli.Coursier$.main(Coursier.scala:69)
	at coursier.cli.Coursier.main(Coursier.scala)
```

(reported on gitter by @tpolecat, @lavrov)

**Comment by tpolecat** [comment]
Any ideas on this? It might make sense to remove mention of `"launcherType": "graalvm-native-image"` until there's a resolution.
