### ISSUE TITLE
Resolution error for tab completion (scalafixEnable) within sbt

### ISSUE THREAD

**Issue by kamilkloch** [coursier/coursier#1615]
```
sbt:x-scala> scalaf <tab>
```
results in
```sbt
sbt:x-scala> scalafcoursierapi.error.SimpleResolutionError$1: Error downloading ch.epfl.scala:scalafix-cli_2.12.10:0.9.11
  org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 55; White spaces are required between publicId and systemId. (White spaces are required between publicId and systemId.)
        at coursierapi.error.SimpleResolutionError.of(SimpleResolutionError.java:11)
        at coursierapi.shaded.coursier.internal.api.ApiHelper$.simpleResError(ApiHelper.scala:271)
        at coursierapi.shaded.coursier.internal.api.ApiHelper$.doFetch(ApiHelper.scala:297)
	at coursierapi.shaded.coursier.internal.api.ApiHelper.doFetch(ApiHelper.scala)
	at coursierapi.Fetch.fetchResult(Fetch.java:219)
	at coursierapi.Fetch.fetch(Fetch.java:214)
	at scalafix.internal.sbt.ScalafixCoursier$.runFetch(ScalafixCoursier.scala:88)
	at scalafix.internal.sbt.ScalafixCoursier$.scalafixCliJars(ScalafixCoursier.scala:30)
	at scalafix.internal.sbt.ScalafixInterface$.$anonfun$fromToolClasspath$1(ScalafixInterface.scala:22)
```

sbt 1.3.8.

**Comment by kamilkloch** [comment]
It get worse. Scalafix rules do not work at all:
```sbt
sbt:x-scala> scalafix X011_TradeStatistics_setBars
ch.epfl.scala:scalafix-cli_2.12.10:0.9.11
[error]   org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 55; White spaces are required between publicId and systemId. (White spaces are required between publicId and systemId.)

```

**Comment by alexarchambault** [comment]
@kamilkloch Do you have a project reproducing this? `ch.epfl.scala:scalafix-cli_2.12.10:0.9.11` is resolved fine by coursier:
```bash
$ cs resolve ch.epfl.scala:scalafix-cli_2.12.10:0.9.11
ch.epfl.scala:scalafix-cli_2.12.10:0.9.11:default
ch.epfl.scala:scalafix-core_2.12:0.9.11:default
…
```

Same with old coursier versions.

**Comment by kamilkloch** [comment]
I cannot share the project easily... Scalafix rules are downloaded from a private Artifactory repo, can this be the culprit? Like here: https://github.com/scalacenter/scalafix/issues/1049

**Comment by kamilkloch** [comment]
Also, due to https://github.com/sbt/sbt/issues/5050#issuecomment-528931905 I have Coursier disabled in the project and build project. Why does sbt use coursier in the first place?

**Comment by kamilkloch** [comment]
Apologies for a false alarm, my bad: instead of 
```sbt
scalafixResolvers in ThisBuild ++= ...
```
the project had
```sbt
scalafixResolvers in ThisBuild := ...
```
...
