### ISSUE TITLE
cs install with url channel fails

### ISSUE THREAD

**Issue by tpolecat** [coursier/coursier#1663]
Hi, I tried to use cs install to install from an application definition on gh, thus:

```
cs install --channel https://raw.githubusercontent.com/gemini-hlsw/itac/cli/cs/itac.json itac
```

And it failed, claiming a decoding error :

```
https://raw.githubusercontent.com/gemini-hlsw/itac/cli/cs/itac.json
  No modified time in response
Exception in thread "main" java.lang.Exception: Error decoding /Users/rnorris/.coursier/cache/v1/https/raw.githubusercontent.com/gemini-hlsw/itac/cli/cs/itac.json (https://raw.githubusercontent.com/gemini-hlsw/itac/cli/cs/itac.json): Expected object: CursorHistory(List(El(CursorOpDownField(repositories),true)))
	at coursier.install.Channels.$anonfun$find$20(Channels.scala:141)
	at scala.util.Either$LeftProjection.map(Either.scala:573)
	at coursier.install.Channels.$anonfun$find$19(Channels.scala:141)
	at coursier.install.Channels.$anonfun$find$19$adapted(Channels.scala:135)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

However if I then try to use the downloaded file referenced in the error message it works!

```
~$ cs install --channel /Users/rnorris/.coursier/cache/v1/https/raw.githubusercontent.com/gemini-hlsw/itac/cli/cs itac
Wrote itac
```

Any ideas?

**Comment by alexarchambault** [comment]
@tpolecat That's because `https://raw.githubusercontent.com/gemini-hlsw/itac/cli/cs/itac.json` designates an app descriptor, not a channel per se. That would be the same with `/Users/rnorris/.coursier/cache/v1/https/raw.githubusercontent.com/gemini-hlsw/itac/cli/cs/itac.json` for example (JSON file, not directory).

To make it a channel, you can transform it like
```json
{
  "itac": {
    "repositories": [
      "central",
      "sonatype:public",
      "https://github.com/gemini-hlsw/maven-repo/raw/master/releases",
      "ivy2Local"
    ],
    "dependencies": [
      "edu.gemini:itc-cli-main_2.12:latest.release"
    ]
  }
}
```

That also allows to add more apps to it.

**Comment by alexarchambault** [comment]
But maybe support for using a single app descriptor as a channel should be added… I've been bitten by that too in the past.

**Comment by tpolecat** [comment]
Aha ok, I misread the documentation. Thanks!:+1:
