### ISSUE TITLE
/usr/libexec/java_home does not work with Java installed via coursier

### ISSUE THREAD

**Issue by mushtaq** [coursier/coursier#1684]
Steps

```txt
~ eval "$(cs java --jvm 11 --env)"
~ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
~ /usr/libexec/java_home
Unable to find any JVMs matching version "(null)".
No Java runtime present, try --request to install.
~
```

**Comment by mushtaq** [comment]
BTW, `cs java-home` works as expected.

The problem is, a third party program is using `/usr/libexec/java_home` to determine JAVA_HOME and that can not be altered.

Any workaround possible?

**Comment by mushtaq** [comment]
One more thing, the external program is `jep`. And `pip install jep` throws:

```txt
Collecting jep
  Using cached jep-3.9.0.tar.gz (3.0 MB)
    ERROR: Command errored out with exit status 1:
     command: /Users/mushtaqahmed/Downloads/polynote/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/8d/nrdzx4s96fnchgk89vlcbbyh0000gn/T/pip-install-47z9ggl5/jep/setup.py'"'"'; __file__='"'"'/private/var/folders/8d/nrdzx4s96fnchgk89vlcbbyh0000gn/T/pip-install-47z9ggl5/jep/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/8d/nrdzx4s96fnchgk89vlcbbyh0000gn/T/pip-install-47z9ggl5/jep/pip-egg-info
         cwd: /private/var/folders/8d/nrdzx4s96fnchgk89vlcbbyh0000gn/T/pip-install-47z9ggl5/jep/
    Complete output (9 lines):
    numpy include found at /Users/mushtaqahmed/Downloads/polynote/.venv/lib/python3.7/site-packages/numpy/core/include
    Traceback (most recent call last):
      File "/private/var/folders/8d/nrdzx4s96fnchgk89vlcbbyh0000gn/T/pip-install-47z9ggl5/jep/commands/java.py", line 36, in get_java_home
        result = shell('/usr/libexec/java_home')
      File "/private/var/folders/8d/nrdzx4s96fnchgk89vlcbbyh0000gn/T/pip-install-47z9ggl5/jep/commands/util.py", line 104, in shell
        raise CommandError(message=msg, result=result)
    commands.util.CommandError: Encountered an error (return code 1) while executing '/usr/libexec/java_home'
    Error:
    Include folder should be at '/System/Library/Frameworks/JavaVM.framework/Headers' but doesn't exist. Please check you've installed the JDK properly.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by alexarchambault** [comment]
AFAIU, `/usr/libexec/java_home` is mostly for JVMs installed under `/Library/Java/JavaVirtualMachines`. It doesn't take into account `JAVA_HOME`, which is the env var we're using here to set the JVM. sdkman is [having the same issue](https://github.com/sdkman/sdkman-cli/wiki/FAQ#on-mac-usrlibexecjava_home-does-not-detect-alternatives-installed-by-sdkman-what-can-i-do).

**Comment by mushtaq** [comment]
I see. Will raise an issue in `jep` repo then. They should be directly using the value of $JAVA_HOME rather than replying on `/usr/libexec/java_home`

**Comment by mushtaq** [comment]
Created https://github.com/ninia/jep/issues/244

**Comment by mushtaq** [comment]
This issue also affects does usage of Ammonite scripts in IntelliJ. 

I opened an issue here: https://youtrack.jetbrains.com/issue/SCL-18258

Request others who is encountering this to please upvote there.

@alexarchambault Any suggestions on how to workaround this in IntelliJ?

**Comment by huanyang01** [comment]
Using "brew install openjdk@8", it can be seen via "java -version", but not in the list of "/usr/libexec/java_home -V"
Do you have any suggestions?

macOS Monterey 
Version  12.5.1

(base) i311414@C02G225GMD6T JavaVirtualMachines % /usr/libexec/java_home -V
Matching Java Virtual Machines (2):
    18.0.2 (x86_64) "Oracle Corporation" - "OpenJDK 18.0.2" /Users/i311414/Library/Java/JavaVirtualMachines/openjdk-18.0.2/Contents/Home
    17.0.4 (x86_64) "SAP SE" - "SapMachine 17.0.4" /Users/i311414/Library/Java/JavaVirtualMachines/sapmachine-17.0.4/Contents/Home
/Users/i311414/Library/Java/JavaVirtualMachines/openjdk-18.0.2/Contents/Home
(base) i311414@C02G225GMD6T JavaVirtualMachines % /usr/libexec/java_home -v
java_home: option requires an argument -- v
/Users/i311414/Library/Java/JavaVirtualMachines/openjdk-18.0.2/Contents/Home
(base) i311414@C02G225GMD6T JavaVirtualMachines % java -version
openjdk version "1.8.0_345"
OpenJDK Runtime Environment (build 1.8.0_345-bre_2022_08_04_23_35-b00)
OpenJDK 64-Bit Server VM (build 25.345-b00, mixed mode)

**Comment by SergiyKolesnikov** [comment]
My current workaround (after setting `JAVA_HOME`) is to create a symlink in `/Library/Java/JavaVirtualMachines` pointing to the JDK location:
```
sudo ln -sfn "$(cs java-home)/../.." /Library/Java/JavaVirtualMachines/coursier.jdk
```
This command needs to be rerun every time the default Coursier JDK is changed.

This will make `/usr/libexec/java_home` work as expected and the apps relying on it will work too. In my case it was Java VisualVM that didn't want to start.

StackOverflow post that helped me to find the workaround: https://stackoverflow.com/a/73040512/6942134
