### ISSUE TITLE
cs complete doesn't seem to honour the :: shorthand

### ISSUE THREAD

**Issue by dwijnand** [coursier/coursier#1701]
```
$ cs complete com.typesafe::mima-core:
Exception in thread "main" coursier.core.Repository$Complete$MalformedInput: Malformed input 'com.typesafe::mima-core:'
	at coursier.core.Repository$Complete$.parse(Repository.scala:301)
	at coursier.complete.Complete.result(Complete.scala:48)
	at coursier.cli.complete.Complete$.run(Complete.scala:30)
	at coursier.cli.Coursier$.$anonfun$runA$2(Coursier.scala:113)
	at coursier.cli.Coursier$.$anonfun$runA$2$adapted(Coursier.scala:109)
	at coursier.cli.CommandAppPreA.run(CommandAppPreA.scala:22)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5(CommandAppWithPreCommand.scala:99)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5$adapted(CommandAppWithPreCommand.scala:99)
	at scala.util.Either.fold(Either.scala:191)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3(CommandAppWithPreCommand.scala:99)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3$adapted(CommandAppWithPreCommand.scala:85)
	at scala.Option.foreach(Option.scala:407)
	at caseapp.core.app.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:85)
	at coursier.cli.Coursier$.main(Coursier.scala:75)
	at coursier.cli.Coursier.main(Coursier.scala)
```

vs

```
$ cs complete com.typesafe:mima-core_2.12:
0.6.4+12-972e1a7f
0.6.4+22-4943295e
0.6.4+26-cf835c11
0.7.0+25-6a15f835+20200430-0828
0.7.0+25-6a15f835
0.1.14
0.1.15
0.1.16
0.1.17
0.1.18
0.2.0
0.3.0
0.4.0
0.5.0
0.6.0
0.6.1
0.6.2
0.6.3
0.6.4
0.7.0
$ cs complete com.typesafe:mima-core_2.13:
$
```

**Comment by alexarchambault** [comment]
You have to pass a scala version for `::` to be accepted, like
```bash
$ cs complete com.typesafe::mima-core: --scala-version 2.12
0.1.14
0.1.15
0.1.16
0.1.17
0.1.18
0.2.0
0.3.0
0.4.0
0.5.0
0.6.0
0.6.1
0.6.2
0.6.3
0.6.4
0.7.0
```

**Comment by alexarchambault** [comment]
That said, it would make sense to have a sensible default one here…

**Comment by dwijnand** [comment]
Good to know.  Yeah, either both `complete` and everything else should require something or they should both have some default.
