### ISSUE TITLE
Cache migration tool doesn't move to correct directory on MacOS

### ISSUE THREAD

**Issue by callado4** [coursier/coursier#1731]
I did not have coursier installed before, but it was being used by sbt once we updated to using sbt 1.3.10.  Even before I installed coursier, I did notice that the cache location being used was 
```
/.coursier/cache/v1
```

I installed coursier using hombrew with `brew install coursier/formulas/coursier`. As soon as it was done I ran `cs --help` and got this output
```
$ cs --help
Warning: a legacy coursier cache was found at /Users/<USER>/.coursier/cache/v1 and is currently being used.

Support for that cache location will be removed in coursier 2.0.0 final, whose release is imminent.

Follow the instructions at
  https://github.com/coursier/cache-migration#cache-migration
in order to migrate your cache to the newer location.


Coursier 2.0.0-RC6-18
Usage: cs [options] [command] [command-options]

Available commands: bootstrap, complete, fetch, install, java, java-home, launch, list, publish, resolve, setup, uninstall, update

Type  cs command --help  for help on an individual command
```

Before doing anything I decided to run `cs list` just to see what would happen and I got an exception shown, and again it mentioned that my cache directory was wrong
```
$ cs list
Warning: a legacy coursier cache was found at /Users/<USER>/.coursier/cache/v1 and is currently being used.

Support for that cache location will be removed in coursier 2.0.0 final, whose release is imminent.

Follow the instructions at
  https://github.com/coursier/cache-migration#cache-migration
in order to migrate your cache to the newer location.


Exception in thread "main" java.nio.file.NoSuchFileException: /Users/<USER>/Library/Application Support/Coursier/bin
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:407)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at java.nio.file.Files.list(Files.java:3451)
	at coursier.install.Updatable$.list(Updatable.scala:20)
	at coursier.cli.install.List$.run(List.scala:10)
	at coursier.cli.Coursier$.$anonfun$runA$2(Coursier.scala:129)
	at coursier.cli.Coursier$.$anonfun$runA$2$adapted(Coursier.scala:113)
	at coursier.cli.CommandAppPreA.run(CommandAppPreA.scala:22)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5(CommandAppWithPreCommand.scala:99)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5$adapted(CommandAppWithPreCommand.scala:99)
	at scala.util.Either.fold(Either.scala:191)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3(CommandAppWithPreCommand.scala:99)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3$adapted(CommandAppWithPreCommand.scala:85)
	at scala.Option.foreach(Option.scala:407)
	at caseapp.core.app.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:85)
	at coursier.cli.Coursier$.main(Coursier.scala:78)
	at coursier.cli.Coursier.main(Coursier.scala)
```

So I decide to follow the instructions shown at https://github.com/coursier/cache-migration#cache-migration.  First it suggests a dry run with:
```
cs launch --contrib cache-migration -- --dry-run
Warning: a legacy coursier cache was found at /Users/<USER>/.coursier/cache/v1 and is currently being used.

Support for that cache location will be removed in coursier 2.0.0 final, whose release is imminent.

Follow the instructions at
  https://github.com/coursier/cache-migration#cache-migration
in order to migrate your cache to the newer location.


(DRY RUN) Moving /Users/<USER>/.coursier/cache/v1 to /Users/<USER>/Library/Caches/Coursier/v1
```

Ok, no errors, it looks fine, so I go ahead and run it (like the instructions say)
```
cs launch --contrib cache-migration
Warning: a legacy coursier cache was found at /Users/<USER>/.coursier/cache/v1 and is currently being used.

Support for that cache location will be removed in coursier 2.0.0 final, whose release is imminent.

Follow the instructions at
  https://github.com/coursier/cache-migration#cache-migration
in order to migrate your cache to the newer location.


Moving /Users/<USER>/.coursier/cache/v1 to /Users/<USER>/Library/Caches/Coursier/v1
```

Ok so it seems like it worked, great!

Now let's try `cs list` again
```
cs list
Exception in thread "main" java.nio.file.NoSuchFileException: /Users/<USER>/Library/Application Support/Coursier/bin
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:407)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at java.nio.file.Files.list(Files.java:3451)
	at coursier.install.Updatable$.list(Updatable.scala:20)
	at coursier.cli.install.List$.run(List.scala:10)
	at coursier.cli.Coursier$.$anonfun$runA$2(Coursier.scala:129)
	at coursier.cli.Coursier$.$anonfun$runA$2$adapted(Coursier.scala:113)
	at coursier.cli.CommandAppPreA.run(CommandAppPreA.scala:22)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5(CommandAppWithPreCommand.scala:99)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5$adapted(CommandAppWithPreCommand.scala:99)
	at scala.util.Either.fold(Either.scala:191)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3(CommandAppWithPreCommand.scala:99)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3$adapted(CommandAppWithPreCommand.scala:85)
	at scala.Option.foreach(Option.scala:407)
	at caseapp.core.app.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:85)
	at coursier.cli.Coursier$.main(Coursier.scala:78)
	at coursier.cli.Coursier.main(Coursier.scala)
```

It still doesn't work 😞 

I _think_ that maybe if I just manually move the cache to `~/Library/Application Support/Coursier/???` it will work but I'm not sure since `cs list` is complaining about a missing bin folder

I believe my problem is related to https://github.com/coursier/coursier/issues/1483 but that one is still open and it doesn't seem like there has been agreement amongst all parties.

I also want to point out that for many of us who get coursier for "free" via sbt, installing coursier separately shouldn't break our existing workflow.  I understand that right now there might be different locations of the cache directory used based on which one was installed but it should just work (and not break the embedded coursier of sbt).

**Comment by alexarchambault** [comment]
`cs list` doesn't list what's in cache. It lists the apps in the [app directory](https://get-coursier.io/docs/cli-install.html#installation-directory). The cache migration worked, you didn't get the warning the second time you ran `cs list`.

`cs list` just wasn't fine with a non-existing app directory, hence the error you're seeing in both cases. https://github.com/coursier/coursier/pull/1732 should fix that.
