### ISSUE TITLE
ZipException during cs setup

### ISSUE THREAD

**Issue by olafurpg** [coursier/coursier#1761]
Congrats on the release of `cs setup`! I am super excited to be able to replace `jabba` with `cs` to manage my JVM installations. I upgraded coursier via homebrew and ran `cs setup` and got the following error
```
❯ cs --help
Coursier 2.0.0-RC6-10
...
❯ cs setup
Checking if a JVM is installed
Found a JVM installed under /Library/Java/JavaVirtualMachines/TwitterJDK/Contents/Home.

Checking if ~/Library/Application Support/Coursier/bin is in PATH

Checking if the standard Scala applications are installed
  Installed ammonite
Exception in thread "main" java.lang.Exception: Reading /Users/lgeirsson/Library/Application Support/Coursier/bin/cs
	at coursier.install.InfoFile$.liftedTree1$1(InfoFile.scala:186)
	at coursier.install.InfoFile$.upToDate(InfoFile.scala:155)
	at coursier.install.InstallDir.upToDate$lzycompute$1(InstallDir.scala:168)
	at coursier.install.InstallDir.upToDate$1(InstallDir.scala:163)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$12(InstallDir.scala:171)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$12$adapted(InstallDir.scala:159)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$29(InstallDir.scala:314)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$29$adapted(InstallDir.scala:313)
	at coursier.install.Updatable$.get$1(Updatable.scala:74)
	at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:115)
	at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:59)
	at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:84)
	at coursier.install.Updatable$.writing(Updatable.scala:115)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:313)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:77)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:52)
	at coursier.cli.setup.MaybeInstallApps.$anonfun$task$3(MaybeInstallApps.scala:22)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.util.zip.ZipException: zip END header not found
	at com.oracle.svm.core.jdk8.zipfile.ZipFile$Source.zerror(ZipFile.java:1317)
	at com.oracle.svm.core.jdk8.zipfile.ZipFile$Source.findEND(ZipFile.java:1218)
	at com.oracle.svm.core.jdk8.zipfile.ZipFile$Source.initCEN(ZipFile.java:1225)
	at com.oracle.svm.core.jdk8.zipfile.ZipFile$Source.<init>(ZipFile.java:1062)
	at com.oracle.svm.core.jdk8.zipfile.ZipFile$Source.get(ZipFile.java:1022)
	at java.util.zip.ZipFile.<init>(ZipFile.java:261)
	at java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at java.util.zip.ZipFile.<init>(ZipFile.java:206)
	at coursier.install.InfoFile$.liftedTree1$1(InfoFile.scala:156)
	... 28 more
```

I was able to work around the issue by removing the existing `cs` file
```
❯ rm "/Users/lgeirsson/Library/Application Support/Coursier/bin/cs"
```

I could be that I placed the `cs` binary there manually, which could have caused this issue but I don't remember exactly.

**Comment by alexarchambault** [comment]
Maybe it could be a file that was created by earlier versions of the `install` command (the way metadata is handled changed a bit before `install` was marked an non-experimental). Deleting it is the best way to circumvent that, yes.

But the exception is unfortunate, in any case… That needs to be fixed. I hadn't thought about the scenario where a file with the same name already exists when we install an app, and that file isn't recognized as an app of ours. We could require some `--force` option to erase it.
