### ISSUE TITLE
cannot `cs launch --jvm 10 scala` on MacOS

### ISSUE THREAD

**Issue by SethTisue** [coursier/coursier#1767]
this is perhaps not so important since JDK 10 is old news, but filing a report anyway, to at least document the problem

it works for 8, 9, 11, 12, 13, and 14. only 10 doesn't work

it fails even if I move my `~/Library/Caches/Coursier` aside first

the error is

```
Extracting
  /Users/tisue/Library/Caches/Coursier/v1/https/github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%252B13/OpenJDK10_x64_Mac_jdk-10.0.2%252B13.tar.gz
in
  /Users/tisue/Library/Caches/Coursier/jvm/adopt@1.10.0-2
Done
Exception in thread "main" java.io.IOException: Cannot run program "/Users/tisue/Library/Caches/Coursier/jvm/adopt@1.10.0-2/Contents/Home/bin/java": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at coursier.cli.launch.Launch$.$anonfun$launchFork$9(Launch.scala:124)
```

**Comment by alexarchambault** [comment]
It seems the openjdk 10 macOS archives don't put their content under `Contents/Home`, like for the other versions… We should just not look under `Contents/Home` if it's not there then. That should be an easy fix.
