### ISSUE TITLE
Unexpected scala version not found error

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#1809]
The following fails to select a scala 2.12 version:
```text
$ cs launch ammonite:2.1.4-12-f697522 --scala 2.12
Exception in thread "main" coursier.install.AppArtifacts$ScalaDependenciesNotFound: Can't find a scala version suffix for com.lihaoyi:::ammonite:2.1.4-12-f697522 (likely a non existing module or version)
	at coursier.install.AppDescriptor.$anonfun$processDependencies$9(AppDescriptor.scala:180)
	at scala.Option.toRight(Option.scala:485)
	at coursier.install.AppDescriptor.processDependencies(AppDescriptor.scala:180)
	at coursier.cli.resolve.Resolve$.$anonfun$depsAndReposOrError$4(Resolve.scala:91)
	at scala.util.Either.flatMap(Either.scala:341)
	at coursier.cli.resolve.Resolve$.$anonfun$depsAndReposOrError$2(Resolve.scala:62)
	at scala.util.Either.flatMap(Either.scala:341)
	at coursier.cli.resolve.Resolve$.depsAndReposOrError(Resolve.scala:62)
	at coursier.cli.resolve.Resolve$.task(Resolve.scala:249)
	at coursier.cli.fetch.Fetch$.task(Fetch.scala:27)
	at coursier.cli.launch.Launch$.task(Launch.scala:432)
	at coursier.cli.launch.Launch$.run(Launch.scala:493)
	at coursier.cli.Coursier$.$anonfun$runA$2(Coursier.scala:128)
	at coursier.cli.Coursier$.$anonfun$runA$2$adapted(Coursier.scala:112)
	at coursier.cli.CommandAppPreA.run(CommandAppPreA.scala:22)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5(CommandAppWithPreCommand.scala:99)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5$adapted(CommandAppWithPreCommand.scala:99)
	at scala.util.Either.fold(Either.scala:191)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3(CommandAppWithPreCommand.scala:99)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3$adapted(CommandAppWithPreCommand.scala:85)
	at scala.Option.foreach(Option.scala:407)
	at caseapp.core.app.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:85)
	at coursier.cli.Coursier$.main(Coursier.scala:77)
	at coursier.cli.Coursier.main(Coursier.scala)
```
while `2.12.12` would have worked:
```text
$ cs launch ammonite:2.1.4-12-f697522 --scala 2.12.12
Loading...
Welcome to the Ammonite Repl 2.1.4-12-f697522 (Scala 2.12.12 Java 1.8.0_121)
@
```

**Comment by alexarchambault** [comment]
In the same vein, the following should have worked, but doesn't:
```text
$ cs resolve mill-interactive:0.9.5
Can't find a scala version suffix for com.lihaoyi::mill-dev:0.9.5 (likely a non existing module or version)
```

While it does with an explicit Scala version:
```text
$ cs resolve mill-interactive:0.9.5 --scala 2.13.3
ch.epfl.scala:bsp4j:2.0.0-M13:default
com.chuusai:shapeless_2.13:2.3.3:default
…
```

(all with coursier `2.0.16`)

**Comment by daniel-awake** [comment]
I saw a similar message when looking up a non-scala package:
```
$ cs resolve com.google.guava::guava:29.0-jre 
Can't find a scala version suffix for com.google.guava::guava:29.0-jre (likely a non existing module or version)
$ cs resolve com.google.guava::guava:29.0-jre  --scala 2.11.12
Resolution error: Error downloading com.google.guava:guava_2.11:29.0-jre
  not found: /home/daniel/.ivy2/local/com.google.guava/guava_2.11/29.0-jre/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/com/google/guava/guava_2.11/29.0-jre/guava_2.11-29.0-jre.pom
$ cs --version
2.0.6
```
I don't know whether this is actually related to the original problem.
