### ISSUE TITLE
Coursier fails to resolve the same dependency concurrently in several projects

### ISSUE THREAD

**Issue by pshirshov** [coursier/coursier#1818]
I have a test suite for my IDL compiler, which launches multiple `sbt` instances in parallel. The projects are nearly identical and have exactly the same set of dependencies.

Seems like Coursier fails to handle such a usecase - I'm always getting weird exceptions like:

```
                [warn] 	Note: Unresolved dependencies path:
                    [error] sbt.librarymanagement.ResolveException: Error downloading com.fasterxml.jackson:jackson-parent:2.9.0
                    [error]   Not found
                    [error]   Not found
                    [error]   not found: /root/.ivy2/local/com.fasterxml.jackson/jackson-parent/2.9.0/ivys/ivy.xml
                    [error]   not found: https://nexus/repository/maven-public/com.fasterxml.jackson/jackson-parent/2.9.0/ivys/ivy.xml
                    [error]   download error: Caught java.nio.file.NoSuchFileException: /root/.cache/coursier/v1/https/nexus/repository/maven-public/com/fasterxml/jackson/jackson-parent/2.9.0/.jackson-parent-2.9.0.pom.part -> /root/.cache/coursier/v1/https/nexus/repository/maven-public/com/fasterxml/jackson/jackson-parent/2.9.0/jackson-parent-2.9.0.pom (/root/.cache/coursier/v1/https/nexus/repository/maven-public/com/fasterxml/jackson/jackson-parent/2.9.0/.jackson-parent-2.9.0.pom.part -> /root/.cache/coursier/v1/https/nexus/repository/maven-public/com/fasterxml/jackson/jackson-parent/2.9.0/jackson-parent-2.9.0.pom) while downloading https://nexus/repository/maven-public/com/fasterxml/jackson/jackson-parent/2.9.0/jackson-parent-2.9.0.pom
                    [error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
                    [error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
                    [error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
                    [error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:218)
                    [error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
                    [error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
                    [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
                    [error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
                    [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
                    [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
                    [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
                    [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
                    [error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
                    [error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
                    [error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
                    [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
                    [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
                    [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
                    [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
                    [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
                    [error] 	at sbt.Execute.work(Execute.scala:290)
                    [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
                    [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
                    [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
                    [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                    [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                    [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                    [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                    [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                    [error] 	at java.base/java.lang.Thread.run(Thread.java:834)
                    [error] (update) sbt.librarymanagement.ResolveException: Error downloading com.fasterxml.jackson:jackson-parent:2.9.0
                    [error]   Not found
                    [error]   Not found
                    [error]   not found: /root/.ivy2/local/com.fasterxml.jackson/jackson-parent/2.9.0/ivys/ivy.xml
                    [error]   not found: https://nexus/repository/maven-public/com.fasterxml.jackson/jackson-parent/2.9.0/ivys/ivy.xml
                    [error]   download error: Caught java.nio.file.NoSuchFileException: /root/.cache/coursier/v1/https/nexus/repository/maven-public/com/fasterxml/jackson/jackson-parent/2.9.0/.jackson-parent-2.9.0.pom.part -> /root/.cache/coursier/v1/https/nexus/repository/maven-public/com/fasterxml/jackson/jackson-parent/2.9.0/jackson-parent-2.9.0.pom (/root/.cache/coursier/v1/https/nexus/repository/maven-public/com/fasterxml/jackson/jackson-parent/2.9.0/.jackson-parent-2.9.0.pom.part -> /root/.cache/coursier/v1/https/nexus/repository/maven-public/com/fasterxml/jackson/jackson-parent/2.9.0/jackson-parent-2.9.0.pom) while downloading https://nexus/repository/maven-public/com/fasterxml/jackson/jackson-parent/2.9.0/jackson-parent-2.9.0.pom
                    Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

Right now I've fixed this by running my first test isolated, but I believe this should be resolved on Coursier level. Most likely a shared read/write lock (which may be implemented with file-level locks) would solve this issue.

**Comment by rlmv** [comment]
👍 @pshirshov this sounds like the same issue as #1815, do you agree?
