### ISSUE TITLE
InvalidPathException exception during cs run on Windows 7

### ISSUE THREAD

**Issue by soronpo** [coursier/coursier#1842]
Just running cs.exe causes an error. (SBT running fine)
Possibly related to https://github.com/dirs-dev/directories-jvm/issues/37 

```
     ________ ___   / /  ___
    / __/ __// _ | / /  / _ |
  __\ \/ /__/ __ |/ /__/ __ |
 /____/\___/_/ |_/____/_/ | |
                          |/

Checking if a JVM is installed
Found a JVM installed under C:\Program Files (x86)\AdoptOpenJDK\jdk-11.0.5.10-hotspot.

Checking if C:\Users\soronpo\AppData\Local\Coursier\data\bin is in PATH

Checking if the standard Scala applications are installed
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 29: c:\Users\soronpo\Downloads\?C:\Users\soronpo\AppData\Roaming\Coursier\config\credentials.properties
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at coursier.credentials.FileCredentials.get(FileCredentials.scala:19)
        at coursier.cache.FileCache.$anonfun$allCredentials0$1(FileCache.scala:49)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:280)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:280)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:277)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
        at coursier.cache.FileCache.allCredentials0$lzycompute(FileCache.scala:49)
        at coursier.cache.FileCache.allCredentials0(FileCache.scala:48)
        at coursier.cache.FileCache.$anonfun$allCredentials$1(FileCache.scala:52)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:136)
```

**Comment by alexarchambault** [comment]
Thanks for the report! That's probably https://github.com/dirs-dev/directories-jvm/issues/37, yes. The fix is included in `2.0.0-RC6-25` and onwards.

**Comment by cheikh-del** [comment]
I have the same eeror.

**Comment by cheikh-del** [comment]
I am trying to use scala with jupyter but when I run the jupyter server I get this same error. As a result, he tells me kernel dead.
