### ISSUE TITLE
cs setup on mac fails to write in .bash_profile with AccessDeniedException

### ISSUE THREAD

**Issue by smarter** [coursier/coursier#1859]
Not sure how common this is but one student reported this on macOS 10.14.6:
```scala
Checking if a JVM is installed
Found a JVM installed under /Users/Lenny/Library/Caches/Coursier/jvm/adopt@1.8.0-252/Contents/Home.
Should we update ~/.profile, ~/.bash_profile? [Y/n] Y
Exception in thread "main" java.nio.file.AccessDeniedException: /Users/Lenny/.bash_profile
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.write(Files.java:3292)
	at coursier.env.ProfileUpdater.$anonfun$addToProfileFiles$5(ProfileUpdater.scala:97)
	at coursier.env.ProfileUpdater.$anonfun$addToProfileFiles$5$adapted(ProfileUpdater.scala:95)
	at scala.Option.foreach(Option.scala:407)
	at coursier.env.ProfileUpdater.$anonfun$addToProfileFiles$1(ProfileUpdater.scala:95)
	at coursier.env.ProfileUpdater.$anonfun$addToProfileFiles$1$adapted(ProfileUpdater.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at coursier.env.ProfileUpdater.addToProfileFiles(ProfileUpdater.scala:91)
	at coursier.env.ProfileUpdater.applyUpdate(ProfileUpdater.scala:168)
	at coursier.env.ProfileUpdater.applyUpdate(ProfileUpdater.scala:165)
	at coursier.cli.setup.MaybeInstallJvm.$anonfun$task$13(MaybeInstallJvm.scala:83)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```
It can be fixed by first running:
```scala
[ -f ~/.bash_profile ] && sudo chmod 0666 ~/.bash_profile
```
I don't know how that happened but it might be worth adding to the instructions if it's a common problem?

**Comment by smarter** [comment]
(weirdly just running `chmod u+w ~/.bash_profile` didn't solve the issue)

**Comment by ritschwumm** [comment]
could it be the owner of the .bash_profile was some other user? that would explain why making it world-writable helped where making it writable fof the owner didn't.

**Comment by alexarchambault** [comment]
Thanks for the report, @smarter!

Not sure how common that is… Maybe the initial `~/.bash_profile` was created from a `sudo` command (on my machine, under macOS, `sudo -s` gives me a shell whose `HOME` is also my standard user home).

Maybe we could print a more sensible message if we detect insufficient permissions.

**Comment by smarter** [comment]
Yes, I think that'd be fine. A more extreme solution would be to ask the user something like: "Insufficient permissions detected in file .bash_profile. Would you like to update the permissions to make this file writable? [Y/n]"
