### ISSUE TITLE
Download error cs-x86_64-pc-win32.exe for v2.0.1

### ISSUE THREAD

**Issue by sshark** [coursier/coursier#1891]
I executed `cs.exe` on Windows 10 and it crashed because of `javax.net.ssl.SSLHandshakeException`. I realized the file [v2.0.1/cs-x86_64-pc-win32.exe](https://github.com/coursier/coursier/releases/download/v2.0.1/cs-x86_64-pc-win32.exe) does not exist. Please advise. Thanks

Checking if the standard Scala applications are installed
  Found ammonite
Exception in thread "main" coursier.cache.ArtifactError$DownloadError: download error: Caught javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure (Received fatal alert: handshake_failure) while downloading https://github.com/coursier/coursier/releases/download/v2.0.1/cs-x86_64-pc-win32.exe
        at coursier.cache.FileCache$.helper$2(FileCache.scala:1019)
        at coursier.cache.FileCache$.coursier$cache$FileCache$$downloading(FileCache.scala:1033)
        at coursier.cache.FileCache.doDownload$1(FileCache.scala:321)
        at coursier.cache.FileCache.$anonfun$download$55(FileCache.scala:508)
        at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:72)
        at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:98)

**Comment by alexarchambault** [comment]
Thanks for the report! I was able to reproduce that on my Windows machine, with cs 2.0.0, by doing
```text
> cs install --install-dir test-install cs
```

The missing `2.0.1` launcher should have been silently ignored (these were not published because of an issue on the CI), and the `2.0.0` launcher should have been pulled instead. This is what happens on Linux and macOS.

Weirdly enough, it seems only to happen with the native launcher, not with the JVM-based one, and only on Windows. So as a workaround, if you already have a JVM installed, you can just use the [JVM-based launcher](https://get-coursier.io/docs/cli-installation.html#windows-1), until `2.0.2` is released.

https://github.com/coursier/coursier/pull/1893 should fix that, and the upcoming `2.0.2` artifacts should also make old launchers not run into that error.

**Comment by alexarchambault** [comment]
It turned out the issue was more complex than that, and wasn't really fixed in `2.0.2`… see https://github.com/coursier/coursier/issues/1894. `2.0.3` should (really) fix that.
