### ISSUE TITLE
https errors when downloading things from github with the windows launcher

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#1894]
These seem to happen since the switch to GraalVM 20 / JDK 11 (`2.0.0-RC6-27` and after):
```text
> cs get --cache tmp-cache https://github.com/coursier/coursier/releases/download/v2.0.2/coursier
Downloading https://github.com/coursier/coursier/releases/download/v2.0.2/coursier
Downloaded https://github.com/coursier/coursier/releases/download/v2.0.2/coursier
download error: Caught javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure (Received fatal alert: handshake_failure) while downloading https://github.com/coursier/coursier/releases/download/v2.0.2/coursier
```

That also makes `cs setup` or `cs java` fail, when they try to download the jabba index from GitHub, or native launchers (`cs`, `bloop`, `sbtn`) from there.

**Comment by alexarchambault** [comment]
More detailed exception:
```text
> cs-2.0.2 get --cache tmp-cache https://github.com/coursier/coursier/releases/download/v2.0.2/coursier -v -v
Downloading https://github.com/coursier/coursier/releases/download/v2.0.2/coursier
Downloaded https://github.com/coursier/coursier/releases/download/v2.0.2/coursier
Exception in thread "main" coursier.cache.ArtifactError$DownloadError: download error: Caught javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure (Received fatal alert: handshake_failure) while downloading https://github.com/coursier/coursier/releases/download/v2.0.2/coursier
        at coursier.cache.FileCache$.helper$2(FileCache.scala:1017)
        at coursier.cache.FileCache$.coursier$cache$FileCache$$downloading(FileCache.scala:1031)
        at coursier.cache.FileCache.doDownload$1(FileCache.scala:321)
        at coursier.cache.FileCache.$anonfun$download$55(FileCache.scala:506)
        at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:72)
        at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:98)
        at coursier.cache.FileCache.$anonfun$download$33(FileCache.scala:507)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138) 
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:313)
        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:186)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1144)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1055)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:395)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
        at coursier.cache.CacheUrl$.redirectTo(CacheUrl.scala:153)
        at coursier.cache.CacheUrl$.redirect(CacheUrl.scala:163)
        at coursier.cache.CacheUrl$.urlConnectionMaybePartial(CacheUrl.scala:310)
        at coursier.cache.ConnectionBuilder.connectionMaybePartial(ConnectionBuilder.scala:45)
        at coursier.cache.FileCache.$anonfun$download$34(FileCache.scala:348)
        at coursier.cache.FileCache$.$anonfun$downloading$1(FileCache.scala:997)
        at coursier.cache.CacheLocks$.withUrlLock(CacheLocks.scala:116)
        at coursier.cache.FileCache$.helper$2(FileCache.scala:997)
        ... 18 more
```
