### ISSUE TITLE
cs can't update itself on Windows

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#1896]
```text
> cs update cs
https://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.12/maven-metadata.xml
  No new update since 2020-10-09 20:45:37
Exception in thread "main" java.nio.file.AccessDeniedException: test-install\.cs.aux.exe
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274)
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)        
        at java.nio.file.Files.deleteIfExists(Files.java:1180)
        at coursier.install.Updatable$.get$1(Updatable.scala:82)
        at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:96)
        at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:72)
        at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:98)
        at coursier.install.Updatable$.writing(Updatable.scala:96)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:340)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:84)
        at coursier.install.InstallDir.$anonfun$maybeUpdate$13(InstallDir.scala:382)
        at coursier.util.Task$.wrap(Task.scala:84)
        at coursier.util.Task$.$anonfun$delay$2(Task.scala:49)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138) 
```

**Comment by alexarchambault** [comment]
It seems the metadata (that live in the `cs` file itself, as a ZIP archive) are updated anyway, which makes subsequent attempts assume the launcher is already up-to-date :|

**Comment by alexarchambault** [comment]
As a workaround, if you didn't already run `cs update cs`, update it with `coursier` (JVM-based coursier launcher) instead:
```text
> coursier update cs
```

If you already ran `cs update cs`, remove `cs` and `.cs.aux.exe` from the installation directory (find it with `where cs`), and install `cs` again with `coursier`:
```text
> coursier install cs
```
