### ISSUE TITLE
Possibly misleading java.net.MalformedURLException for the URL protocol zip+https

### ISSUE THREAD

**Issue by callado4** [coursier/coursier#1908]
I'm getting the following exception when trying to install `sbtn`:
```
$ cs install sbtn
Exception in thread "main" coursier.cache.ArtifactError$DownloadError: download error: Caught java.net.MalformedURLException: Accessing an URL protocol that was not enabled. The URL protocol zip+https is not tested and might not work as expected. It can be enabled by adding the -H:EnableURLProtocols=zip+https option to the native-image command. (Accessing an URL protocol that was not enabled. The URL protocol zip+https is not tested and might not work as expected. It can be enabled by adding the -H:EnableURLProtocols=zip+https option to the native-image command.) while downloading zip+https://github.com/sbt/sbt/releases/download/v1.4.1/sbt-1.4.1.zip!sbt/bin/sbtn-x86_64-apple-darwin
	at coursier.cache.FileCache$.helper$2(FileCache.scala:1018)
	at coursier.cache.FileCache$.coursier$cache$FileCache$$downloading(FileCache.scala:1032)
	at coursier.cache.FileCache.doDownload$1(FileCache.scala:320)
	at coursier.cache.FileCache.$anonfun$download$54(FileCache.scala:507)
	at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:58)
	at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:84)
	at coursier.cache.FileCache.$anonfun$download$32(FileCache.scala:508)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.net.MalformedURLException: Accessing an URL protocol that was not enabled. The URL protocol zip+https is not tested and might not work as expected. It can be enabled by adding the -H:EnableURLProtocols=zip+https option to the native-image command.
	at com.oracle.svm.core.jdk.JavaNetSubstitutions.unsupported(JavaNetSubstitutions.java:208)
	at com.oracle.svm.core.jdk.JavaNetSubstitutions.getURLStreamHandler(JavaNetSubstitutions.java:169)
	at java.net.URL.getURLStreamHandler(URL.java:70)
	at java.net.URL.<init>(URL.java:616)
	at coursier.cache.CacheUrl$.url(CacheUrl.scala:90)
	at coursier.cache.CacheUrl$.urlConnectionMaybePartial(CacheUrl.scala:289)
	at coursier.cache.CacheUrl$.urlConnectionMaybePartial(CacheUrl.scala:277)
	at coursier.cache.FileCache.$anonfun$download$33(FileCache.scala:349)
	at coursier.cache.FileCache$.$anonfun$downloading$1(FileCache.scala:998)
	at coursier.cache.CacheLocks$.withUrlLock(CacheLocks.scala:102)
	at coursier.cache.FileCache$.helper$2(FileCache.scala:998)
	... 18 more
```

I _think_ what is actually happening is that the metadata for the `sbtn` artifact is either stored incorrectly or there is a problem with how coursier is parsing the response.  If you need any more information to reproduce or to find the cause please let me know (I can't look into it at the moment).

**Comment by callado4** [comment]
Since I installed coursier using Homebrew, I upgrading it using Homebrew too with
```
brew upgrade coursier/formulas/coursier
```
Now with the current version of `cs` I was able to install `sbtn`:
```
> cs --version
2.0.5
> cs install sbtn
https://repo1.maven.org/maven2/org/scala-sbt/sbt/maven-metadata.xml
  No new update since 2020-10-19 16:21:40
Wrote sbtn
> sbtn about
[info] entering *experimental* thin client - BEEP WHIRR
[info] server was not detected. starting an instance
[info] welcome to sbt 1.4.1 (AdoptOpenJDK Java 11.0.7)
...
```

**Comment by alexarchambault** [comment]
Indeed, the latest sbtn descriptor needs coursier `2.0.5`. Maybe it's time for coursier to version the app descriptor format…
