### ISSUE TITLE
Running project with sbt 1.4.2 on Windows 10 - Couldn't find pwsh.exe

### ISSUE THREAD

**Issue by kalejami** [coursier/coursier#1913]
Hi,

Getting this error, when running a sbt project on Windows 10 with sbt version 1.4.2:

```
java.lang.RuntimeException: Couldn't find pwsh.exe or powershell.exe on path or in default system locations
        at lmcoursier.internal.shaded.coursier.cache.shaded.dirs.dev.dirs.Util.windowsFallback(Util.java:265)
        at lmcoursier.internal.shaded.coursier.cache.shaded.dirs.dev.dirs.Util.getWinDirs(Util.java:163)
        at lmcoursier.internal.shaded.coursier.cache.shaded.dirs.dev.dirs.ProjectDirectories.fromPath(ProjectDirectories.java:254)
        at lmcoursier.internal.shaded.coursier.cache.shaded.dirs.dev.dirs.ProjectDirectories.from(ProjectDirectories.java:308)
        at lmcoursier.internal.shaded.coursier.paths.CoursierPaths.coursierDirectories(CoursierPaths.java:90)
        at lmcoursier.internal.shaded.coursier.paths.CoursierPaths.computeCacheDirectory(CoursierPaths.java:53)
        at lmcoursier.internal.shaded.coursier.paths.CoursierPaths.computeCacheDirectory(CoursierPaths.java:37)
        at lmcoursier.internal.shaded.coursier.paths.CoursierPaths.cacheDirectory(CoursierPaths.java:66)
        at lmcoursier.internal.shaded.coursier.paths.CachePath.defaultCacheDirectory(CachePath.java:97)
        at lmcoursier.internal.shaded.coursier.cache.CacheDefaults$.location$lzycompute(CacheDefaults.scala:16)
        at lmcoursier.internal.shaded.coursier.cache.CacheDefaults$.location(CacheDefaults.scala:16)
        at lmcoursier.CoursierDependencyResolution$.defaultCacheLocation(CoursierDependencyResolution.scala:275)
        at sbt.coursierint.LMCoursier$.defaultCacheLocation(LMCoursier.scala:44)
        at sbt.Defaults$.$anonfun$buildLevelIvySettings$1(Defaults.scala:508)
        at scala.Function1.$anonfun$compose$1(Function1.scala:49)
        at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
        at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
        at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
        at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
        at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: no output from process
        at lmcoursier.internal.shaded.coursier.cache.shaded.dirs.dev.dirs.Util.runCommands(Util.java:201)
        at lmcoursier.internal.shaded.coursier.cache.shaded.dirs.dev.dirs.Util.runWinCommands(Util.java:226)
        at lmcoursier.internal.shaded.coursier.cache.shaded.dirs.dev.dirs.Util.windowsFallback(Util.java:263)
        ... 22 more
```

Powershell is in PATH and it also works with versions of sbt <= 1.3.13

Someone else getting this errors?

**Comment by kalejami** [comment]
It seems that sbt 1.3.13 uses the following coursier-shaded version
 
```
val lmCoursierVersion = "2.0.0-RC6-4"
val lmCoursierShaded = "io.get-coursier" %% "lm-coursier-shaded" % lmCoursierVersion
```

In sbt 1.4.2 it uses

`val lmCoursierShaded = "io.get-coursier" %% "lm-coursier-shaded" % "2.0.0"`

**Comment by kalejami** [comment]
It seems to be a permission problem. Running powershell as admin and executing the sbt builld works like a charm. 

Running powershell als normal user and it fails:

This commit seems to be responsible for this behaviour:

https://github.com/dirs-dev/directories-jvm/commit/74a100907f4e40fee5368425b0c232f4da494f2e

**Comment by kalejami** [comment]
Ok, 

`if (line == null) throw new IOException("no output from process");`

https://github.com/dirs-dev/directories-jvm/commit/74a100907f4e40fee5368425b0c232f4da494f2e#diff-e1beb805598d360f4a22dfef3fa4d511d45711c8f744d93148e0e44d03ff869bR201

is responsible for the error we see.

It doesn't work if the powershell instance is with `ConstraintLanguage` Language Mode.

Language Mode can be checked with in powershell

`$ExecutionContext.SessionState.LanguageMode`
