### ISSUE TITLE
SSLHandshakeException when running setup

### ISSUE THREAD

**Issue by sloshy** [coursier/coursier#1977]
When running `./cs setup` behind my work proxy, which uses some self-signed certs, I consistently receive an SSL handshake exception each time I try to run. It appears this happens when it is trying to resolve the URLs from Jabba. I downloaded the index and passed it in as an argument to see if I could work around it, as maybe it just did not like github, but I am getting the same error with all other indexes as well:

```
➜  ~ ./cs -J-Dhttp.proxySet=true -J-Dhttp.proxyHost=<my-proxy> -J-Dhttp.proxyPort=<my-proxy> -J-Dhttp.nonProxyHosts='<my-proxy>' -J-Dhttps.proxySet=true -J-Dhttps.proxyHost=<my-proxy> -J-Dhttps.proxyPort=<my-proxy> -J-Dhttps.nonProxyHosts='<my-proxy>' setup --jvm-index file:///Users/me/jabba-index.json
Checking if a JVM is installed
Found a JVM installed under /Users/me/.sdkman/candidates/java/current.

Checking if ~/Library/Application Support/Coursier/bin is in PATH

Checking if the standard Scala applications are installed
  Found ammonite
Exception in thread "main" coursier.cache.ArtifactError$DownloadError: download error: Caught javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.4/graalvm-ce-java8-darwin-amd64-19.3.4.tar.gz
	at coursier.cache.FileCache$.helper$2(FileCache.scala:1008)
	at coursier.cache.FileCache$.coursier$cache$FileCache$$downloading(FileCache.scala:1022)
	at coursier.cache.FileCache.doDownload$1(FileCache.scala:321)
	at coursier.cache.FileCache.$anonfun$download$55(FileCache.scala:506)
	at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:72)
	at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:98)
	at coursier.cache.FileCache.$anonfun$download$33(FileCache.scala:507)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:645)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:464)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1144)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1055)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:395)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at coursier.cache.CacheUrl$.redirectTo(CacheUrl.scala:154)
	at coursier.cache.CacheUrl$.redirect(CacheUrl.scala:164)
	at coursier.cache.CacheUrl$.urlConnectionMaybePartial(CacheUrl.scala:311)
	at coursier.cache.ConnectionBuilder.connectionMaybePartial(ConnectionBuilder.scala:45)
	at coursier.cache.FileCache.$anonfun$download$34(FileCache.scala:348)
	at coursier.cache.FileCache$.$anonfun$downloading$1(FileCache.scala:988)
	at coursier.cache.CacheLocks$.withUrlLock(CacheLocks.scala:116)
	at coursier.cache.FileCache$.helper$2(FileCache.scala:988)
	... 18 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at sun.security.validator.Validator.validate(Validator.java:264)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:629)
	... 42 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
```

If I set the index to an empty JSON it returns:
```
JVM graalvm:19.3 not found in index: No JVM found for OS darwin
```
And will not let me complete setup.

**Comment by hamero** [comment]
Had similar issue (cs uses its own embedded jre and doesn't use user's JVM certs/truststore), and worked around with running 
`java -noverify -jar ~/bin/coursier setup ...` instead

**Comment by jneira** [comment]
Same here, i had to follow @hamero's workaround, but ideally the cs executable shoud allow use an external jvm, via config file next to executable or similar, or configure the internal one

**Comment by lr-josephcho** [comment]
This worked for me too. If you are trying to run `coursier` installed from Homebrew, try running `java -noverify -jar /opt/homebrew/bin/coursier setup` or something similar

**Comment by laughedelic** [comment]
This seems to be a workaround only for the Jar-based launcher. Is there any solution for the native launcher?

**Comment by jiramares** [comment]
Is there any directory where is the coursier jvm installed where I can import our self signed certificate?
