### ISSUE TITLE
cs setup --jvm 8,9,11,13 doesn't works 

### ISSUE THREAD

**Issue by rachlenko** [coursier/coursier#1989]
Hi, I've tried to test it on the windows 10 platform.  It crashed with the following error :
cs setup --jvm 13
Checking if a JVM is installed
Exception in thread "main" java.lang.Exception: Error while getting https://github.com/shyiko/jabba/raw/master/index.json: download error: Caught javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://github.com/shyiko/jabba/raw/master/index.json
        at coursier.jvm.JvmIndex$.$anonfun$load$5(JvmIndex.scala:141)
        at coursier.jvm.JvmIndex$.$anonfun$load$5$adapted(JvmIndex.scala:139)
        at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
        at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
        at coursier.util.Task$.wrap(Task.scala:84)
        at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)

**Comment by hamero** [comment]
see https://github.com/coursier/coursier/issues/1977#issuecomment-841636550

**Comment by rachlenko** [comment]
thanks
