### ISSUE TITLE
Coursier cannot resolve the latest version of the netty-transport-native-epoll library for Mac and Linux

### ISSUE THREAD

**Issue by nerush** [coursier/coursier#2016]
Environment:
OS: Mac/Linux
SBT version 1.4.9
Scala version: 2.13.4

Steps to reproduce:
1. add the following dependency to `build.sbt`:
```
"io.netty" % "netty-transport-native-epoll" % "4.1.60.Final"
```

2. compile the project with sbt to get the following exception:
```
[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.60.Final/netty-transport-native-epoll-4.1.60.Final-linux-aarch64.jar: not found: https://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.60.Final/netty-transport-native-epoll-4.1.60.Final-linux-aarch64.jar
[error] 
[error] 	at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$9(Artifacts.scala:346)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.wrap(Task.scala:84)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: lmcoursier.internal.shaded.coursier.cache.ArtifactError$NotFound: not found: https://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.60.Final/netty-transport-native-epoll-4.1.60.Final-linux-aarch64.jar
[error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$12(FileCache.scala:244)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (update) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.60.Final/netty-transport-native-epoll-4.1.60.Final-linux-aarch64.jar: not found: https://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.60.Final/netty-transport-native-epoll-4.1.60.Final-linux-aarch64.jar
```

Cause: coursier tries to download the artifact with `linux-aarch64` prefix, while actual prefix is `linux-aarch_64`

**Comment by eed3si9n** [comment]
Not sure if this is related, but there's an issue that says `aarch_64` is incorrect - https://github.com/netty/netty-tcnative/issues/571

**Comment by eed3si9n** [comment]
https://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.60.Final/netty-transport-native-epoll-4.1.60.Final.pom says:

```xml
<classifier>${jni.classifier}</classifier>
```

and 

```xml
<profile>
<id>linux-aarch64</id>
<properties>
<!--  use aarch_64 as this is also what os.detected.arch will use on an aarch64 system  -->
<jni.classifier>${os.detected.name}-aarch_64</jni.classifier>
</properties>
```

so I'm guessing that OP is correct.

**Comment by nerush** [comment]
I wonder why this library is resolved with Ivy but is not with Coursier, given that both of them read the same POM ...

**Comment by eed3si9n** [comment]
Any dependency resolver that is not Maven is emulating Maven (or Aether) to parse POM files, so there are lots of corner cases like this that needs to be ironed out.

**Comment by artemkorsakov** [comment]
Is there any solution other than disabling Coursier?

**Comment by eed3si9n** [comment]
I have not tried but I'm guessing the workaround would be to exclude this library from the resolution and add back URL dependencies to the transitive JARs it would have brought in.

**Comment by Falmarri** [comment]
Hit this as well. 2 and a half years open, huh
