### ISSUE TITLE
Transient OverlappingFileLockException issues in CI

### ISSUE THREAD

**Issue by dimisjim** [coursier/coursier#2018]
It is happening on freshly ran CI machines which shouldn't be running any other conflicting coursier process at all that could explain this.

```
Error:  coursier.lmcoursier.ResolutionException: 1 download error
Error:      Caught java.nio.channels.OverlappingFileLockException while downloading https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.7.0/commons-pool2-2.7.0.jar
Error:  (service / update) coursier.lmcoursier.ResolutionException: 1 download error
Error:      Caught java.nio.channels.OverlappingFileLockException while downloading https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.7.0/commons-pool2-2.7.0.jar
Error:  Total time: 19 s, completed Mar 26, 2021 1:54:11 PM
Error: Process completed with exit code 1.
```

Related to https://github.com/coursier/coursier/issues/1276

## EDIT 31/3

Encountered this again for another project:
```
Error:  java.nio.channels.OverlappingFileLockException
Error:  	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
Error:  	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
Error:  	at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1062)
Error:  	at java.nio.channels.FileChannel.lock(FileChannel.java:1053)
Error:  	at lmcoursier.internal.shaded.coursier.paths.CachePath.withStructureLock(CachePath.java:132)
Error:  	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withStructureLock(CacheLocks.scala:21)
Error:  	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:38)
Error:  	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$32(FileCache.scala:553)
Error:  	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
Error:  	at scala.util.Success.$anonfun$map$1(Try.scala:255)
Error:  	at scala.util.Success.map(Try.scala:213)
Error:  	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
Error:  	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
Error:  	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
Error:  	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
Error:  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Error:  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Error:  	at java.lang.Thread.run(Thread.java:748)
Error:  (common / Compile / compileIncremental) java.nio.channels.OverlappingFileLockException
```

Both of them use `scalaVersion := "2.12.12"`
Could this be related?

**Comment by rlmv** [comment]
Do you use any SBT plugins that pull in Coursier as a separate dependency? Older versions of Coursier don't play nice with new versions in the same project. I have fixed this error in the past by upgrading plugins to the latest version. In particular `sbt-scalafmt` needs to be >= 2.20 (see https://github.com/scalameta/sbt-scalafmt/releases/tag/v2.2.0 which no longer pulls down Coursier as a separate dependency).

See https://github.com/coursier/coursier/issues/1276 for another discussion of this bug.

**Comment by dimisjim** [comment]
Yes, after upgrading to latest sbt version, we stopped seeing this transient issue.
