### ISSUE TITLE
Linux installation process broken on Ubuntu

### ISSUE THREAD

**Issue by jinfiesto** [coursier/coursier#2108]
I've tried installing Coursier on two Ubuntu installs today with the same result. Using the [official instructions](https://get-coursier.io/docs/cli-installation.html#latest-launchers):

```
curl -fLo cs https://git.io/coursier-cli-linux
chmod +x cs
./cs setup
```

This errors out with the error: "No main class found." Running in verbose:

```
Found 3 main classes:
  ((,),org.codehaus.plexus.classworlds.launcher.Launcher)
  ((org.apache,Apache Commons Compress),org.apache.commons.compress.archivers.Lister)
  ((org.fusesource.jansi,jansi),org.fusesource.jansi.AnsiMain)
Exception in thread "main" coursier.install.InstallDir$NoMainClassFound: No main class found
	at coursier.install.InstallDir.$anonfun$createOrUpdate$13(InstallDir.scala:295)
	at scala.Option.getOrElse(Option.scala:189)
	at coursier.install.InstallDir.mainClass$lzycompute$1(InstallDir.scala:295)
	at coursier.install.InstallDir.mainClass$1(InstallDir.scala:281)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$14(InstallDir.scala:325)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$14$adapted(InstallDir.scala:299)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$21(InstallDir.scala:385)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$21$adapted(InstallDir.scala:384)
	at coursier.install.Updatable$.get$1(Updatable.scala:55)
	at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:96)
	at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:72)
	at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:98)
	at coursier.install.Updatable$.writing(Updatable.scala:96)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:384)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:87)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:62)
	at coursier.cli.setup.MaybeInstallApps.$anonfun$task$3(MaybeInstallApps.scala:22)
	at coursier.util.Task$.wrap(Task.scala:84)
	at coursier.util.Task$.$anonfun$delay$2(Task.scala:49)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

We've been using Coursier as part of our CI and this installation process was working until earlier today. Has anything changed that would cause this issue?

**Comment by alexarchambault** [comment]
Thanks for reporting this!

This should be fixed as soon as a release of [coursier-apps](https://github.com/coursier/apps) including https://github.com/coursier/apps/pull/103 or a release of coursier including https://github.com/coursier/coursier/pull/2107 is sync-ed to Maven Central. Both are underway.

**Comment by jinfiesto** [comment]
This appears to be fixed. Thanks so much @alexarchambault.

**Comment by jorhett** [comment]
Seems to still be a problem on 20.04 today:

```
$ cs setup --yes
Checking if a JVM is installed
Found a JVM installed under /usr/lib/jvm/java-11-openjdk-arm64.

Checking if ~/.local/share/coursier/bin is in PATH

Checking if the standard Scala applications are installed
  Found ammonite
  Found cs
  Found coursier
  Found scala
  Found scalac
  Found sbt
No main class found
```
