### ISSUE TITLE
coursier.jar fails to run on Windows Arm64

### ISSUE THREAD

**Issue by harrisonmetz** [coursier/coursier#2175]
Hello, I was trying to run the coursier jar (eventually to install scala3) however I can't seem to invoke it without an issue. This is on a Surface Pro X (Windows 10 Arm64). I'm a bit confused because I thought the entire idea of the JVM was "write once, run anywhere," but it appears to be loading some DLL from org.fusesource.hawtjni, whatever that is.

```
java -jar .\Downloads\coursier.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [java.lang.LinkageError: Unable to load library jansi, java.lang.LinkageError: Unable to load library from C:\Users\harri\AppData\Local\Temp\jansi-93fa3188adb8407f81dad04d08abc8192e4e380d.dll, java.lang.LinkageError: Unable to load library from C:\Users\harri\.hawtjni\jansi\jansi-93fa3188adb8407f81dad04d08abc8192e4e380d.dll]
        at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:233)
        at org.fusesource.hawtjni.runtime.Library.load(Library.java:185)
        at org.fusesource.jansi.internal.Kernel32.<clinit>(Kernel32.java:37)
        at io.github.alexarchambault.windowsansi.WindowsAnsi.setup(WindowsAnsi.java:31)
        at coursier.cli.Coursier$.<init>(Coursier.scala:36)
        at coursier.cli.Coursier$.<clinit>(Coursier.scala)
        at coursier.cli.Coursier.main(Coursier.scala)
        Suppressed: java.lang.LinkageError: Unable to load library jansi
                at org.fusesource.hawtjni.runtime.Library.loadLibrary(Library.java:539)
                at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:217)
                ... 6 more
        Caused by: java.lang.UnsatisfiedLinkError: no jansi in java.library.path: C:\Program Files (Arm)\Microsoft\jdk-16.0.2.7-hotspot\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\WindowsApps\Microsoft.PowerShell_7.1.4.0_arm64__8wekyb3d8bbwe;C:\Program Files (Arm)\Microsoft\jdk-16.0.2.7-hotspot\bin;C:\Program Files (Arm)\Microsoft\jdk-16.0.1.9-hotspot\bin;C:\ProgramData\Miniconda3;C:\ProgramData\Miniconda3\Library\mingw-w64\bin;C:\ProgramData\Miniconda3\Library\usr\bin;C:\ProgramData\Miniconda3\Library\bin;C:\ProgramData\Miniconda3\Scripts;C:\Program Files\dotnet\;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\dotnet\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\jdk16\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\Hostx86\x86;C:\Program Files (x86)\Git\cmd;C:\Program Files\Go\bin;C:\Users\harri\.cargo\bin;C:\Users\harri\AppData\Local\Microsoft\WindowsApps;C:\Users\harri\go\bin;C:\Users\harri\.dotnet\tools;C:\Users\harri\AppData\Local\Microsoft\WindowsApps;C:\Users\harri\.dotnet\tools;C:\Users\harri\go\bin;.
                at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2423)
                at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:808)
                at java.base/java.lang.System.loadLibrary(System.java:1893)
                at org.fusesource.hawtjni.runtime.Library.loadLibrary(Library.java:535)
                ... 7 more
        Suppressed: java.lang.LinkageError: Unable to load library from C:\Users\harri\AppData\Local\Temp\jansi-93fa3188adb8407f81dad04d08abc8192e4e380d.dll
                at org.fusesource.hawtjni.runtime.Library.load(Library.java:526)
                at org.fusesource.hawtjni.runtime.Library.extractAndLoad(Library.java:330)
                at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:227)
                ... 6 more
        Caused by: java.lang.UnsatisfiedLinkError: C:\Users\harri\AppData\Local\Temp\jansi-93fa3188adb8407f81dad04d08abc8192e4e380d.dll: Can't load AMD 64-bit .dll on a ARM 64-bit platform
                at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
                at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
                at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
                at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
                at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
                at java.base/java.lang.Runtime.load0(Runtime.java:746)
                at java.base/java.lang.System.load(System.java:1857)
                at org.fusesource.hawtjni.runtime.Library.load(Library.java:522)
                ... 8 more
        Suppressed: java.lang.LinkageError: Unable to load library from C:\Users\harri\.hawtjni\jansi\jansi-93fa3188adb8407f81dad04d08abc8192e4e380d.dll
                at org.fusesource.hawtjni.runtime.Library.load(Library.java:526)
                at org.fusesource.hawtjni.runtime.Library.extractAndLoad(Library.java:330)
                at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:227)
                ... 6 more
        Caused by: java.lang.UnsatisfiedLinkError: C:\Users\harri\.hawtjni\jansi\jansi-93fa3188adb8407f81dad04d08abc8192e4e380d.dll: Can't load AMD 64-bit .dll on a ARM 64-bit platform
                at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
                at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
                at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
                at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
                at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
                at java.base/java.lang.Runtime.load0(Runtime.java:746)
                at java.base/java.lang.System.load(System.java:1857)
                at org.fusesource.hawtjni.runtime.Library.load(Library.java:522)
                ... 8 more
```

**Comment by Friendseeker** [comment]
Coursier probably has an outdated Jansi that does not support arm64. sbt got bitten by same issue.
