### ISSUE TITLE
Pre-release tags should not be published for Homebrew

### ISSUE THREAD

**Issue by ches** [coursier/coursier#2225]
It looks CI automation results in the Homebrew formula being updated for pre-release versions:

```
$ brew info coursier | head -1
coursier/formulas/coursier: stable 2.0.16-169-g194ebc55c
```

This is probably undesirable, since e.g. users may run into CLI interface breaking, without release notes letting us know 😇 

```sh
# Shell history recall that worked a week ago...
$ cs complete --scala-version 2.13 org.scalatest::scalatest:
Exception in thread "main" java.lang.NumberFormatException: For input string: "2.13"
        at java.lang.Integer.parseInt(Integer.java:652)
        at java.lang.Integer.parseInt(Integer.java:770)
        at scala.collection.immutable.StringLike.toInt(StringLike.scala:304)
        at scala.collection.immutable.StringLike.toInt$(StringLike.scala:304)
        at scala.collection.immutable.StringOps.toInt(StringOps.scala:33)
        at caseapp.core.app.CommandsEntryPoint.completeMain(CommandsEntryPoint.scala:70)
        at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:95)
        at coursier.cli.Coursier$.main(Coursier.scala:111)
        at coursier.cli.Coursier.main(Coursier.scala)

$ cs complete org.scalatest::scalatest:
Usage: cs List(complete) format index ...args...
```

(By the way the latter seems like less-than-ideal case-app behavior… And I did find that the command is `complete-dep` now ☺️ )

AFAIK Homebrew's worldview of a stability model consists of "stable" and "head". Since the Coursier formula doesn't really do build from source anyway, you could maybe use [the `head` block in the DSL][1] to scope values for pre-releases so the latest one would install with `brew install --head`, if you want to be a bit fancy to support that. Or alternatively, simply adjust CI automation so the formula doesn't update for pre-releases.

I can try making a stab at either change, if you have a preferred direction.

[1]: https://docs.brew.sh/Formula-Cookbook#patches

**Comment by tnielens** [comment]
+1 on this one. I'm new to coursier and tried for a while to run the `complete` command from the doc before searching through the issue tracker

**Comment by Maatary** [comment]
oh gosh yes. I fixed my issue by reverting to the previous version following https://cmichel.io/how-to-install-an-old-package-version-with-brew/ 
really painful experience
