### ISSUE TITLE
Runtime crash in dependency parsing

### ISSUE THREAD

**Issue by varungandhi-src** [coursier/coursier#2281]
Coursier version: 2.0.16.
Platform: macOS 12 on M1.

I'm sure I messed something up in this invocation (~first time using coursier), but it looks like I should get a parse error instead of a crash.

```
coursier fetch -q -q --intransitive junit --classifier sources
Exception in thread "main" scala.MatchError: [Ljava.lang.String;@112245f88 (of class [Ljava.lang.String;)
        at coursier.parse.DependencyParser$.javaOrScalaDependencyParams(DependencyParser.scala:172)
        at coursier.parse.DependencyParser$.$anonfun$javaOrScalaDependenciesParams$1(DependencyParser.scala:376)
        at coursier.util.Traverse$TraverseOps.$anonfun$validationNelTraverse$1(Traverse.scala:32)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
        at scala.collection.immutable.List.foldLeft(List.scala:91)
        at coursier.util.Traverse$TraverseOps.validationNelTraverse(Traverse.scala:25)
        at coursier.parse.DependencyParser$.javaOrScalaDependenciesParams(DependencyParser.scala:375)
        at coursier.parse.DependencyParser$.javaOrScalaDependenciesParams(DependencyParser.scala:369)
        at coursier.cli.params.DependencyParams$.$anonfun$apply$12(DependencyParams.scala:105)
        at scala.util.Either.flatMap(Either.scala:341)
        at coursier.cli.params.DependencyParams$.apply(DependencyParams.scala:104)
        at coursier.cli.resolve.SharedResolveParams$.apply(SharedResolveParams.scala:36)
        at coursier.cli.fetch.FetchParams$.apply(FetchParams.scala:28)
        at coursier.cli.fetch.Fetch$.run(Fetch.scala:83)
        at coursier.cli.Coursier$.$anonfun$runA$2(Coursier.scala:148)
        at coursier.cli.Coursier$.$anonfun$runA$2$adapted(Coursier.scala:140)
        at coursier.cli.CommandAppPreA.run(CommandAppPreA.scala:22)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5(CommandAppWithPreCommand.scala:99)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5$adapted(CommandAppWithPreCommand.scala:99)
        at scala.util.Either.fold(Either.scala:191)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3(CommandAppWithPreCommand.scala:99)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3$adapted(CommandAppWithPreCommand.scala:85)
        at scala.Option.foreach(Option.scala:407)
        at caseapp.core.app.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:85)
        at coursier.cli.Coursier$.main(Coursier.scala:105)
        at coursier.cli.Coursier.main(Coursier.scala)
```

**Comment by PawelLipski** [comment]
+1, getting the same (coursier version 2.1.9):

```
$ coursier fetch --intransitive --quiet org.apache.parquet:parquet-hadoop-bundle:1.10.1
Exception in thread "main" scala.MatchError: [Ljava.lang.String;@7ac0e420 (of class [Ljava.lang.String;)
	at coursier.parse.DependencyParser$.javaOrScalaDependencyParams(DependencyParser.scala:176)
	at coursier.parse.DependencyParser$.$anonfun$javaOrScalaDependenciesParams$1(DependencyParser.scala:381)
	at coursier.util.Traverse$TraverseOps.$anonfun$validationNelTraverse$1(Traverse.scala:32)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at coursier.util.Traverse$TraverseOps.validationNelTraverse(Traverse.scala:25)
	at coursier.parse.DependencyParser$.javaOrScalaDependenciesParams(DependencyParser.scala:380)
	at coursier.parse.DependencyParser$.javaOrScalaDependenciesParams(DependencyParser.scala:374)
	at coursier.cli.params.DependencyParams$.$anonfun$apply$15(DependencyParams.scala:138)
	at scala.util.Either.flatMap(Either.scala:341)
	at coursier.cli.params.DependencyParams$.apply(DependencyParams.scala:137)
	at coursier.cli.resolve.SharedResolveParams$.apply(SharedResolveParams.scala:38)
	at coursier.cli.fetch.FetchParams$.apply(FetchParams.scala:30)
	at coursier.cli.fetch.Fetch$.run(Fetch.scala:92)
	at coursier.cli.fetch.Fetch$.run(Fetch.scala:18)
	at caseapp.core.app.CaseApp.main(CaseApp.scala:157)
	at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:161)
	at coursier.cli.Coursier$.main(Coursier.scala:118)
	at coursier.cli.Coursier.main(Coursier.scala)
```

Seems that `fetch --quiet --intransitive` crashes for certain libs (not all, I've used in scripts for some time without issues)

**Comment by keynmol** [comment]
This seems to be an argument parsing bug - it's trying to parse `--quiet` as a dependency spec. 

This works:

```
fetch --quiet --intransitive org.apache.parquet:parquet-hadoop-bundle:1.10.1
```

So it needs both a fix in case-app, and a more meaningful log message in dependency parser.
