### ISSUE TITLE
Unrecognized launcher type: prebuilt

### ISSUE THREAD

**Issue by agilesteel** [coursier/coursier#2350]
I started to get this error today when trying to update some packages. Examples of packages: `cs` itself, `sbt`, `sbtn`.
![cs](https://user-images.githubusercontent.com/1141462/152021141-2ca10cd4-80ba-48dd-ba6b-7c93d8d0e9fc.png)
```scala
❯ cs update cs
Exception in thread "main" coursier.install.InfoFile$ErrorProcessingAppDescription: Error processing app description /home/vlad/.cache/co
ursier/v1/https/repo1.maven.org/maven2/io/get-coursier/apps/1.0.20/apps-1.0.20.jar!cs.json: Unrecognized launcher type: prebuilt
        at coursier.install.InfoFile$.$anonfun$appDescriptor$3(InfoFile.scala:78)
        at scala.util.Either$LeftProjection.map(Either.scala:573)
        at coursier.install.InfoFile$.$anonfun$appDescriptor$2(InfoFile.scala:77)
        at scala.util.Either.flatMap(Either.scala:341)
        at coursier.install.InfoFile$.appDescriptor(InfoFile.scala:74)
        at coursier.install.InstallDir.$anonfun$maybeUpdate$9(InstallDir.scala:412)
        at coursier.install.InstallDir.$anonfun$maybeUpdate$9$adapted(InstallDir.scala:406)
        at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
        at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
        at coursier.util.Task$.wrap(Task.scala:84)
        at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

**Comment by agilesteel** [comment]
I installed `coursier` (the jvm version), updated `cs` (the native image) and with that new version everything worked. For someone who stumbles on this in the future:
```bash
cs install coursier
coursier update cs
cs update
cs uninstall coursier
```
