### ISSUE TITLE
`Unrecognized launcher type: prebuilt` in `cs setup`

### ISSUE THREAD

**Issue by armanbilge** [coursier/coursier#2351]
Please let me know any other details I can provide. Thanks!

```
$ java -version
Picked up JAVA_TOOL_OPTIONS:  -Xmx2576m
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

$ ./cs setup -y
Checking if a JVM is installed
Found a JVM installed under /home/gitpod/.sdkman/candidates/java/current.

Checking if ~/.local/share/coursier/bin is in PATH
Should we add ~/.local/share/coursier/bin to your PATH via ~/.profile, ~/.bash_profile? [Y/n] Y

Checking if the standard Scala applications are installed
  Found ammonite
Exception in thread "main" coursier.install.Channels$ErrorProcessingAppDescriptor: Error processing app descriptor for app cs from channel io.get-coursier:apps: Unrecognized launcher type: prebuilt
        at coursier.install.Channels.$anonfun$appDescriptor$5(Channels.scala:77)
        at coursier.install.Channels.$anonfun$appDescriptor$5$adapted(Channels.scala:64)
        at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
        at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
        at coursier.util.Task$.wrap(Task.scala:84)
        at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)

**Comment by keynmol** [comment]
https://github.com/coursier/coursier/issues/2350 as well?

**Comment by armanbilge** [comment]
Yeah, seems that issue was closed prematurely :) it's a workaround, but it seems the Fix™ is to do that for whatever native binary is being distributed.

**Comment by dn-mib** [comment]
We have the same problem on our build server, but got it working again with this work around:

`coursier install --default-channels=false --channel="io.get-coursier:apps:1.0.19" sbt:1.6.1`

**Comment by julienrf** [comment]
Same problem here: https://github.com/scala/docs.scala-lang/runs/5033608530?check_suite_focus=true

Also reported there: https://github.com/coursier/setup-action/issues/171

**Comment by alexarchambault** [comment]
This ought to have gotten better since https://github.com/coursier/apps/pull/134 (so `io.get-coursier:apps:1.0.21`). cs 2.0.16 launchers should be able to install / update cs itself again.

But yeah, using `coursier/setup-action@v1.2.0-M2` also fixes that.

**Comment by alexarchambault** [comment]
Actually, `sbtn` rather than `cs` seems to be an issue with `coursier/setup-action` 1.1.x. https://github.com/coursier/apps/pull/135 should fix that.

**Comment by alexarchambault** [comment]
Closing this, as I think this should be fixed since https://github.com/coursier/apps/pull/135. We'll try to come up with backward- (unless it's forward-?) compatible ways to evolve the app descriptor format in the future, to avoid such issues.
