### ISSUE TITLE
update failure & confusing error message

### ISSUE THREAD

**Issue by mtk** [coursier/coursier#2357]
```
% cs update
https://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
  No new update since 2022-02-02 05:04:16
https://repo1.maven.org/maven2/com/lihaoyi/ammonite_2.13.8/maven-metadata.xml
  No new update since 2022-02-01 09:09:01
https://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.12/maven-metadata.xml
  No new update since 2022-02-01 11:57:53
https://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.12/maven-metadata.xml
  No new update since 2022-02-01 11:57:53
https://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.12/maven-metadata.xml
  No new update since 2022-02-01 11:57:53
Error downloading gz+https://github.com/coursier/coursier/releases/download/v2.1.0-M4/cs-x86_64-pc-linux.gz
```

**Comment by alexarchambault** [comment]
Do you know what's the current version of `cs`? (`cs --help` should print it.)

As a workaround, this should work:
```text
$ cs install coursier
$ coursier update cs
```

**Comment by mtk** [comment]
this is strange.  i had two identical (hand-wavvy identical, software only) systems.  both were up-to-date fedora 35 instances (one a vm, the other on bare metal).  in response to "--help", both reported version 2.0.16.  a 'cs update' on one worked.  and on the other failed as reported.  after i did your workaround, 'cs update' worked.  however, 'cs --help' after the workaround reports:

``` 
cs --help
Usage: /home/mtk/.local/share/coursier/bin/.cs.aux <COMMAND>
Coursier is the Scala application and artifact manager.
It can install Scala applications and setup your Scala development environment.
It can also download and cache artifacts from the web.

Install application commands:
  install    Install an application from its descriptor.
  list       List all currently installed applications.
  setup      Setup a machine for Scala development.
```

**Comment by mtk** [comment]
and i just did the workaround on the box where 'cs update' worked (where '--help' reports 2.0.16).  and it triggered this:

```
% coursier update cs
Exception in thread "main" java.lang.Exception: Reading /home/mtk/.local/share/coursier/bin/cs
        at coursier.install.InfoFile$.readSource(InfoFile.scala:64)
        at coursier.install.InstallDir.$anonfun$maybeUpdate$3(InstallDir.scala:435)
        at coursier.install.InstallDir.$anonfun$maybeUpdate$3$adapted(InstallDir.scala:427)
        at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
        at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
        at coursier.util.Task$.wrap(Task.scala:82)
        at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1607)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1497)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1504)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1308)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1271)
```

**Comment by kalanzai** [comment]
Also seeing this on Mac
```
Error downloading gz+https://github.com/coursier/coursier/releases/download/v2.1.0-M4/cs-x86_64-apple-darwin.gz
```
Running
```
coursier update cs
```
alleviated the issue

**Comment by matil019** [comment]
It seems that `coursier` at `gh-pages` branch (downloaded from https://git.io/coursier-cli, as explained in [the doc](https://get-coursier.io/docs/cli-installation#latest-launchers)) causes this issue. The `master` branch (https://github.com/coursier/launchers/raw/master/coursier) works fine.

**Comment by alexarchambault** [comment]
@matil019 https://github.com/coursier/coursier/pull/2359 should fix that (no more `git.io` in the install docs)

**Comment by matil019** [comment]
@alexarchambault Unfortunately, the `gh-pages` branch itself (https://github.com/coursier/coursier/raw/gh-pages/coursier, which the `git.io` URL pointed to) fails with the same error.

**Comment by maxstreese** [comment]
Hi everyone, is this actually solved? I just got the same error message using the `master` link:

```
> curl -fL https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz | gzip -d > cs
...
> chmod +x cs
> ./cs update cs
Exception in thread "main" java.lang.Exception: Reading /home/max/.local/share/coursier/bin/cs
	at coursier.install.InfoFile$.readSource(InfoFile.scala:64)
	at coursier.install.InstallDir.$anonfun$maybeUpdate$3(InstallDir.scala:435)
	at coursier.install.InstallDir.$anonfun$maybeUpdate$3$adapted(InstallDir.scala:427)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at coursier.install.InfoFile$.readSource(InfoFile.scala:44)
```

Or am I missing something?

**Comment by okennedy** [comment]
It looks like the default launcher link has a corrupt jar embedded in it.  Fortunately install still works and `cs` comes under multiple names, so the following workaround worked for me:
```
cs install coursier
rm `which cs`
coursier install cs
```
