### ISSUE TITLE
new 'cs update' glitch

### ISSUE THREAD

**Issue by mtk** [coursier/coursier#2369]
% cs update
https://repo1.maven.org/maven2/com/lihaoyi/ammonite_2.13.8/maven-metadata.xml
  No new update since 2022-02-01 09:09:01
https://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
  No new update since 2022-02-06 13:51:21
https://repo1.maven.org/maven2/org/scala-lang/scala-library/maven-metadata.xml
  No new update since 2022-01-10 13:30:20
https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.13/maven-metadata.xml
  No new update since 2022-02-11 15:30:18
Exception in thread "main" coursier.error.ResolutionError$CantDownloadModule: Error downloading ch.epfl.scala:bloopgun_2.13:latest.stable
  No latest stable version found in https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.13/maven-metadata.xml
        at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:347)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:286)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at coursier.Resolve$.validate(Resolve.scala:345)
        at coursier.Resolve.validate0$1(Resolve.scala:117)
        at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:167)
        at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
        at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
        at coursier.util.Task$.wrap(Task.scala:82)
        at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)

**Comment by valencik** [comment]
Ran into this issue when trying to install `bloop-jvm`

Workaround was to pin the exact version to download:
```
cs install bloop-jvm:1.4.12-48-81973d63
```

**Comment by mtk** [comment]
that gets you a fresh bloop.  but the 'cs update' still fails.
