### ISSUE TITLE
`cs setup` throws a java.util.zip.ZipException: invalid entry CRC

### ISSUE THREAD

**Issue by sunLightLeaf** [coursier/coursier#2395]
So I'm trying to setup coursier, but when I call `./cs setup` it throws a ZipException. Which leads me to think there might be something wrong with some of my jar files. So I follwed [this](https://stackoverflow.com/questions/41932426/java-util-zip-zipexception-invalid-entry-crc-expected-0x0-but-got-0xc86c27fe) advice, run that script (only I made it recursively scan everything starting with root), but found no bad jars.

What might be the problem, and how may I fix it?

>$ ./cs setup
>Checking if a JVM is installed
>Found a JVM installed under /home/lightleaf/.cache/coursier/arc/https/github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10/OpenJDK8U-jdk_x64_linux_hotspot_8u292b10.tar.gz/jdk8u292-b10.
>
>Checking if ~/.local/share/coursier/bin is in PATH
>
>Checking if the standard Scala applications are installed
>Exception in thread "main" java.util.zip.ZipException: invalid entry CRC (expected 0x8899ec42 but got 0xd4a7d99d)
>	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:409)
>	at java.util.zip.ZipInputStream.read(ZipInputStream.java:198)
>	at coursier.launcher.internal.FileUtil$.readFullyUnsafe(FileUtil.scala:20)
>	at coursier.launcher.internal.Zip$$anon$1.next(Zip.scala:20)
>	at coursier.launcher.internal.Zip$$anon$1.next(Zip.scala:10)
>	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:514)
>	at scala.collection.Iterator.foreach(Iterator.scala:943)
>	at scala.collection.Iterator.foreach$(Iterator.scala:943)
>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
>	at coursier.launcher.BootstrapGenerator$.writeZip(BootstrapGenerator.scala:112)
>	at coursier.launcher.BootstrapGenerator$.$anonfun$generate$2(BootstrapGenerator.scala:62)
>	at coursier.launcher.BootstrapGenerator$.$anonfun$generate$2$adapted(BootstrapGenerator.scala:18)
>	at coursier.launcher.internal.FileUtil$.withOutputStream(FileUtil.scala:43)
>	at coursier.launcher.BootstrapGenerator$.generate(BootstrapGenerator.scala:18)
>	at coursier.launcher.Generator$.generate(Generator.scala:13)
>	at coursier.install.InstallDir.$anonfun$createOrUpdate$15(InstallDir.scala:341)
>	at coursier.install.InstallDir$.coursier$install$InstallDir$$writing(InstallDir.scala:569)
>	at coursier.install.InstallDir.$anonfun$createOrUpdate$14(InstallDir.scala:340)
>	at coursier.install.InstallDir.$anonfun$createOrUpdate$14$adapted(InstallDir.scala:310)
>	at coursier.install.InstallDir.$anonfun$createOrUpdate$22(InstallDir.scala:416)
>	at coursier.install.InstallDir.$anonfun$createOrUpdate$22$adapted(InstallDir.scala:415)
>	at coursier.install.Updatable$.get$1(Updatable.scala:61)
>	at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:106)
>	at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:71)
>	at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:95)
>	at coursier.install.Updatable$.writing(Updatable.scala:106)
>	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:415)
>	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:96)
>	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:71)
>	at coursier.cli.setup.MaybeInstallApps.$anonfun$task$3(MaybeInstallApps.scala:22)
>	at coursier.util.Task$.wrap(Task.scala:82)
>	at coursier.util.Task$.$anonfun$delay$2(Task.scala:47)
>	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
>	at scala.util.Success.$anonfun$map$1(Try.scala:255)
>	at scala.util.Success.map(Try.scala:213)
>	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
>	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
>	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
>	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
>	at java.lang.Thread.run(Thread.java:833)
>	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
>	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)

**Comment by alexarchambault** [comment]
@sunLightLeaf What OS are you using? Could it be ArchLinux?

**Comment by robatipoor** [comment]
> @sunLightLeaf What OS are you using? Could it be ArchLinux?

I use manjaro, I have the same problem

**Comment by lakinwecker** [comment]
I'm also on arch linux and ran into this issue today.  It seems the linked pull request/issue on scala-cli is probably the root cause of the problem.

In my case, I'm not directly using the graalvm, so the only reason it gets used is because I had downloaded and was using a version of coursier that is compiled natively for linux, which uses graalvm I guess.  I switched to the jar based installation: https://get-coursier.io/docs/cli-installation#linux-macos  And let it use the version of the JDK/JRE that I have installed and now it's working again for me.

**Comment by sunLightLeaf** [comment]
I'm on Arch, and @lakinwecker 's solution worked for me. Thanks!

**Comment by TrevCan** [comment]
Hello, I have the same issue when using the native installer and running `cs setup`. It also crashes with an invalid CRC entry.

This is the log:
<details>
<summary><code>cs.setup.log</code></summary>
<pre><code>
Checking if a JVM is installed
Checking if a JVM is installed
Found a JVM installed under /home/myuser/.cache/coursier/arc/https/github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11%252B28/OpenJDK11-jdk_x64_linux_hotspot_11_28.tar.gz/jdk-11+28.
Found a JVM installed under /home/myuser/.cache/coursier/arc/https/github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11%252B28/OpenJDK11-jdk_x64_linux_hotspot_11_28.tar.gz/jdk-11+28.


Checking if ~/.local/share/coursier/bin is in PATH
Checking if ~/.local/share/coursier/bin is in PATH

Checking if the standard Scala applications are installed

Checking if the standard Scala applications are installed
Exception in thread "main" java.util.zip.ZipException: invalid entry CRC (expected 0x8899ec42 but got 0xd4a7d99d)
	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:409)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:198)
	at coursier.launcher.internal.FileUtil$.readFullyUnsafe(FileUtil.scala:20)
	at coursier.launcher.internal.Zip$$anon$1.next(Zip.scala:20)
Exception in thread "main" java.util.zip.ZipException: invalid entry CRC (expected 0x8899ec42 but got 0xd4a7d99d)
	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:409)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:198)
	at coursier.launcher.internal.FileUtil$.readFullyUnsafe(FileUtil.scala:20)
	at coursier.launcher.internal.Zip$$anon$1.next(Zip.scala:20)
	at coursier.launcher.internal.Zip$$anon$1.next(Zip.scala:10)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:514)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at coursier.launcher.internal.Zip$$anon$1.next(Zip.scala:10)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:514)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.launcher.BootstrapGenerator$.writeZip(BootstrapGenerator.scala:112)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.launcher.BootstrapGenerator$.writeZip(BootstrapGenerator.scala:112)
	at coursier.launcher.BootstrapGenerator$.$anonfun$generate$2(BootstrapGenerator.scala:62)
	at coursier.launcher.BootstrapGenerator$.$anonfun$generate$2(BootstrapGenerator.scala:62)
	at coursier.launcher.BootstrapGenerator$.$anonfun$generate$2$adapted(BootstrapGenerator.scala:18)
	at coursier.launcher.internal.FileUtil$.withOutputStream(FileUtil.scala:43)
	at coursier.launcher.BootstrapGenerator$.$anonfun$generate$2$adapted(BootstrapGenerator.scala:18)
	at coursier.launcher.internal.FileUtil$.withOutputStream(FileUtil.scala:43)
	at coursier.launcher.BootstrapGenerator$.generate(BootstrapGenerator.scala:18)
	at coursier.launcher.BootstrapGenerator$.generate(BootstrapGenerator.scala:18)
	at coursier.launcher.Generator$.generate(Generator.scala:13)
	at coursier.launcher.Generator$.generate(Generator.scala:13)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$15(InstallDir.scala:341)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$15(InstallDir.scala:341)
	at coursier.install.InstallDir$.coursier$install$InstallDir$$writing(InstallDir.scala:569)
	at coursier.install.InstallDir$.coursier$install$InstallDir$$writing(InstallDir.scala:569)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$14(InstallDir.scala:340)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$14(InstallDir.scala:340)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$14$adapted(InstallDir.scala:310)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$14$adapted(InstallDir.scala:310)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$22(InstallDir.scala:416)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$22(InstallDir.scala:416)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$22$adapted(InstallDir.scala:415)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$22$adapted(InstallDir.scala:415)
	at coursier.install.Updatable$.get$1(Updatable.scala:61)
	at coursier.install.Updatable$.get$1(Updatable.scala:61)
	at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:106)
	at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:106)
	at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:71)
	at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:71)
	at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:95)
	at coursier.install.Updatable$.writing(Updatable.scala:106)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:415)
	at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:95)
	at coursier.install.Updatable$.writing(Updatable.scala:106)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:415)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:96)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:96)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:71)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:71)
	at coursier.cli.setup.MaybeInstallApps.$anonfun$task$3(MaybeInstallApps.scala:22)
	at coursier.cli.setup.MaybeInstallApps.$anonfun$task$3(MaybeInstallApps.scala:22)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$delay$2(Task.scala:47)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at coursier.util.Task$.$anonfun$delay$2(Task.scala:47)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)

</code></pre>
</details>

I am also running Arch Linux

```
> uname --all
Linux t490-4rch 5.17.3-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 14 Apr 2022 01:18:28 +0000 x86_64 GNU/Linux
```

**Comment by alexarchambault** [comment]
Should be fixed by https://github.com/coursier/coursier/pull/2514.
