### ISSUE TITLE
cs uninstall --all uninstalls itself and crashes

### ISSUE THREAD

**Issue by CervEdin** [coursier/coursier#2396]
What I did:

On Windows 10
Installed coursier using
https://raw.githubusercontent.com/coursier/launchers/master/cs-x86_64-pc-win32.zip

uninstalled using
cs uninstall --all

What happened:
```
Uninstalled amm
Uninstalled coursier
Exception in thread "main" java.nio.file.AccessDeniedException: C:\Users\ErikCE\AppData\Local\Coursier\data\bin\.cs.aux.exe
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
        at java.nio.file.Files.deleteIfExists(Files.java:1191)
        at coursier.install.Updatable$.$anonfun$delete$2(Updatable.scala:124)
        at coursier.install.Updatable$.$anonfun$delete$2$adapted(Updatable.scala:124)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at coursier.install.Updatable$.get$2(Updatable.scala:124)
        at coursier.install.Updatable$.$anonfun$delete$3(Updatable.scala:129)
        at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:71)
        at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:95)
        at coursier.install.Updatable$.delete(Updatable.scala:129)
        at coursier.install.InstallDir.delete(InstallDir.scala:102)
        at coursier.cli.install.Uninstall$.$anonfun$run$1(Uninstall.scala:53)
        at coursier.cli.install.Uninstall$.$anonfun$run$1$adapted(Uninstall.scala:51)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at coursier.cli.install.Uninstall$.run(Uninstall.scala:51)
        at coursier.cli.install.Uninstall$.run(Uninstall.scala:16)
        at caseapp.core.app.CaseApp.main(CaseApp.scala:149)
        at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:109)
        at coursier.cli.Coursier$.main(Coursier.scala:115)
        at coursier.cli.Coursier.main(Coursier.scala)
The batch file cannot be found.
```

What I expected:

`cs uninstall amm cs scala scalac sbt sbtn scalafmt && coursier unistall coursier`
which coincidentally, also fails at `coursier uninstall coursier`.

**Comment by rustedwizard** [comment]
Any update on this one? Exactly same behavior on my machine as well. I am on Windows 11 here.

**Comment by pWoLiAn** [comment]
Same here
