### ISSUE TITLE
Coursier fails to install Metals with error ZipException: Invalid entry CRC

### ISSUE THREAD

**Issue by Sberlos** [coursier/coursier#2398]
Hello everybody,

I tried installing metals (https://github.com/scalameta/metals) with `cs install metals` and I get the following error:
﻿
```
https://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
  100.0% [##########] 2.2 KiB (50.2 KiB / s)
https://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
  No new update since 2022-03-30 18:39:24
https://repo1.maven.org/maven2/io/get-coursier/apps/1.0.24/apps-1.0.24.pom
  100.0% [##########] 1.3 KiB (26.7 KiB / s)
https://repo1.maven.org/maven2/org/scalameta/metals_2.12/maven-metadata.xml
  No new update since 2022-03-08 14:30:01
https://repo1.maven.org/maven2/com/google/code/gson/gson/maven-metadata.xml
  No new update since 2022-02-11 20:18:46
Exception in thread "main" java.util.zip.ZipException: invalid entry CRC (expected 0x6c89cde4 but got 0x30b7f83b)
        at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:408)
        at java.util.zip.ZipInputStream.read(ZipInputStream.java:197)
        at coursier.launcher.internal.FileUtil$.readFullyUnsafe(FileUtil.scala:20)
        at coursier.launcher.internal.Zip$$anon$1.next(Zip.scala:20)
        at coursier.launcher.internal.Zip$$anon$1.next(Zip.scala:10)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:514)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at coursier.launcher.BootstrapGenerator$.writeZip(BootstrapGenerator.scala:108)
        at coursier.launcher.BootstrapGenerator$.$anonfun$generate$2(BootstrapGenerator.scala:61)
        at coursier.launcher.BootstrapGenerator$.$anonfun$generate$2$adapted(BootstrapGenerator.scala:18)
        at coursier.launcher.internal.FileUtil$.withOutputStream(FileUtil.scala:44)
        at coursier.launcher.BootstrapGenerator$.generate(BootstrapGenerator.scala:18)
        at coursier.launcher.Generator$.generate(Generator.scala:13)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$15(InstallDir.scala:328)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at coursier.install.InstallDir$.coursier$install$InstallDir$$writing(InstallDir.scala:534)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$14(InstallDir.scala:328)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$14$adapted(InstallDir.scala:299)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$21(InstallDir.scala:385)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$21$adapted(InstallDir.scala:384)
        at coursier.install.Updatable$.get$1(Updatable.scala:55)
        at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:96)
        at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:72)
        at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:98)
        at coursier.install.Updatable$.writing(Updatable.scala:96)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:384)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:87)
        at coursier.cli.install.Install$.$anonfun$run$7(Install.scala:108)
        at coursier.cli.install.Install$.$anonfun$run$7$adapted(Install.scala:95)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at coursier.cli.install.Install$.run(Install.scala:95)
        at coursier.cli.Coursier$.$anonfun$runA$2(Coursier.scala:152)
        at coursier.cli.Coursier$.$anonfun$runA$2$adapted(Coursier.scala:140)
        at coursier.cli.CommandAppPreA.run(CommandAppPreA.scala:22)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5(CommandAppWithPreCommand.scala:99)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5$adapted(CommandAppWithPreCommand.scala:99)
        at scala.util.Either.fold(Either.scala:191)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3(CommandAppWithPreCommand.scala:99)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3$adapted(CommandAppWithPreCommand.scala:85)
        at scala.Option.foreach(Option.scala:407)
        at caseapp.core.app.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:85)
        at coursier.cli.Coursier$.main(Coursier.scala:105)
        at coursier.cli.Coursier.main(Coursier.scala)
```

My system is Arch Linux, coursier version 2.0.16, jdk11.

Let me know if I have to provide additional information.

**Comment by ckipp01** [comment]
Following up from the convo we were having on the scalameta discord, this looks to be the issue mentioned in https://github.com/coursier/coursier/issues/2395 although we should probably leave this issue open since you're the second one this week that I've had report this on Discord.
