### ISSUE TITLE
Can't install with corporate repo

### ISSUE THREAD

**Issue by skestle** [coursier/coursier#2405]
If I try to install with our corporate repository I get:
```
cs install --no-default -r http://repository/maven metals
http://repository/maven/io/get-coursier/apps/maven-metadata.xml
  No new update since 2022-04-21 23:37:52
Exception in thread "main" coursier.error.ResolutionError$CantDownloadModule: Error downloading org.scalameta:metals_2.12:latest.stable
  download error: Caught java.net.SocketException (Network is unreachable) while downloading https://repo1.maven.org/maven2/org/scalameta/metals_2.12/maven-metadata.xml
	at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:347)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at coursier.Resolve$.validate(Resolve.scala:345)
	at coursier.Resolve.validate0$1(Resolve.scala:117)
	at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:167)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
```

Using `fetch` instead of `install` works

**Comment by skestle** [comment]
I'd love to tell you what version of coursier I'm running, but I can't figure out how.

**Comment by skestle** [comment]
In gitter, Vijay was able to fix his issue by providing credentials in file instead of in the `-r` argument. However, I have no need for credentials. https://gitter.im/coursier/coursier?at=62623631f43b6d783f6069b2

Perhaps this issue doesn't need to be fixed in the way I'd like - even just some logging about why it gives up on my repo would be incredibly helpful.
