### ISSUE TITLE
Allow specifying a version number as just `+` without leading digits

### ISSUE THREAD

**Issue by smarter** [coursier/coursier#2408]
This came up in https://contributors.scala-lang.org/t/why-doesnt-scala-have-library-listing/5696/8:
```scala
% cs fetch 'org.scalacheck::scalacheck:1+'
/home/smarter/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalacheck/scalacheck_2.13/1.16.0/scalacheck_2.13-1.16.0.jar
/home/smarter/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar
/home/smarter/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar
% cs fetch 'org.scalacheck::scalacheck:+'
Exception in thread "main" coursier.install.AppArtifacts$ScalaDependenciesNotFound: Can't find a scala version suffix for org.scalacheck::scalacheck:+ (likely a non existing module or version)
        at coursier.install.AppDescriptor.$anonfun$processDependencies$9(AppDescriptor.scala:231)
        at scala.Option.toRight(Option.scala:485)
        at coursier.install.AppDescriptor.processDependencies(AppDescriptor.scala:231)
        at coursier.cli.resolve.Resolve$.$anonfun$depsAndReposOrError$4(Resolve.scala:90)
        at scala.util.Either.flatMap(Either.scala:341)
        at coursier.cli.resolve.Resolve$.$anonfun$depsAndReposOrError$2(Resolve.scala:61)
        at scala.util.Either.flatMap(Either.scala:341)
        at coursier.cli.resolve.Resolve$.depsAndReposOrError(Resolve.scala:61)
        at coursier.cli.resolve.Resolve$.task(Resolve.scala:260)
        at coursier.cli.fetch.Fetch$.task(Fetch.scala:28)
        at coursier.cli.fetch.Fetch$.run(Fetch.scala:114)
        at coursier.cli.fetch.Fetch$.run(Fetch.scala:18)
        at caseapp.core.app.CaseApp.main(CaseApp.scala:149)
        at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:109)
        at coursier.cli.Coursier$.main(Coursier.scala:115)
        at coursier.cli.Coursier.main(Coursier.scala)
% cs fetch 'org.scalacheck_2.13:scalacheck:+'
Resolution error: Error downloading org.scalacheck_2.13:scalacheck:+
  not found: /home/smarter/.ivy2/local/org.scalacheck_2.13/scalacheck/+/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scalacheck_2/13/scalacheck/+/scalacheck-+.pom
% cs fetch 'org.scalacheck_2.13:scalacheck:1+'
Resolution error: Error downloading org.scalacheck_2.13:scalacheck:1+
  not found: /home/smarter/.ivy2/local/org.scalacheck_2.13/scalacheck
  not found: https://repo1.maven.org/maven2/org/scalacheck_2/13/scalacheck/maven-metadata.xml
```

**Comment by nafg** [comment]
The incantation you're looking for is `latest.release`.

```
❯ cs fetch 'org.scalacheck::scalacheck:latest.release'
https://repo1.maven.org/maven2/org/scalacheck/scalacheck_2.13/1.16.0/scalacheck_2.13-1.16.0.jar
  100.0% [##########] 683.7 KiB (3.3 MiB / s)
https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar
  100.0% [##########] 5.7 MiB (17.9 MiB / s)
/home/naftoli/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalacheck/scalacheck_2.13/1.16.0/scalacheck_2.13-1.16.0.jar
/home/naftoli/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar
/home/naftoli/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar
```

**Comment by smarter** [comment]
Thanks! It looks like you need `latest.stable` to avoid beta/rc releases.
