### ISSUE TITLE
could not resolve coursierapi....ApiInternalNativeApi

### ISSUE THREAD

**Issue by simlei** [coursier/coursier#2447]
Hi, I'm getting this while trying to update to the latest bloop version:

```text
cs install bloop:1.5.0-22-91111c15 -- -H:PrintFlags=+
https://repo1.maven.org/maven2/org/graalvm/nativeimage/svm-driver/maven-metadata.xml
  No new update since 2022-05-20 10:25:34
[.local/share/coursier/bin/.bloop.aux.part:109475]    classlist:   9,137.13 ms
[.local/share/coursier/bin/.bloop.aux.part:109475]        (cap):   2,154.16 ms
[.local/share/coursier/bin/.bloop.aux.part:109475]        setup:   3,078.24 ms
Error: Error parsing reflection configuration in jar:file:/home/snuc/.cache/coursier/v1/https/repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.13/1.5.0-22-91111c15/bloopgun_2.13-1.5.0-22-91111c15.jar!/META-INF/native-image/io.get-coursier/jni-utils-coursierapi/reflect-config.json:
Could not resolve coursierapi.internal.jniutils.ApiInternalNativeApi for reflection configuration. To allow unresolvable reflection configuration, use option -H:+AllowIncompleteClasspath
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ReflectionConfigurationResources.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
Exception in thread "main" java.lang.RuntimeException: Error running native-image (exit code: 1)
	at scala.sys.package$.error(package.scala:30)
	at coursier.launcher.NativeImageGenerator$.generate(NativeImageGenerator.scala:124)
	at coursier.launcher.Generator$.generate(Generator.scala:14)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$15(InstallDir.scala:341)
	at coursier.install.InstallDir$.coursier$install$InstallDir$$writing(InstallDir.scala:569)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$14(InstallDir.scala:340)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$14$adapted(InstallDir.scala:310)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$22(InstallDir.scala:416)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$22$adapted(InstallDir.scala:415)
	at coursier.install.Updatable$.get$1(Updatable.scala:61)
	at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:106)
	at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:71)
	at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:95)
	at coursier.install.Updatable$.writing(Updatable.scala:106)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:415)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:96)
	at coursier.cli.install.Install$.$anonfun$run$7(Install.scala:126)
	at coursier.cli.install.Install$.$anonfun$run$7$adapted(Install.scala:113)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at coursier.cli.install.Install$.run(Install.scala:113)
	at coursier.cli.install.Install$.run(Install.scala:21)
	at caseapp.core.app.CaseApp.main(CaseApp.scala:149)
	at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:109)
	at coursier.cli.Coursier$.main(Coursier.scala:115)
	at coursier.cli.Coursier.main(Coursier.scala)
```

**Comment by alexarchambault** [comment]
`cs install` trying to build a native-image on its own is kind of broken… It does this when it doesn't find pre-built binaries. We should disable that feature IMO, and simply complain about the lack of pre-built binary.
