### ISSUE TITLE
Coursier somewhat broken on FreeBSD

### ISSUE THREAD

**Issue by csgordon** [coursier/coursier#2478]
Coursier does not appear to fully work on FreeBSD anymore.

The docs suggest installing a FreeBSD package. I haven't tried that because the latest version in that package manager is 1.1.0.m12, which is quite old.

There is an "Any" platform launcher, linked to https://github.com/coursier/coursier/raw/gh-pages/coursier. Downloading this (as ```cs```) and trying to set up leads to issues:

```
➜  ~ ./cs setup
Exception in thread "main" java.lang.Exception: Unrecognized OS: freebsd
	at coursier.jvm.JvmIndex$.defaultOs(JvmIndex.scala:199)
	at coursier.jvm.JvmCache$.apply(JvmCache.scala:23)
	at coursier.cli.jvm.SharedJavaParams.jvmCacheOf$1(SharedJavaParams.scala:32)
	at coursier.cli.jvm.SharedJavaParams.cacheAndHome(SharedJavaParams.scala:40)
	at coursier.cli.jvm.SharedJavaParams.javaHome(SharedJavaParams.scala:61)
	at coursier.cli.setup.Setup$.run(Setup.scala:32)
	at coursier.cli.Coursier$.$anonfun$runA$2(Coursier.scala:166)
	at coursier.cli.Coursier$.$anonfun$runA$2$adapted(Coursier.scala:140)
	at coursier.cli.CommandAppPreA.run(CommandAppPreA.scala:22)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5(CommandAppWithPreCommand.scala:99)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5$adapted(CommandAppWithPreCommand.scala:99)
	at scala.util.Either.fold(Either.scala:191)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3(CommandAppWithPreCommand.scala:99)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3$adapted(CommandAppWithPreCommand.scala:85)
	at scala.Option.foreach(Option.scala:407)
	at caseapp.core.app.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:85)
	at coursier.cli.Coursier$.main(Coursier.scala:105)
	at coursier.cli.Coursier.main(Coursier.scala)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at coursier.bootstrap.launcher.a.a(Unknown Source)
	at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
➜  ~ 
```
This was after running it once with no arguments, during which it did download various dependencies. I'm using OpenJDK 18.0.1. Some other subcommands (```java```, ```java-home```) yield the same failure point.

But it's not *totally* broken. I did ```./cs install ammonite``` and it appears to have given me a working Ammonite shell with Scala 2.13.8 (I only tested a couple simple expressions though).

I'm happy to kick the tires on any possible fixes, including trying to fix it myself if a maintainer thinks it would likely be "small".

**Comment by alexarchambault** [comment]
@csgordon I wouldn't expect `cs setup` to work out-of-the-box on FreeBSD. It tries to install a JVM itself if none is found (using the [coursier JVM index](https://github.com/coursier/jvm-index)), but this index has no JVMs for FreeBSD. It seems JVM vendors don't package JVMs for FreeBSD. My understanding is that JVMs should be installed via the FreeBSD package manager there. So on FreeBSD, coursier shoudn't try to install one. It should only complain if it doesn't find one, and maybe suggest users to install one via the FreeBSD package manager.

That said, it seems you ran the JVM launcher of coursier on FreeBSD (so I assume you already installed a JVM yourself), and apparently, coursier tried to look for a JVM in the index anyway. I'm not sure why it does that, but I guess it shouldn't, so that would need to be addressed too.
