### ISSUE TITLE
Any coursier call which results in reaching out to jvm-index fails behind a proxy with SSLHandshake exception.

### ISSUE THREAD

**Issue by DamianReeves** [coursier/coursier#2482]
When using couriser behind a proxy it seems call which use `JvmIndex` to fetch the jvm-index index.json file fail with an SSLHandshakeException:

```
Error: java.lang.Exception: java.lang.Exception: Error while getting https://github.com/coursier/jvm-index/raw/master/index.json: download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://github.com/coursier/jvm-index/raw/master/index.json
```

It feels like there is an issue with how these calls are made as things like downloading artifacts work no problem.

**Comment by ashwinbhaskar** [comment]
I get a similar error when I run `brew install scalacenter/bloop/bloop`
```
Exception in thread "main" java.lang.Exception: Error while getting https://github.com/coursier/jvm-index/raw/master/index.json: download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://github.com/coursier/jvm-index/raw/master/index.json
	at coursier.jvm.JvmIndex$.$anonfun$load$5(JvmIndex.scala:142)
	at coursier.jvm.JvmIndex$.$anonfun$load$5$adapted(JvmIndex.scala:140)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)```

**Comment by ryanstull** [comment]
Getting the same issue

**Comment by DamianReeves** [comment]
Wondering if there is any progress on this, or if there is anything I can do to help debug/troubleshoot this?
