### ISSUE TITLE
Coursier installation fails behind proxy

### ISSUE THREAD

**Issue by nemoo** [coursier/coursier#2539]
I tried this install method on ubuntu: curl -fL https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz | gzip -d > cs && chmod +x cs && ./cs setup 

When running the setup part, I get this output:
```
./cs setup
Checking if a JVM is installed
Found a JVM installed under /usr/lib/jvm/java-1.17.0-openjdk-amd64.

Checking if ~/.local/share/coursier/bin is in PATH

Checking if the standard Scala applications are installed
Exception in thread "main" coursier.error.ResolutionError$CantDownloadModule: Error downloading io.get-coursier:apps:latest.release
  not found: /home/username/.ivy2/local/io.get-coursier/apps
  download error: Caught java.net.ConnectException (Connection refused) while downloading https://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
	at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:348)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
```

Environment variables HTTPS_PROXY and HTTP_PROXY are set correctly.

In the install documentation https://get-coursier.io/docs/cli-installation I could not find any information on how to configure a proxy. 
The proxy documentation is only about how to use a proxy after you have installed Coursier, but I am failing before that, while call the coursier setup: https://get-coursier.io/docs/other-proxy

**Comment by alexarchambault** [comment]
https://github.com/coursier/coursier/pull/2541 made that easier, but its changes need to be documented.

**Comment by 2072** [comment]
I would like to add that, on Windows, usage also fails completely behind a proxy. In the worst case this is a silent fail with no output to the console (when connecting without proxy means going through a stupid firewall that displays an error message with an invalid https certificate...).
Moreover, JVM_OPTS environment variable is ignored by all `.aux.exe` lauchers on Windows.

**Comment by amarossy** [comment]
On Windows for me `cs-x86_64-pc-win32.exe -J-Dhttps.proxyHost=... -J-Dhttps.proxyPort=...` worked with the current version (3.7).
