### ISSUE TITLE
./cs setup fail

### ISSUE THREAD

**Issue by ztsweet** [coursier/coursier#2570]
```
Checking if a JVM is installed
Found a JVM installed under /home/fzt/jdk-11.

Checking if ~/.local/share/coursier/bin is in PATH

Checking if the standard Scala applications are installed
  Found ammonite
Exception in thread "main" java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
        at java.io.FilterInputStream.read(FilterInputStream.java:106)
        at coursier.install.InstallDir$.coursier$install$InstallDir$$writeTo(InstallDir.scala:612)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$18(InstallDir.scala:363)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$18$adapted(InstallDir.scala:362)
        at coursier.install.internal.ArchiveUtil$.withGzipContent(ArchiveUtil.scala:98)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$14(InstallDir.scala:362)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$14$adapted(InstallDir.scala:311)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$22(InstallDir.scala:417)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$22$adapted(InstallDir.scala:416)
        at coursier.install.Updatable$.get$1(Updatable.scala:61)
        at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:106)
        at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:71)
        at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:95)
        at coursier.install.Updatable$.writing(Updatable.scala:106)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:416)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:96)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:71)
        at coursier.cli.setup.MaybeInstallApps.$anonfun$task$3(MaybeInstallApps.scala:22)
        at coursier.util.Task$.wrap(Task.scala:82)
        at coursier.util.Task$.$anonfun$delay$2(Task.scala:47)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
```

**Comment by chungtc** [comment]
try sudo apt install unzip

**Comment by alexarchambault** [comment]
> try sudo apt install unzip

@chungtc Not sure how that can help, coursier doesn't rely on the `unzip` binary at all.

**Comment by julienrf** [comment]
The problem looks like this one: https://stackoverflow.com/questions/24531089/exception-unexpected-end-of-zlib-input-stream. Would it be possible that the file we try to decompress has not been fully written (and closed) on the filesystem?

**Comment by simlei** [comment]
This hit me today:

1) downloaded via 
```bash
curl -fL "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz" | gzip -d > cs
```

Then tried to installed via ./cs setup, but failed early!

```txt
$ ./cs setup
Checking if a JVM is installed
Found a JVM installed under /home/sleischnig/.sdkman/candidates/java/current.

Checking if ~/.local/share/coursier/bin is in PATH
  Should we add ~/.local/share/coursier/bin to your PATH via ~/.profile? [Y/n] Y

Checking if the standard Scala applications are installed
  Found ammonite
  Found cs
  Found coursier
  Found scala
  Found scalac
Exception in thread "main" java.io.EOFException: Unexpected end of ZLIB input stream
        at java.base@17.0.5/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
        at java.base@17.0.5/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.base@17.0.5/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
        at java.base@17.0.5/java.io.FilterInputStream.read(FilterInputStream.java:106)
        at coursier.install.InstallDir$.coursier$install$InstallDir$$writeTo(InstallDir.scala:615)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$18(InstallDir.scala:354)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$18$adapted(InstallDir.scala:353)
        at coursier.install.internal.ArchiveUtil$.withGzipContent(ArchiveUtil.scala:98)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$14(InstallDir.scala:353)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$14$adapted(InstallDir.scala:302)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$22(InstallDir.scala:408)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$22$adapted(InstallDir.scala:407)
        at coursier.install.Updatable$.get$1(Updatable.scala:61)
        at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:106)
        at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:73)
        at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:93)
        at coursier.install.Updatable$.writing(Updatable.scala:106)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:407)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:96)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:71)
        at coursier.cli.setup.MaybeInstallApps.$anonfun$task$3(MaybeInstallApps.scala:22)
        at coursier.util.Task$.wrap(Task.scala:82)
        at coursier.util.Task$.$anonfun$delay$2(Task.scala:47)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

**Comment by julienrf** [comment]
Thank you for reporting. Which operating system do you use?

**Comment by simlei** [comment]
> Thank you for reporting. Which operating system do you use?

Ubuntu 20.04

**Comment by liuxiaocs7** [comment]
Hi, @julienrf, seems same question:

follow setup from here: https://www.scala-lang.org/download/

```bash
user@PC:~$ curl -fL https://github.com/coursier/coursier/releases/latest/download/cs-x86_64-pc-linux.gz | gzip -d > cs && chmod +x cs && ./cs setup
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100 19.8M  100 19.8M    0     0  2126k      0  0:00:09  0:00:09 --:--:-- 4439k
Checking if a JVM is installed
Found a JVM installed under /usr/local/java/jdk1.8.0_321.

Checking if ~/.local/share/coursier/bin is in PATH
  Should we add ~/.local/share/coursier/bin to your PATH via ~/.profile? [Y/n] y

Checking if the standard Scala applications are installed
  Installed ammonite

Exception in thread "main" java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base@17.0.5/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
	at java.base@17.0.5/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.base@17.0.5/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
	at java.base@17.0.5/java.io.FilterInputStream.read(FilterInputStream.java:106)
	at coursier.install.InstallDir$.coursier$install$InstallDir$$writeTo(InstallDir.scala:615)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$18(InstallDir.scala:354)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$18$adapted(InstallDir.scala:353)
	at coursier.install.internal.ArchiveUtil$.withGzipContent(ArchiveUtil.scala:98)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$14(InstallDir.scala:353)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$14$adapted(InstallDir.scala:302)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$22(InstallDir.scala:408)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$22$adapted(InstallDir.scala:407)
	at coursier.install.Updatable$.get$1(Updatable.scala:61)
	at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:106)
	at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:73)
	at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:93)
	at coursier.install.Updatable$.writing(Updatable.scala:106)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:407)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:96)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:71)
	at coursier.cli.setup.MaybeInstallApps.$anonfun$task$3(MaybeInstallApps.scala:22)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$delay$2(Task.scala:47)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

OS: Ubuntu 20.04

```bash
uname -a
Linux 5.15.0-84-generic #93~20.04.1-Ubuntu SMP Wed Sep 6 16:15:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

cs version 2.1.7

```
./cs version
2.1.7
```

**Comment by julienrf** [comment]
Thank you for the report, I think we should reopen the issue then.

**Comment by xieyuheng** [comment]
Same problem here.

```
❯ cs version
2.1.7
```

```
❯ cs setup
Checking if a JVM is installed
Found a JVM installed under /usr/lib/jvm/java-21-openjdk-amd64.

Checking if ~/.local/share/coursier/bin is in PATH

Checking if the standard Scala applications are installed
  Found ammonite
  Found cs
  Found coursier
  Found scala
  Found scalac
Exception in thread "main" java.io.EOFException: Unexpected end of ZLIB input stream
    at java.base@17.0.5/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
    at java.base@17.0.5/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
    at java.base@17.0.5/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
    at java.base@17.0.5/java.io.FilterInputStream.read(FilterInputStream.java:106)
    at coursier.install.InstallDir$.coursier$install$InstallDir$$writeTo(InstallDir.scala:615)
    at coursier.install.InstallDir.$anonfun$createOrUpdate$18(InstallDir.scala:354)
    at coursier.install.InstallDir.$anonfun$createOrUpdate$18$adapted(InstallDir.scala:353)
    at coursier.install.internal.ArchiveUtil$.withGzipContent(ArchiveUtil.scala:98)
    at coursier.install.InstallDir.$anonfun$createOrUpdate$14(InstallDir.scala:353)
    at coursier.install.InstallDir.$anonfun$createOrUpdate$14$adapted(InstallDir.scala:302)
    at coursier.install.InstallDir.$anonfun$createOrUpdate$22(InstallDir.scala:408)
    at coursier.install.InstallDir.$anonfun$createOrUpdate$22$adapted(InstallDir.scala:407)
    at coursier.install.Updatable$.get$1(Updatable.scala:61)
    at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:106)
    at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:73)
    at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:93)
    at coursier.install.Updatable$.writing(Updatable.scala:106)
    at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:407)
    at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:96)
    at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:71)
    at coursier.cli.setup.MaybeInstallApps.$anonfun$task$3(MaybeInstallApps.scala:22)
    at coursier.util.Task$.wrap(Task.scala:82)
    at coursier.util.Task$.$anonfun$delay$2(Task.scala:47)
    at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
    at scala.util.Success.$anonfun$map$1(Try.scala:255)
    at scala.util.Success.map(Try.scala:213)
    at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
    at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
    at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
    at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
    at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
    at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

My system:

```
❯ neofetch
       _,met$$$$$gg.          xyh@cicada
    ,g$$$$$$$$$$$$$$$P.       ----------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux trixie/sid x86_64
 ,$$P'              `$$$.     Host: EUL-WX9 M1080
',$$P       ,ggs.     `$$b:   Kernel: 6.5.0-1-amd64
`d$$'     ,$P"'   .    $$$    Uptime: 7 hours, 8 mins
 $$P      d$'     ,    $$P    Packages: 3124 (dpkg), 47 (nix-user)
 $$:      $$.   -    ,d$$'    Shell: fish 3.6.1
 $$;      Y$b._   _,d$P'      Resolution: 3000x2000
 Y$$.    `.`"Y$$$$P"'         DE: xinitrc
 `$$b      "-.__              WM: i3
  `Y$$                        Theme: Breeze [GTK3]
   `Y$$.                      Icons: breeze [GTK3]
     `$$b.                    Terminal: alacritty
       `Y$$b.                 Terminal Font: Monaco
          `"Y$b._             CPU: Intel i7-10510U (8) @ 4.900GHz
              `"""            GPU: Intel CometLake-U GT2 [UHD Graphics]
                              Memory: 7023MiB / 15729MiB
```

**Comment by xieyuheng** [comment]
A workaround seems to remove be `~/.cache/coursier` and run `cs setup` again.

**Comment by xieyuheng** [comment]
In a slow connection far from the source (eastern asia),
maybe restarting `cs setup` will put the cache into partial state,
and causing the error about unzip.

(I hope `cs setup` can have some source mirrors in asia.)

**Comment by simlei** [comment]
Great advice, thanks for posting!

**Comment by xieyuheng** [comment]
It seems coursier is fetching from multiple third-party sources:

```
 /repo1.maven.org
 /github.com
 /repo.typesafe.com
```

There is little hope to setup mirrors for them all.

**Comment by axmrnv** [comment]
I'm experiencing the same issue, and it's very frustrating. I've tried `rm -Rf ~/.cache/coursier`, but it the issue is still there. I'm following the [instructions](https://www.scala-lang.org/download/) from scala-lang.org. The [step-by-step guide](https://get-coursier.io/docs/cli-installation#macos) from get-coursier.io yields the same result.

I've tried running cs setup with temurin-25 and temurin-21. I even tried to delete JVMs from my machine and run `cs setup`. It dowloaded version 11 and then failed with the same issue.

I don't think the issue is caused by some network connectivity problems.

```
> curl -fL https://github.com/coursier/coursier/releases/latest/download/cs-aarch64-apple-darwin.gz | gzip -d > cs && chmod +x cs && (xattr -d com.apple.quarantine cs || true) && ./cs setup
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 21.3M  100 21.3M    0     0  8220k      0  0:00:02  0:00:02 --:--:-- 10.8M
xattr: cs: No such xattr: com.apple.quarantine
Checking if a JVM is installed
Found a JVM installed under /Library/Java/JavaVirtualMachines/temurin-25.jdk/Contents/Home.

Checking if ~/Library/Application Support/Coursier/bin is in PATH

Checking if the standard Scala applications are installed
  Found ammonite
Exception in thread "main" java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base@17.0.9/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
	at java.base@17.0.9/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.base@17.0.9/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
	at java.base@17.0.9/java.io.FilterInputStream.read(FilterInputStream.java:106)
	at coursier.install.InstallDir$.coursier$install$InstallDir$$writeTo(InstallDir.scala:615)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$18(InstallDir.scala:354)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$18$adapted(InstallDir.scala:353)
	at coursier.install.internal.ArchiveUtil$.withGzipContent(ArchiveUtil.scala:104)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$14(InstallDir.scala:353)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$14$adapted(InstallDir.scala:302)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$22(InstallDir.scala:408)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$22$adapted(InstallDir.scala:407)
	at coursier.install.Updatable$.get$1(Updatable.scala:61)
	at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:106)
	at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:94)
	at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:117)
	at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:39)
	at coursier.install.Updatable$.writing(Updatable.scala:106)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:407)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:96)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:71)
	at coursier.cli.setup.MaybeInstallApps.$anonfun$task$3(MaybeInstallApps.scala:22)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$delay$2(Task.scala:47)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.9/java.lang.Thread.run(Thread.java:840)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
```
