### ISSUE TITLE
NullPointerException in createErrFileBlocking

### ISSUE THREAD

**Issue by eed3si9n** [coursier/coursier#2581]
## steps

bazel-multiversion resolves 1000+ dependencies in parallel. This used to work ok for Coursier 2.0.0

## problem

I tried to upgrade to the latest, and I am hitting NullPointerException:

```scala
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:221)
	at java.nio.file.Files.write(Files.java:3422)
	at coursier.cache.internal.Downloader.createErrFileBlocking$1(Downloader.scala:529)
	at coursier.cache.internal.Downloader.$anonfun$remoteKeepErrors$2(Downloader.scala:540)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

## expectations

No errors. 

## notes

I wonder if there are multiple threads trying to write to the same file. If this is for caching purpose, could we ignore the error?

**Comment by alexarchambault** [comment]
Looking at the [`Files.write` sources](https://github.com/adoptium/jdk8u/blob/ae6d30dba462ee53eb89999b7b24a72693737c03/jdk/src/share/classes/java/nio/file/Files.java#L3290), it seems the `requireNonNull` is about the second argument (the bytes to be written), which [here](https://github.com/coursier/coursier/blob/290cf99fea1b592b16b9bd53e8d22ccab0fd26c0/modules/cache/jvm/src/main/scala/coursier/cache/internal/Downloader.scala#L529), corresponds to `scala.Array.emptyByteArray`.

**Comment by alexarchambault** [comment]
I'm not sure how `scala.Array.emptyByteArray` can be null… That might be a native image issue 🤔

**Comment by alexarchambault** [comment]
We can always inline the `emptyByteArray` definition, hoping it won't run into similar errors down-the-line…

**Comment by eed3si9n** [comment]
> That might be a native image issue

Interesting. And yes, bazel-multiversion uses GraalVM Native Image. Let me try updating the toolchain to see if that would make any difference.

**Comment by eed3si9n** [comment]
Another thing to note is that this error only happened on Linux, but was ok on macOS. Upgrading to GraalVM 22.0 seems to have fixed the issue. Thanks for the hint.
