### ISSUE TITLE
Unable to install bloop 1.5.6 on mac

### ISSUE THREAD

**Issue by ashwinbhaskar** [coursier/coursier#2650]
```
coursier version: 2.1.0-RC4
java version: openjdk 11.0.12 2021-07-20
```

Command `brew install scalacenter/bloop/bloop` gives
```
Exception in thread "main" java.lang.Exception: Error while getting https://github.com/coursier/jvm-index/raw/master/index.json: download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://github.com/coursier/jvm-index/raw/master/index.json
    at coursier.jvm.JvmIndex$.$anonfun$load$5(JvmIndex.scala:142)
    at coursier.jvm.JvmIndex$.$anonfun$load$5$adapted(JvmIndex.scala:140)
    at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
    at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
    at coursier.util.Task$.wrap(Task.scala:82)
    at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
    at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
    at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
```

Command `coursier install bloop` gives
```
https://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
  No new update since 2022-12-21 18:35:06
https://repo1.maven.org/maven2/org/scala-lang/scala-library/maven-metadata.xml
  No new update since 2022-10-08 23:59:56
https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/maven-metadata.xml
  100.0% [##########] 29.1 KiB (81.3 KiB / s)
https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.13/maven-metadata.xml
  No new update since 2022-12-22 22:00:47
https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.13/maven-metadata.xml
  No new update since 2022-12-22 22:00:47
https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/maven-metadata.xml
  No new update since 2023-01-04 09:54:46
https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.13/maven-metadata.xml
  No new update since 2022-12-22 22:00:47
Exception in thread "main" coursier.jvm.JvmCache$JvmNotFoundInIndex: JVM graalvm:19.3 not found in index: JVM graalvm not found
    at coursier.jvm.JvmCache.$anonfun$getIfInstalled$1(JvmCache.scala:35)
    at coursier.jvm.JvmCache.$anonfun$getIfInstalled$1$adapted(JvmCache.scala:34)
    at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
```

Command `coursier install --graalvm-default-version=22.1 bloop` gives
```
ttps://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
  No new update since 2022-12-21 18:35:06
https://repo1.maven.org/maven2/org/scala-lang/scala-library/maven-metadata.xml
  No new update since 2022-10-08 23:59:56
https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/maven-metadata.xml
  No new update since 2023-01-04 09:54:46
https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.13/maven-metadata.xml
  No new update since 2022-12-22 22:00:47
https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.13/maven-metadata.xml
  No new update since 2022-12-22 22:00:47
https://repo1.maven.org/maven2/org/scala-lang/scala-library/maven-metadata.xml
  No new update since 2022-10-08 23:59:56
https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/maven-metadata.xml
  No new update since 2023-01-04 09:54:46
https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.13/maven-metadata.xml
  No new update since 2022-12-22 22:00:47
Exception in thread "main" coursier.jvm.JvmCache$JvmNotFoundInIndex: JVM graalvm:22.1 not found in index: JVM graalvm not found
    at coursier.jvm.JvmCache.$anonfun$getIfInstalled$1(JvmCache.scala:35)
    at coursier.jvm.JvmCache.$anonfun$getIfInstalled$1$adapted(JvmCache.scala:34)
    at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
    at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
```

**Comment by ashwinbhaskar** [comment]
@ckipp01 sorry missed this. Yes I have an M1

**Comment by ckipp01** [comment]
> @ckipp01 sorry missed this. Yes I have an M1

Gotcha, I believe https://github.com/coursier/coursier/pull/2652 will fix this for you.

**Comment by ashwinbhaskar** [comment]
@ckipp01 thank you, would `coursier update && coursier install bloop` after the release get me the latest bloop server?

**Comment by davesmith00000** [comment]
It's slow (I guess it's using the JVM version?), but as a workaround while we wait for a real version, you can run bloop on M1 via coursier, e.g.:

`cs launch bloop -- about`

I have an alias set up to point at that called `blp` so that I can do `blp compile <project>` and so on.

**Comment by SethTisue** [comment]
Is this still reproducible? I can't currently reproduce it on my M1 Mac. I think it might be fixed? Dare we hope?
