### ISSUE TITLE
Assertion failed when listing installed jdks

### ISSUE THREAD

**Issue by mtomko** [coursier/coursier#2696]
Running:

```shell
$ cs java --installed
```

Getting:

```
Exception in thread "main" java.util.concurrent.ExecutionException: Boxed Error
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:87)
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
Caused by: java.lang.AssertionError: assertion failed: Attempts to download https://github.com/coursier/jvm-index/raw/master/index.json twice in parallel
	at scala.Predef$.assert(Predef.scala:223)
	at coursier.cache.loggers.RefreshLogger$UpdateDisplayRunnable.newEntry(RefreshLogger.scala:132)
	at coursier.cache.loggers.RefreshLogger.downloadingArtifact(RefreshLogger.scala:306)
	at coursier.cache.internal.Downloader$Blocking$.remote(Downloader.scala:400)
	at coursier.cache.internal.Downloader.$anonfun$remote$6(Downloader.scala:518)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	... 7 more
```

```shell
$ cs version
2.1.0-RC2
$ uname -a
Darwin mbp14.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64
```

If it's any help, before that error, it prints 
```
https://github.com/coursier/jvm-index/raw/master/index.json
  No modified time in response
``` 
many, many times in a row.

**Comment by mtomko** [comment]
I can try and peek a little closer at the source tonight.
