### ISSUE TITLE
error installing stbn in windows

### ISSUE THREAD

**Issue by philwalk** [coursier/coursier#2700]
My system is Windows 10, running in an Msys64 bash session:
```
MINGW64_NT-10.0-19044 d5 3.4.5.x86_64 2023-01-20 09:17 UTC x86_64 Msys
```

Coursier is:
```
cs.exe --version
2.0.13
```

The failed command is:
```bash
cs install --contrib sbtn
Exception in thread "main" java.util.NoSuchElementException: sbt/bin/sbtn-x86_64-pc-win32.exe.exe not found
(details are below)
```

The error seems to be that an extra `.exe` is appended to a file that already has that extension, resulting in the wrong filename (extension is **_.exe.exe_**)

Not sure if this is a coursier error, the downloaded sbt-1.8.2.zip file contents look okay:

```bash
jar -tf C:/Users/philwalk/AppData/Local/Coursier/cache/v1/https/github.com/sbt/sbt/releases/download/v1.8.2/sbt-1.8.2.zip
sbt/conf/sbtconfig.txt
sbt/conf/sbtopts
sbt/bin/sbt.bat
sbt/bin/sbt
sbt/bin/sbt-launch.jar
sbt/bin/sbtn-x86_64-apple-darwin
sbt/bin/sbtn-x86_64-pc-linux
sbt/bin/sbtn-aarch64-pc-linux
sbt/bin/sbtn-x86_64-pc-win32.exe
sbt/LICENSE
sbt/NOTICE
```

<details>
# cs install --contrib sbtn
Exception in thread "main" java.util.NoSuchElementException: sbt/bin/sbtn-x86_64-pc-win32.exe.exe not found in C:\Users\philwalk\AppData\Local\Coursier\cache\v1\https\github.com\sbt\sbt\releases\download\v1.8.2\sbt-1.8.2.zip
        at coursier.install.InstallDir$.$anonfun$withFileInZip$1(InstallDir.scala:803)
        at scala.Option.getOrElse(Option.scala:189)
        at coursier.install.InstallDir$.coursier$install$InstallDir$$withFileInZip(InstallDir.scala:803)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$14(InstallDir.scala:353)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$14$adapted(InstallDir.scala:299)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$21(InstallDir.scala:385)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$21$adapted(InstallDir.scala:384)
        at coursier.install.Updatable$.get$1(Updatable.scala:55)
        at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:96)
        at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:72)
        at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:98)
        at coursier.install.Updatable$.writing(Updatable.scala:96)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:384)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:87)
        at coursier.cli.install.Install$.$anonfun$run$7(Install.scala:108)
        at coursier.cli.install.Install$.$anonfun$run$7$adapted(Install.scala:95)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at coursier.cli.install.Install$.run(Install.scala:95)
        at coursier.cli.Coursier$.$anonfun$runA$2(Coursier.scala:151)
        at coursier.cli.Coursier$.$anonfun$runA$2$adapted(Coursier.scala:139)
        at coursier.cli.CommandAppPreA.run(CommandAppPreA.scala:22)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5(CommandAppWithPreCommand.scala:99)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5$adapted(CommandAppWithPreCommand.scala:99)
        at scala.util.Either.fold(Either.scala:191)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3(CommandAppWithPreCommand.scala:99)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3$adapted(CommandAppWithPreCommand.scala:85)
        at scala.Option.foreach(Option.scala:407)
        at caseapp.core.app.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:85)
        at coursier.cli.Coursier$.main(Coursier.scala:104)
        at coursier.cli.Coursier.main(Coursier.scala)

philwalk@d5 MINGW64 ~/workspace/scala-native-philwalk-2023
#
</details>

**Comment by adpi2** [comment]
This bug should be fixed in the latest `2.1.0-RC6` version of Coursier. Could you uninstall coursier, install the latest version and try again?

**Comment by philwalk** [comment]
After installing 2.1.0-RC6, the command line "succeeds" in the sense that it doesn't report any errors.
(although the new install includes `sbtn`, and it would have to first be uninstalled in order to do a comparable test).

It seems the file `cs.exe` provided in previous versions has been renamed to `.cs.aux.exe`, is that correct?
