### ISSUE TITLE
Running cs setup caused an exception 

### ISSUE THREAD

**Issue by yacinehechmi** [coursier/coursier#2787]
by running `./cs setup` on a linux x86_64 got

`Exception in thread "main" java.lang.Exception: Reading /home/yacine/.local/share/coursier/bin/sbt
        at coursier.install.InfoFile$.liftedTree1$1(InfoFile.scala:186)
        at coursier.install.InfoFile$.upToDate(InfoFile.scala:154)
        at coursier.install.InstallDir.upToDate$lzycompute$1(InstallDir.scala:312)
        at coursier.install.InstallDir.upToDate$1(InstallDir.scala:307)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$14(InstallDir.scala:315)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$14$adapted(InstallDir.scala:302)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$22(InstallDir.scala:408)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$22$adapted(InstallDir.scala:407)
        at coursier.install.Updatable$.get$1(Updatable.scala:61)
        at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:106)
        at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:73)
        at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:93)
        at coursier.install.Updatable$.writing(Updatable.scala:106)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:407)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:96)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:71)
        at coursier.cli.setup.MaybeInstallApps.$anonfun$task$3(MaybeInstallApps.scala:22)
        at coursier.util.Task$.wrap(Task.scala:82)
        at coursier.util.Task$.$anonfun$delay$2(Task.scala:47)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)`

**Comment by yacinehechmi** [comment]
removing `.cache/coursier`, `.local/share/coursier` and rerunning `./cs setup` fixed the problem
