### ISSUE TITLE
fetch hangs indefinitely with 100% CPU

### ISSUE THREAD

**Issue by tirsen** [coursier/coursier#2831]
Looks like an endless recursion probably caused by a faulty internal dependency.

```
jstack <pid>

"main" #1 prio=5 os_prio=31 cpu=591.86ms elapsed=245.20s tid=0x000000013b809e00 nid=0x2303 waiting on condition  [0x000000016bc2d000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.8/Native Method)
	- parking to wait for  <0x0000000400c82800> (a scala.concurrent.impl.Promise$CompletionLatch)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.8/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.8/AbstractQueuedSynchronizer.java:715)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@17.0.8/AbstractQueuedSynchronizer.java:1047)
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:242)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:258)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:223)
	at scala.concurrent.Await$$$Lambda$1030/0x000000080034ef00.apply(Unknown Source)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.Await$.result(package.scala:146)
	at coursier.util.PlatformTaskCompanion$PlatformTaskOps.unsafeRun(PlatformTaskCompanion.scala:43)
	at coursier.cli.fetch.Fetch$.run(Fetch.scala:116)
	at coursier.cli.fetch.Fetch$.run(Fetch.scala:18)
	at caseapp.core.app.CaseApp.main(CaseApp.scala:150)
	at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:115)
	at coursier.cli.Coursier$.main(Coursier.scala:118)
	at coursier.cli.Coursier.main(Coursier.scala)

...snip...

"coursier-pool-1-thread-5" #18 daemon prio=5 os_prio=31 cpu=145390.81ms elapsed=244.57s tid=0x000000013b156600 nid=0x8503 runnable  [0x00000002a81ff000]
   java.lang.Thread.State: RUNNABLE
	at scala.runtime.Statics.anyHash(Statics.java:122)
	at scala.util.hashing.MurmurHash3.productHash(MurmurHash3.scala:76)
	at scala.util.hashing.MurmurHash3$.productHash(MurmurHash3.scala:246)
	at scala.runtime.ScalaRunTime$._hashCode(ScalaRunTime.scala:167)
	at scala.Tuple3.hashCode(Tuple3.scala:25)
	at scala.runtime.Statics.anyHash(Statics.java:122)
	at scala.util.hashing.MurmurHash3$hasher$2.apply(MurmurHash3.scala:140)
	at scala.util.hashing.MurmurHash3$hasher$2.apply(MurmurHash3.scala:136)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.util.hashing.MurmurHash3.orderedHash(MurmurHash3.scala:145)
	at scala.util.hashing.MurmurHash3$.seqHash(MurmurHash3.scala:257)
	at scala.collection.IndexedSeqLike.hashCode(IndexedSeqLike.scala:44)
	at scala.collection.IndexedSeqLike.hashCode$(IndexedSeqLike.scala:44)
	at scala.collection.immutable.Vector.hashCode(Vector.scala:69)
	at scala.runtime.Statics.anyHash(Statics.java:122)
	at scala.util.hashing.MurmurHash3.product2Hash(MurmurHash3.scala:60)
	at scala.util.hashing.MurmurHash3$.product2Hash(MurmurHash3.scala:245)
	at scala.collection.immutable.Map$HashCodeAccumulator.apply(Map.scala:558)
	at scala.collection.immutable.Map$HashCodeAccumulator.apply(Map.scala:553)
	at scala.collection.immutable.HashMap$HashMap1.foreachEntry(HashMap.scala:401)
	at scala.collection.immutable.HashMap$HashTrieMap.foreachEntry(HashMap.scala:735)
	at scala.collection.immutable.HashMap$HashTrieMap.foreachEntry(HashMap.scala:735)
	at scala.collection.immutable.HashMap.hashCode(HashMap.scala:64)
	at scala.runtime.Statics.anyHash(Statics.java:122)
	at coursier.graph.ReverseModuleTree$Node.hashCode(ReverseModuleTree.scala:173)
	at scala.runtime.Statics.anyHash(Statics.java:122)
	at scala.collection.immutable.HashSet.elemHashCode(HashSet.scala:186)
	at scala.collection.immutable.HashSet.computeHash(HashSet.scala:195)
	at scala.collection.immutable.HashSet.$plus(HashSet.scala:86)
	at scala.collection.immutable.HashSet.$plus(HashSet.scala:37)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.$anonfun$customRender$3(Tree.scala:49)
	at coursier.util.Tree.$anonfun$customRender$3$adapted(Tree.scala:43)
	at coursier.util.Tree$$Lambda$1995/0x00000008005c3108.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at coursier.util.Tree.recursivePrint$1(Tree.scala:43)
	at coursier.util.Tree.customRender(Tree.scala:58)
	at coursier.error.ResolutionError$.$anonfun$conflictingDependenciesErrorMessage$3(ResolutionError.scala:59)
	at coursier.error.ResolutionError$$$Lambda$1983/0x00000008005bf528.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.TraversableLike$$Lambda$841/0x00000008002c69e0.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at coursier.error.ResolutionError$.coursier$error$ResolutionError$$conflictingDependenciesErrorMessage(ResolutionError.scala:56)
	at coursier.error.ResolutionError$ConflictingDependencies.<init>(ResolutionError.scala:109)
	at coursier.Resolve$.validate(Resolve.scala:382)
	at coursier.Resolve.validate0$1(Resolve.scala:137)
	at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:187)
	at coursier.Resolve$$Lambda$1146/0x0000000800384998.apply(Unknown Source)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$$$Lambda$1029/0x000000080034ea28.apply(Unknown Source)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at coursier.util.Task$$$Lambda$1025/0x000000080034d890.apply(Unknown Source)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.Future$$Lambda$1026/0x000000080034de88.apply(Unknown Source)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.Promise$$Lambda$1027/0x000000080034e268.apply(Unknown Source)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.8/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.8/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.8/Thread.java:833)
```

**Comment by tirsen** [comment]
Looks like there is cycle detection though...
https://github.com/coursier/coursier/blob/26719841df0732dca511c93f1c31959ef2e32986/modules/core/shared/src/main/scala/coursier/util/Tree.scala#L41

**Comment by tirsen** [comment]
If I print out the `elem` variable it's clear that there is a cycle and that the cycle detection does not prevent an infinite loop here.

**Comment by eed3si9n** [comment]
(Not that I am a maintainer of Coursier) thanks for the reporting this issue. Do you have some repro steps so this can be tested on CI?
