### ISSUE TITLE
cannot install:  Can't find a scala version suffix 

### ISSUE THREAD

**Issue by gogamid** [coursier/coursier#2832]
I have been stuck to setup coursier for corporate laptop. I am using mirror.properties. 
I get this error  when i run `coursier install metals`:
```
https://jfrog.[mycompany.com]/artifactory/public/io/get-coursier/apps/maven-metadata.xml
  No new update since 2023-08-16 16:52:10
Exception in thread "main" java.lang.Exception: coursier.install.AppArtifacts$ScalaDependenciesNotFound: Can't find a scala version suffix for org.scalameta::metals:latest.stable (likely a non existing module or version)
        at coursier.install.AppDescriptor.artifacts(AppDescriptor.scala:109)
        at coursier.install.InstallDir.update$1(InstallDir.scala:262)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$22(InstallDir.scala:408)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$22$adapted(InstallDir.scala:407)
        at coursier.install.Updatable$.get$1(Updatable.scala:61)
        at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:106)
        at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:73)
        at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:93)
        at coursier.install.Updatable$.writing(Updatable.scala:106)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:407)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:96)
        at coursier.cli.install.Install$.$anonfun$run$7(Install.scala:128)
        at coursier.cli.install.Install$.$anonfun$run$7$adapted(Install.scala:115)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at coursier.cli.install.Install$.run(Install.scala:115)
        at coursier.cli.install.Install$.run(Install.scala:23)
        at caseapp.core.app.CaseApp.main(CaseApp.scala:150)
        at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:115)
        at coursier.cli.Coursier$.main(Coursier.scala:118)
        at coursier.cli.Coursier.main(Coursier.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at coursier.bootstrap.launcher.a.a(Unknown Source)
        at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
Caused by: coursier.install.AppArtifacts$ScalaDependenciesNotFound: Can't find a scala version suffix for org.scalameta::metals:latest.stable (likely a non existing module or version)
        at coursier.install.AppDescriptor.$anonfun$processDependencies$9(AppDescriptor.scala:231)
        at scala.Option.toRight(Option.scala:485)
        at coursier.install.AppDescriptor.processDependencies(AppDescriptor.scala:231)
        at coursier.install.AppDescriptor.artifacts(AppDescriptor.scala:107)
        ... 25 more
```
weirdly `coursier bootstrap/resolve/fetch` works :(

**Comment by tgodzik** [comment]
Thanks for reporting! Does it work when you do `coursier install metals:1.0.1` ? Alternatively, bootstrap command should be enough.

**Comment by gogamid** [comment]
@tgodzik  same  with this command `coursier install metals:1.0.1`
this happens also in the part of `coursier setup`, i dont really know how to run setup with bootstrap...

**Comment by tgodzik** [comment]
Hmm... maybe:
`coursier install org.scalameta:metals_2.13:1.0.1`
would work?

I think there might be some additional files we use on maven central and that doesn't work on corporate repositories?

**Comment by tgodzik** [comment]
Ach no, your best case is to do `coursier bootstrap -o metals org.scalameta:metals_2.13:1.0.1`

**Comment by gogamid** [comment]
running ` coursier install org.scalameta:metals_2.13:1.0.1` gives me this time:
```Cannot find app org.scalameta in channels io.get-coursier:apps```

**Comment by gogamid** [comment]
as i said, `coursier bootstrap/resolve/fetch metals` works somehow, but `install` and  `setup` doesnt't work

**Comment by dhpiggott** [comment]
Adding a source-level diagnosis, since this still bites and the error message actively misleads. All line references are at tag `v2.1.25-M26` (`fab45036b434f36b25d7907e3c732168aff1e5ea`).

### Why `resolve`/`fetch`/`bootstrap` work but `install` doesn't

`Mirror.replace` has exactly **two** call sites in the whole repo, both inside a `finalRepositories`:

- [`Resolve.scala#L94-L104`](https://github.com/coursier/coursier/blob/fab45036b434f36b25d7907e3c732168aff1e5ea/modules/coursier/shared/src/main/scala/coursier/Resolve.scala#L94-L104)
- [`Versions.scala#L47-L48`](https://github.com/coursier/coursier/blob/fab45036b434f36b25d7907e3c732168aff1e5ea/modules/coursier/shared/src/main/scala/coursier/Versions.scala#L47-L48)

`fetch` inherits mirrors only because it wraps a `Resolve`. Meanwhile `modules/install/src/main` contains **zero** occurrences of `Mirror`. That asymmetry is the bug in one line — and it's visible *within* a single file: the app's real artifact fetch uses `Fetch()` (mirrors apply), but the scala-suffix discovery goes straight at the raw repositories:

- [`AppDescriptor.scala#L464-L465`](https://github.com/coursier/coursier/blob/fab45036b434f36b25d7907e3c732168aff1e5ea/modules/install/src/main/scala/coursier/install/AppDescriptor.scala#L464-L465) — `listVersions(cache, repositories, mod"org.scala-lang:scala-library")`
- [`AppDescriptor.scala#L482-L483`](https://github.com/coursier/coursier/blob/fab45036b434f36b25d7907e3c732168aff1e5ea/modules/install/src/main/scala/coursier/install/AppDescriptor.scala#L482-L483) — `coursier.complete.Complete(cache).withRepositories(repositories)`

`Complete` has no mirror field at all, and `listVersions` calls `repo.versions(...)` per repository directly.

### Why the error says "Can't find a scala version suffix" instead of "couldn't reach repo1"

This is the part worth fixing regardless of the mirror question. `listVersions` swallows every per-repository failure:

```scala
// AppDescriptor.scala#L549-L552
t.unsafeRun(wrapExceptions = true)(cache.ec) match {
  case Left(err) =>
    // FIXME Trapped error
    Set.empty
```

So "repo1 is blocked / rate-limited / unreachable in this environment" becomes an empty version set, which surfaces as `ScalaDependenciesNotFound: ... (likely a non existing module or version)`. That's why this thread went hunting for a missing artifact — the module exists fine; the network call was dropped on the floor.

### Why setting a mirror or `COURSIER_REPOSITORIES` doesn't rescue it

Even with the suffix-discovery path fixed, app descriptors pin their own repositories:

- Stock descriptors declare `"repositories": ["central"]`.
- `"central"` maps to a **hardcoded** URL — [`SharedRepositoryParser.scala#L10-L14`](https://github.com/coursier/coursier/blob/fab45036b434f36b25d7907e3c732168aff1e5ea/modules/coursier/shared/src/main/scala/coursier/internal/SharedRepositoryParser.scala#L10-L14) → [`Repositories.scala#L7-L13`](https://github.com/coursier/coursier/blob/fab45036b434f36b25d7907e3c732168aff1e5ea/modules/coursier/shared/src/main/scala/coursier/Repositories.scala#L7-L13) `MavenRepository("https://repo1.maven.org/maven2")`. (Note bare `central` is repo1; the `central:<name>` form is `central.sonatype.com`.)
- Those parsed repositories go into a fresh `AppDescriptor().withRepositories(...)`, so they **replace** the user's CLI/env repositories rather than adding to them (`RawAppDescriptor`).
- And a descriptor has no way to defer to the user's configuration: the single-argument `RepositoryParser.repositories` used on this path passes `defaultRepositoriesOpt = None`, making the `"default"` branch unreachable — the scaladoc says as much.

Coursier already flags this itself: `// FIXME Get raw repositories from or along with params.repositories` at `Channels.scala:73`.

### The ask

Could mirrors — and more generally the user's repository configuration — be honoured for repositories named in app descriptors, not just on the `Resolve`/`Fetch` path? Concretely, any of:

1. Route the app-install repositories through the same `finalRepositories`/`Mirror.replace` pipeline (this alone fixes the common case, since a mirror of `repo1` is exactly what these environments configure).
2. Make a descriptor's `repositories` **additive**, or let it opt into the user's configured repositories (i.e. make `"default"` reachable there).
3. Independently of the above: stop trapping the error at `AppDescriptor.scala#L549-L552`, so an unreachable repository reports itself instead of masquerading as a missing artifact.

(1) and (3) would together turn this from "inexplicable missing-artifact error" into "works, or tells you why not".

### A real-world example of it breaking a tool

[`scala-steward-org/scala-steward-action#837 (comment)`](https://github.com/scala-steward-org/scala-steward-action/pull/837#issuecomment-5118134168) — a GitHub Action that installs its tooling with `cs install` is unusable on CI whose egress is rate-limited by Maven Central, for exactly this reason. The maintainers' fix is to abandon `cs install` in favour of `cs bootstrap` with explicit coordinates (which, as this thread found in 2023, is the working escape hatch) — though that swap has its own side-effects, since the `sbt` app descriptor is archive-based and gives you the real `sbt` launcher script, while a bootstrap launcher doesn't.

### Workaround, for anyone landing here

You can override the descriptors rather than patching the tool. Put a JSON file per app in a directory, with explicit coordinates (avoiding `::` suffix discovery entirely) and your own repository:

```json
{
  "repositories": [ "https://your-mirror.example/maven/" ],
  "dependencies": [ "org.scalameta:scalafmt-cli_2.13:3.11.5" ],
  "mainClass": "org.scalafmt.cli.Cli"
}
```

then `cs channel --add /path/to/dir`. Custom channels sort ahead of `io.get-coursier:apps` and the first match wins, so plain `cs install <app>` picks yours up with no other changes.

Two caveats learned the hard way: include **every** app you install, because any app still coming from the default channel brings its `"repositories": ["central"]` back with it; and for archive-based apps (`sbt`, `scala-cli`) copy the stock descriptor's `prebuilt`/`prebuiltBinaries` fields, so you keep the real launcher rather than a JVM bootstrap.

*(Written by Claude on David's behalf.)*
