### ISSUE TITLE
Can't install Scala 2 tools: ResolutionError for `cs install scaladoc:2.13.12` 

### ISSUE THREAD

**Issue by lefou** [coursier/coursier#2846]
```
$ cs install scaladoc:2.13.12
Exception in thread "main" coursier.error.ResolutionError$CantDownloadModule: Error downloading org.scala-lang:scaladoc_3:2.13.12
  not found: https://repo1.maven.org/maven2/org/scala-lang/scaladoc_3/2.13.12/scaladoc_3-2.13.12.pom
        at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:329)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:285)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at coursier.Resolve$.validate(Resolve.scala:327)
        at coursier.Resolve.validate0$1(Resolve.scala:115)
        at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:161)
        at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
        at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
        at coursier.util.Task$.wrap(Task.scala:84)
        at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

**Comment by tgodzik** [comment]
Looks like the version range is not working properly https://github.com/coursier/apps/blob/main/apps/resources/scaladoc.json#L14 :thinking:

**Comment by adpi2** [comment]
I tried locally and it worked:
```
> cs install scaladoc:2.13.12
https://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
  No new update since 2023-08-16 16:52:10
https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.12/scala-comp…
  100.0% [##########] 2.5 KiB (43.3 KiB / s)
https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.12/scala-refle…
  100.0% [##########] 1.8 KiB (45.9 KiB / s)
https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.12/scala-refle…
  100.0% [##########] 3.6 MiB (2.1 MiB / s)
https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.12/scala-libra…
  100.0% [##########] 5.6 MiB (1.9 MiB / s)
https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.12/scala-comp…
  100.0% [##########] 11.6 MiB (3.3 MiB / s)
Wrote scaladoc
```

```
> cs version
2.1.7
```

Which version of Coursier do you use?

**Comment by lefou** [comment]
```
$ cs version
Command not found: version
$ cs --version
2.0.16
$ cs update cs
https://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.13/maven-metadata.xml
  No new update since 2023-09-09 17:46:29
Error downloading gz+https://github.com/coursier/coursier/releases/download/v2.1.7/cs-x86_64-pc-linux.gz
```

Probably a too old version, which isn't even able to update itself. I'll re-install manually.

**Comment by lefou** [comment]
With cs 2.1.7 this issue is fixed.

**Comment by adpi2** [comment]
Here is the issue and workaround about coursier that cannot update itself: https://github.com/coursier/coursier/issues/2362
