### ISSUE TITLE
 ./cs-x86_64-pc-linux setup error

### ISSUE THREAD

**Issue by yuchunzhou** [coursier/coursier#2855]
```
Exception in thread "main" java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base@17.0.5/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
	at java.base@17.0.5/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.base@17.0.5/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
	at java.base@17.0.5/java.io.FilterInputStream.read(FilterInputStream.java:106)
	at coursier.install.InstallDir$.coursier$install$InstallDir$$writeTo(InstallDir.scala:615)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$18(InstallDir.scala:354)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$18$adapted(InstallDir.scala:353)
	at coursier.install.internal.ArchiveUtil$.withGzipContent(ArchiveUtil.scala:98)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$14(InstallDir.scala:353)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$14$adapted(InstallDir.scala:302)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$22(InstallDir.scala:408)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$22$adapted(InstallDir.scala:407)
	at coursier.install.Updatable$.get$1(Updatable.scala:61)
	at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:106)
	at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:73)
	at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:93)
	at coursier.install.Updatable$.writing(Updatable.scala:106)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:407)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:96)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:71)
	at coursier.cli.setup.MaybeInstallApps.$anonfun$task$3(MaybeInstallApps.scala:22)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$delay$2(Task.scala:47)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

**Comment by yuchunzhou** [comment]
coursier version 2.1.7

**Comment by yuchunzhou** [comment]
$ java --version
openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+35-2513)
OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)
