### ISSUE TITLE
Access Denied on file with .error extension when doing cs setup

### ISSUE THREAD

**Issue by vpinna80** [coursier/coursier#2871]
When doing cs setup on Windows, an AccessDeniedException is thrown with the following text (redacted):

```
$ coursier setup
Checking if a JVM is installed
Found a JVM installed under *******\jdk17.

Checking if ~\AppData\Local\Coursier\data\bin is in PATH

Checking if the standard Scala applications are installed
Exception in thread "main" java.nio.file.AccessDeniedException: ******\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with
-guava\.listenablefuture-9999.0-empty-to-avoid-conflict-with-guava-sources.jar.error
        at java.base@17.0.5/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
        at java.base@17.0.5/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
        at java.base@17.0.5/java.nio.file.Files.newOutputStream(Files.java:228)
        at java.base@17.0.5/java.nio.file.Files.write(Files.java:3512)
        at coursier.cache.internal.Downloader.createErrFileBlocking$1(Downloader.scala:551)
        at coursier.cache.internal.Downloader.$anonfun$remoteKeepErrors$2(Downloader.scala:562)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178)
```

**Comment by kendalldita** [comment]
I encountered the same problem. What I did was use the jar-based installer, first of all. I also dislike the very long paths that windows programs usually use. So, after downloading the jar file:

rem with JDK 1.8 installed
mkdir c:\lib\coursier\bin
mkdir c:\lib\coursier\archive
mkdir c:\lib\coursier\cache
mkdir c:\lib\coursier\jvm
set COURSIER_HOME=c:\lib\coursier
set COURSIER_CACHE=%COURSIER_HOME%\cache
set COURSIER_ARCHIVE_CACHE=%COURSIER_HOME%\archive
set COURSIER_JVM_CACHE=%COURSIER_HOME%\jvm

curl --ssl-no-revoke -fLo %COURSIER_HOME%\bin\coursier.jar  https://github.com/coursier/launchers/raw/master/coursier
rem -y means yes, add c:\lib\coursier\bin to path:
java -jar %COURSIER_HOME%\bin\coursier.jar setup -v -y --cache %COURSIER_CACHE% --dir %COURSIER_HOME%\bin --install-platform x86_64-pc-win32
del %COURSIER_HOME%\bin\cs.bat
del %COURSIER_HOME%\bin\coursier.bat
echo @java -jar %COURSIER_HOME%\bin\coursier.jar %* > %COURSIER_HOME%\bin\cs.cmd

Open a new terminal. Now "cs" invokes c:\lib\coursier\bin\cs.cmd which runs coursier.jar

cs java --available 
cs java-home --jvm adoptium:1.8
cs java-home --jvm adoptium:1.17
cs java-home --jvm corretto:17
cs java-home --jvm adoptium:1.21

Then I create scripts to select the version:

cs java-home --jvm adoptium:1.8 --env > c:\bin\java8.cmd
rem edit removing quotes and replacing "set path" with the "path" command
cs java-home --jvm adoptium:1.17 --env > c:\bin\java17.cmd
etc.
