### ISSUE TITLE
cs update fails

### ISSUE THREAD

**Issue by ironfish** [coursier/coursier#2948]
```
❯ cs update
https://repo1.maven.org/maven2/com/lihaoyi/ammonite_3.3.3/maven-metadata.xml
  No new update since 2024-03-08 15:25:31
https://repo1.maven.org/maven2/com/google/code/gson/gson/maven-metadata.xml
  No new update since 2023-01-06 10:48:35
Exception in thread "main" coursier.error.ResolutionError$CantDownloadModule: Error downloading com.lihaoyi:ammonite-terminal_3:3.0.0-M1-8-35694880
  not found: https://repo1.maven.org/maven2/com/lihaoyi/ammonite-terminal_3/3.0.0-M1-8-35694880/ammonite-terminal_3-3.0.0-M1-8-35694880.pom
	at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:367)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at coursier.Resolve$.validate(Resolve.scala:365)
	at coursier.Resolve.validate0$1(Resolve.scala:137)
	at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:187)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
```

**Comment by adpi2** [comment]
This is probably a timing issue. `ammonite-terminal_3:3.0.0-M1-8-35694880` is now available at https://repo1.maven.org/maven2/com/lihaoyi/ammonite-terminal_3/3.0.0-M1-8-35694880/ammonite-terminal_3-3.0.0-M1-8-35694880.pom.

**Comment by ironfish** [comment]
Thanks, looks like it's working now.
