### ISSUE TITLE
`JvmNotFoundInIndex` while listing installed JVMs (which took 70+ seconds)

### ISSUE THREAD

**Issue by carlosedp** [coursier/coursier#2952]
I'm trying to list the installed JVMs by `cs` but after more than 70 seconds (I'm on a 16`` Intel MBP) it returns:

```
❯ time cs java --installed
Exception in thread "main" coursier.jvm.JvmCache$JvmNotFoundInIndex: JVM graalvm-jdk@oracle:17 not found in index: JVM graalvm-jdk not found
	at coursier.jvm.JvmCache.$anonfun$getIfInstalled$1(JvmCache.scala:35)
	at coursier.jvm.JvmCache.$anonfun$getIfInstalled$1$adapted(JvmCache.scala:34)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
cs java --installed  74.93s user 38.33s system 111% cpu 1:41.30 total
```

I've removed my `$HOME/Library/Application Support/Coursier` and `$HOME/Library/Caches/Coursier` dirs but same happens.

**Comment by carlosedp** [comment]
I look into the index and all references are there and exist:

```
❯ curl -sSL https://github.com/coursier/jvm-index/raw/master/index.json |jq |grep graalvm-jdk
      "graalvm-jdk@oracle": {
        "17": "https://download.oracle.com/graalvm/17/latest/graalvm-jdk-17_macos-x64_bin.tar.gz",
        "21": "https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_macos-x64_bin.tar.gz"
      "graalvm-jdk@oracle": {
        "17": "https://download.oracle.com/graalvm/17/latest/graalvm-jdk-17_macos-aarch64_bin.tar.gz",
        "21": "https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_macos-aarch64_bin.tar.gz"
      "graalvm-jdk@oracle": {
        "17": "https://download.oracle.com/graalvm/17/latest/graalvm-jdk-17_linux-x64_bin.tar.gz",
        "21": "https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_linux-x64_bin.tar.gz"
      "graalvm-jdk@oracle": {
        "17": "https://download.oracle.com/graalvm/17/latest/graalvm-jdk-17_linux-aarch64_bin.tar.gz",
        "21": "https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_linux-aarch64_bin.tar.gz"
      "graalvm-jdk@oracle": {
        "17": "https://download.oracle.com/graalvm/17/latest/graalvm-jdk-17_windows-x64_bin.zip",
        "21": "https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_windows-x64_bin.zip"
```

Is there any constraint regarding the naming.. like having dashes or something like that?

**Comment by carlosedp** [comment]
With the PR sent to the index, I've run the `time cs java --jvm-index ./index.json --installed` command (with my locally generated index).
It ran for about 80 seconds but consumed more than 6GB of RAM.

```
❯ time cs java --jvm-index ./index.json --installed
adoptium:1.17 installed at /Users/cdepaula/Library/Caches/Coursier/arc/https/github.com/adoptium/temurin17-binaries/releases/download/jdk-17%252B35/OpenJDK17-jdk_x64_mac_hotspot_17_35.tar.gz/jdk-17+35/Contents/Home
graalvm-community:21.0.2 installed at /Users/cdepaula/Library/Caches/Coursier/arc/https/github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_macos-x64_bin.tar.gz/graalvm-community-openjdk-21.0.2+13.1/Contents/Home
graalvm-java21:21.0.2 installed at /Users/cdepaula/Library/Caches/Coursier/arc/https/github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_macos-x64_bin.tar.gz/graalvm-community-openjdk-21.0.2+13.1/Contents/Home
graalvm-oracle:21 installed at /Users/cdepaula/Library/Caches/Coursier/arc/https/download.oracle.com/graalvm/21/latest/graalvm-jdk-21_macos-x64_bin.tar.gz/graalvm-jdk-21.0.2+13.1/Contents/Home
temurin:1.17 installed at /Users/cdepaula/Library/Caches/Coursier/arc/https/github.com/adoptium/temurin17-binaries/releases/download/jdk-17%252B35/OpenJDK17-jdk_x64_mac_hotspot_17_35.tar.gz/jdk-17+35/Contents/Home
cs java --jvm-index ./index.json --installed  80.99s user 59.77s system 101% cpu 2:18.75 total
```

**Comment by carlosedp** [comment]
The JVM index have been updated (if doesn't update automatically, run `cs java --available --update --ttl 0` and the `--installed` command after), this issue won't happen anymore except taking a strange amount of time (about 60 seconds on my laptop).

I believe there's another issue reporting this (#2642) so I'm closing this.
