### ISSUE TITLE
`sbt` `scala-cli` `cs` installed by coursier does not work on windows

### ISSUE THREAD

**Issue by harry-xi** [coursier/coursier#2953]
When I try to run the above command, it says
```
This version of C:\Users\HarryXi\AppData\Local\Coursier\data\bin\.sbt.aux.exe is not compatible with the version of Windows you are running. Please check your computer's system information and then contact the software publisher.
```

**Comment by tgodzik** [comment]
Might be that the version of windows is too old? What version are you using?

**Comment by harry-xi** [comment]
> Might be that the version of windows is too old? What version are you using?

I'm using Windows 11 23H2 (22613.3296)

I apologize for forgetting to provide this information in the first place

**Comment by tgodzik** [comment]
According to https://answers.microsoft.com/en-us/windows/forum/all/this-verison-of-this-file-is-not-compatible-with/0c6a4c8e-1416-47a5-b6b4-6d10a82942da it might mean that you have 32bit system and the apps are create for 64 or the other way around. I think the native apps are released for 64 bit systems

**Comment by harry-xi** [comment]
> According to https://answers.microsoft.com/en-us/windows/forum/all/this-verison-of-this-file-is-not-compatible-with/0c6a4c8e-1416-47a5-b6b4-6d10a82942da it might mean that you have 32bit system and the apps are create for 64 or the other way around. I think the native apps are released for 64 bit systems

You should know that win11 doesn't have a 32 bit version

**Comment by tgodzik** [comment]
Hmm... Ok then a pity the error doesn't give us more information. You could try installing Scala CLI via winget, we can confirm whether the error is coursier specific.

https://scala-cli.virtuslab.org/install <- there should be some minimal instruction there

**Comment by harry-xi** [comment]
It's working fine.
In fact the binary version cs downloaded from [coursier's release](https://github.com/coursier/coursier/releases/download/v2.1.9) and the sbt binary downloaded from the official sbt repository's release both work fine!
The problem only occurs with the version installed by coursier.

**Comment by tgodzik** [comment]
Not sure them :thinking: does anyone else have this problem? If it's more widespread we might need to take a closer look soon.

**Comment by eed3si9n** [comment]
> This version of C:\Users\HarryXi\AppData\Local\Coursier\data\bin\.sbt.aux.exe ...

So when Coursier says it's installing sbt, is it still installing some shim of sbt instead of the genuine sbt?

**Comment by harry-xi** [comment]
> So when Coursier says it's installing sbt, is it still installing some shim of sbt instead of the genuine sbt?

Honestly, I didn't understand your statement very well.
I was just installing scala and its tools using a binary version of coursier on a computer that didn't have scala (and any of its associated tools) installed.
During this process, I didn't notice any different log output when installing sbt than when installing other tools.

**Comment by eed3si9n** [comment]
Yea, sorry about that. That was more of an observation (I'm a maintainer of sbt) that Coursier does that. `bin.sbt.aux.exe` isn't something that we (sbt project) ship.

**Comment by Friendseeker** [comment]
> Yea, sorry about that. That was more of an observation (I'm a maintainer of sbt) that Coursier does that. `bin.sbt.aux.exe` isn't something that we (sbt project) ship.

I did some investigation on a fresh coursier sbt install on Windows and the situation has apparently improved. It now simply installs a thin `sbt.bat` file that redirects to genuine `sbt.bat` file.

```powershell
PS D:\Repos> where.exe sbt
C:\Users\Jerry Tan\AppData\Local\Coursier\data\bin\sbt.bat
```

Content of `C:\Users\Jerry Tan\AppData\Local\Coursier\data\bin\sbt.bat`

```
@echo off



@REM set %HOME% to equivalent of $HOME
if "%HOME%" == "" (set HOME=%HOMEDRIVE%%HOMEPATH%)

set ERROR_CODE=0

@REM set local scope for the variables with windows NT shell
if "%OS%"=="Windows_NT" @setlocal

@REM Decide how to startup depending on the version of windows

@REM -- Win98ME
if NOT "%OS%"=="Windows_NT" goto Win9xArg

@REM -- 4NT shell
if "%@eval[2+2]" == "4" goto 4NTArgs

@REM -- Regular WinNT shell
set CMD_LINE_ARGS=%*
goto endInit

@REM The 4NT Shell from jp software
:4NTArgs
set CMD_LINE_ARGS=%$
goto endInit

:Win9xArg
@REM Slurp the command line arguments.  This loop allows for an unlimited number
@REM of arguments (up to the command line limit, anyway).
set CMD_LINE_ARGS=
:Win9xApp
if %1a==a goto endInit
set CMD_LINE_ARGS=%CMD_LINE_ARGS% %1
shift
goto Win9xApp

@REM Reaching here means variables are defined and arguments have been captured
:endInit


@REM Start program
:runm2
SET CMDLINE="C:\Users\Jerry Tan\AppData\Local\Coursier\cache\arc\https\github.com\sbt\sbt\releases\download\v1.10.4\sbt-1.10.4.zip\sbt\bin\sbt.bat" %CMD_LINE_ARGS%
%CMDLINE%
if ERRORLEVEL 1 goto error
goto end

:error
if "%OS%"=="Windows_NT" @endlocal
set ERROR_CODE=1

:end
@REM set local scope for the variables with windows NT shell
if "%OS%"=="Windows_NT" goto endNT

@REM For old DOS remove the set variables from ENV - we assume they were not set
@REM before we started - at least we don't leave any baggage around
set CMD_LINE_ARGS=
set CMDLINE=
goto postExec

:endNT
@endlocal

:postExec
exit /B %ERROR_CODE%
```

**Comment by lvyuemeng** [comment]
> Never mind coursier doesn't always just install a thin shim...
> 
> https://github.com/coursier/coursier/blob/24ae7456d45c3597613f35076ed967c287597bb2/modules/install/src/main/scala/coursier/install/InstallDir.scala#L251-L259
> 
> Apparently it looks up for "prebuilt" exe launchers somewhere, and then fallback to thin bat shim...

Is there any way to circumvent this problem? It still ship cs.aux and other shim files.

**Comment by eed3si9n** [comment]
Use scoop on Windows? - https://www.scala-sbt.org/download

**Comment by Friendseeker** [comment]
If prebuilt sbt binary is broken, can we just disable prebuilt lookup when installing sbt (or if prebuilt are hosted in some remote server, delete these broken prebuilt).

Like on my machine the installation of sbt via coursier was fine. It just worked.

**Comment by lvyuemeng** [comment]
> Use scoop on Windows? - https://www.scala-sbt.org/download

I use coursier installed by scoop, and `coursier setup` will prompt:


> Checking if the standard Scala applications are installed
>   Found ammonite
>   Found cs
>   Found coursier
> No prebuilt binary available at https://github.com/scala/scala3/releases/download/3.6.1/scala3-3.6.1-x86_64-pc-win32.zip, https://github.com/scala/scala3/releases/download/3.6.1/scala3-3.6.1-x86_64-pc-win32.zip...

**Comment by Friendseeker** [comment]
> > Use scoop on Windows? - https://www.scala-sbt.org/download
> 
> 
> 
> I use coursier installed by scoop( actually the jar version, cs still can't use ), and `coursier setup` will prompt:
> 
> 
> 
> 
> 
> > Checking if the standard Scala applications are installed
> 
> >   Found ammonite
> 
> >   Found cs
> 
> >   Found coursier
> 
> > No prebuilt binary available at https://github.com/scala/scala3/releases/download/3.6.1/scala3-3.6.1-x86_64-pc-win32.zip, https://github.com/scala/scala3/releases/download/3.6.1/scala3-3.6.1-x86_64-pc-win32.zip...

I think Eugene is probably referring to using scoop to install sbt directly, instead of using scoop to install coursier.

**Comment by lvyuemeng** [comment]
> I think Eugene is probably referring to using scoop to install sbt directly, rather then using scoop to install coursier.

But I can't install the whole toolchain, not only sbt.

**Comment by lvyuemeng** [comment]
> I think Eugene is probably referring to using scoop to install sbt directly, rather then using scoop to install coursier.

But I can't install the whole toolchain, not only sbt. Are there other ways?

**Comment by Friendseeker** [comment]
> > I think Eugene is probably referring to using scoop to install sbt directly, rather then using scoop to install coursier.
> 
> But I can't install the whole toolchain, not only sbt. Are there other ways?

How about `scoop install scala-cli` (and vice versa to install other parts of the toolchain).

Yeah this is an ugly situation... I also use Windows (I have a Windows 11 ARM virtual machine on my MacBook and a physical x64 Windows 10 Machine), and on neither of these can I reproduce the issue. If I can reproduce it somehow, I might be able to look into it further.

**Comment by lvyuemeng** [comment]
> How about `scoop install scala-cli` (and vice versa to install other parts of the toolchain).
> 
> Yeah this is an ugly situation... I also use Windows (I have a Windows 11 ARM virtual machine on my MacBook and a physical x64 Windows 10 Machine), and on neither of these can I reproduce the issue. If I can reproduce it somehow, I might be able to look into it further.

I currently use intellij now to circumvent this. : (

**Comment by Friendseeker** [comment]
Now sbt 1.10.7 is released, I just tried `cs update sbt` on Windows. Still cannot reproduce the issue...

**Comment by lvyuemeng** [comment]
> Now sbt 1.10.7 is released, I just tried `cs update sbt` on Windows. Still cannot reproduce the issue...

I'm just stuck at cs installation. I try to use `coursier setup` but it will panic:

> Checking if the standard Scala applications are installed
>   Found ammonite
>   Found cs
>   Found coursier
> No prebuilt binary available at https://github.com/scala/scala3/releases/download/3.6.2/scala3-3.6.2-x86_64-pc-win32.zip...

**Comment by Friendseeker** [comment]
> > Now sbt 1.10.7 is released, I just tried `cs update sbt` on Windows. Still cannot reproduce the issue...
> 
> I'm just stuck at cs installation. I try to use `coursier setup` but it will panic:
> 
> > Checking if the standard Scala applications are installed
> > Found ammonite
> > Found cs
> > Found coursier
> > No prebuilt binary available at https://github.com/scala/scala3/releases/download/3.6.2/scala3-3.6.2-x86_64-pc-win32.zip...
> 
> So, currently, I can't even install sbt during the process.

I wonder if there's a flag that enables "prebuilt binary" mode. The mode is broken and should not be turned on.

**Comment by Friendseeker** [comment]
https://github.com/coursier/coursier/blob/5ea4aa43a58e7aaa2fec4da86d592ffb94c30fcb/modules/install/src/main/scala/coursier/install/InstallDir.scala#L323-L328

Exception is thrown right there.

**Comment by lvyuemeng** [comment]
> https://github.com/coursier/coursier/blob/5ea4aa43a58e7aaa2fec4da86d592ffb94c30fcb/modules/install/src/main/scala/coursier/install/InstallDir.scala#L323-L328
> 
> Exception is thrown right there.

I hope that will fix it, at least I can use `coursier`.

**Comment by Fiyaas** [comment]
echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo tee /etc/apt/trusted.gpg.d/sbt.asc
sudo apt-get update
sudo apt-get install sbt

**Comment by lvyuemeng** [comment]
```
https://github.com/coursier/jvm-index/raw/master/index.json
    0.0% [          ] 0B (0B / s)

Exception in thread "main" java.lang.Exception: Error while getting https://github.com/coursier/jvm-index/raw/master/index.json: coursier.cache.ArtifactError$DownloadError: download error: Caught java.net.ConnectException (Connection timed out: connect) while downloading https://github.com/coursier/jvm-index/raw/master/index.json
        at coursier.jvm.JvmIndex$.$anonfun$load$3(JvmIndex.scala:170)
        at coursier.jvm.JvmIndex$.$anonfun$load$3$adapted(JvmIndex.scala:168)
        at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
        at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
        at coursier.util.Task$.wrap(Task.scala:82)
        at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.5/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:902)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:878)
```
It seems weird, even I can open the url.
