### ISSUE TITLE
Documented installation command fails

### ISSUE THREAD

**Issue by mslinn** [coursier/coursier#3026]
The following incantation is shown on https://get-coursier.io/docs/cli-install:

```shell
$ cs install scala:2.12.15 scalac:2.12.15
```

However, that fails:

```shell
$ cs install scala:2.12.15 scalac:2.12.15
Exception in thread "main" coursier.error.ResolutionError$CantDownloadModule: Error downloading org.scala-lang:scala3-compiler_3:2.12.15
  not found: https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/2.12.15/scala3-compiler_3-2.12.15.pom
        at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:329)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:285)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at coursier.Resolve$.validate(Resolve.scala:327)
        at coursier.Resolve.validate0$1(Resolve.scala:115)
        at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:161)
        at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
        at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
        at coursier.util.Task$.wrap(Task.scala:84)
        at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

We can see that the URL (`https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/2.12.15/scala3-compiler_3-2.12.15.pom`) contains the `scala3-compiler_3/` subdirectory, which is not going to work with Scala 2.x. A better subdirectory might be `scala-compiler/`.

**Comment by tgodzik** [comment]
Thanks for reporting! Which version of coursier are you using? I can't reproduce on the newest one.

Btw. I recommend trying out the new scala runner that is available since the 3.5.0-RC4 version. It should work with all scala 2.12.x and 2.13.x versions. You can do `scala --scala-version 2.12.15` to get repl or try compile/run commands.

**Comment by mslinn** [comment]
I just installed coursier, so it should be the current version.

```shell
$ cs
Coursier 2.0.16
Usage: cs [options] [command] [command-options]

Available commands: bootstrap, channel, complete, fetch, get, install, java, java-home, launch, list, publish, resolve, setup, uninstall, update, search

Type  cs command --help  for help on an individual command
```

**Comment by tgodzik** [comment]
That's not the newest version, how did you install it?

**Comment by mslinn** [comment]
```shell
$ curl -sfL \
  "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz" | \
  gzip -d > ~/Downloads/cs
$ chmod +x ~/Downloads/cs
$ ~/Downloads/cs setup
```

**Comment by tgodzik** [comment]
The version I download does show `2.1.10`, but I don't think `cs setup` adds the cs itself to the PATH, so that might be an older cs on the PATH

**Comment by mslinn** [comment]
You are correct!

```script
$ ls -alF /home/mslinn/.local/bin/cs
-rwxr-xr-x 1 mslinn mslinn 59885680 Jan 14  2022 /home/mslinn/.local/bin/cs*

$ ~/.local/share/coursier/bin/cs version
2.1.10
```
