### ISSUE TITLE
bootstrap --native-image seems broken on OSX / Apple M1

### ISSUE THREAD

**Issue by jatcwang** [coursier/coursier#3057]
When I run this on OSX (Apple M1) I get the following error
```
> cs bootstrap echo-java --native-image -o echo
Exception in thread "main" coursier.jvm.JvmCache$JvmNotFoundInIndex: JVM graalvm:latest.release not found in index: JVM graalvm not found
	at coursier.jvm.JvmCache.$anonfun$get$3(JvmCache.scala:108)
	at coursier.jvm.JvmCache.$anonfun$get$3$adapted(JvmCache.scala:107)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

If I specify the GraalVM version explicitly using --graalvm 19.3 I get the error `Exception in thread "main" coursier.jvm.JvmCache$JvmNotFoundInIndex: JVM graalvm:19.3 not found in index: JVM graalvm not found`.

This seems to indicate that it cannot find the JVM `graalvm:19.3` in the JVM index.

By running `cs java --available`, I confirmed that indeed there's no JVM with the name prefix `graalvm:*`

```
graalvm-community:22.0.2
... etc etc
graalvm-java21:21.0.1
... etc etc
graalvm-oracle:21
... etc etc
```

## Possible solutions

1. Fix --graalvm flag to allow full JVM name instead of just the version
1. Fix coursier to not hardcode `graalvm:` prefix

I think no.1 should be relatively simple to implement, but no.2 will be helpful for better OOTB experience. What do you think?

**Comment by tgodzik** [comment]
Thanks for reporting! I would opt for 1. seems like a smaller fix and limited amount breakage possible
