### ISSUE TITLE
NullPointerException during resolution

### ISSUE THREAD

**Issue by avdv** [coursier/coursier#398]
Hi.

I'm using the sbt coursier plugin `1.0.0-M14-8` and sometimes when I'm trying to run `sbt task` I get this:

```
$ sbt stage              
[info] Loading global plugins from /home/claudio/.sbt/0.13/plugins
[info] Loading project definition from /home/claudio/src/search/project
[info] Updating search-build
[info] Resolved search-build dependencies
[info] Fetching artifacts of search-build
[info] Fetched artifacts of search-build
[info] Compiling 1 Scala source to /home/claudio/src/search/project/target/scala-2.10/sbt-0.13/classes...
[warn] /home/claudio/src/search/project/Build.scala:4: trait Build in package sbt is deprecated: Use .sbt format instead
[warn] object Build extends SbtBuild {
[warn]                      ^
[warn] one warning found
[info] Set current project to my-search (in build file:/home/claudio/src/search/)
[info] Packaging /home/claudio/src/search/target/scala-2.11/my-search_2.11-1.7.1-tests-sources.jar ...
[info] Packaging /home/claudio/src/search/target/scala-2.11/my-search_2.11-1.7.1-sources.jar ...
[info] Done packaging.
[info] Done packaging.
[info] Updating search
[info] Resolved search dependencies
coursier.ResolutionException: Exception during resolution
Caused by: java.lang.NullPointerException
	at coursier.Cache$$anonfun$validateChecksum$1.<init>(Cache.scala:797)
	at coursier.Cache$.validateChecksum(Cache.scala:797)
	at coursier.Cache$$anonfun$file$1.apply(Cache.scala:885)
	at coursier.Cache$$anonfun$file$1.apply(Cache.scala:882)
	at scalaz.EitherT$$anonfun$flatMap$1$$anonfun$apply$4.apply(EitherT.scala:93)
	at scalaz.$bslash$div.fold(Either.scala:58)
	at scalaz.EitherT$$anonfun$flatMap$1.apply(EitherT.scala:93)
	at scalaz.EitherT$$anonfun$flatMap$1.apply(EitherT.scala:93)
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$.Try(Task.scala:457)
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:33)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
	at scalaz.concurrent.Future.step(Future.scala:118)
	at scalaz.concurrent.Future.unsafePerformListen(Future.scala:75)
	at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:91)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:91)
	at scalaz.Free.resume(Free.scala:109)
	at scalaz.Free.go2$1(Free.scala:153)
	at scalaz.Free.go(Free.scala:157)
	at scalaz.Free.run(Free.scala:263)
	at scalaz.concurrent.Future.unsafePerformListen(Future.scala:76)
	at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:91)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:91)
	at scalaz.Free.resume(Free.scala:109)
	at scalaz.Free.go2$1(Free.scala:153)
	at scalaz.Free.go(Free.scala:157)
	at scalaz.Free.run(Free.scala:263)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:coursierResolution) coursier.ResolutionException: Exception during resolution
```

Usually, if I try the same command again, it works OK. So probably some kind of race condition?

**Comment by alexarchambault** [comment]
Wow, worrying. If you are using a `project/*.scala` based build definition, you may want to try with a standard `build.sbt` based one, the `project/*.scala` based ones sometimes mess with autoplugins (which sbt-coursier is).

**Comment by avdv** [comment]
OK, I'll try.

Although the `project/Build.scala` file simply adds an entry to `libraryDependencies` which is a left-over artefact where we wanted to support multi-project builds as well as building the sub-projects individually (top-level build.sbt uses `dependsOn` but the sub-projects add dependent libraries simply in `libraryDependencies` in a .scala file).

**Comment by avdv** [comment]
Just happened again, the stacktrace points to a different culprit:

```
[trace] Stack trace suppressed: run last search/*:coursierResolvers for the full output.
[error] (search/*:coursierResolvers) java.lang.NullPointerException
[error] Total time: 10 s, completed Jan 26, 2017 11:55:22 AM
[project-search:1.12.0-SNAPSHOT@2.5.12] (issue-1738) $ last search/*:coursierResolvers 
java.lang.NullPointerException
	at coursier.Tasks$$anonfun$coursierResolversTask$1$$anonfun$apply$2.<init>(Tasks.scala:60)
	at coursier.Tasks$$anonfun$coursierResolversTask$1.apply(Tasks.scala:60)
	at coursier.Tasks$$anonfun$coursierResolversTask$1.apply(Tasks.scala:59)
	at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:35)
	at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (search/*:coursierResolvers) java.lang.NullPointerException
[project-search:1.12.0-SNAPSHOT@2.5.12] (issue-1738) $ sbt  62.47s user 1.82s system 16% cpu 6:35.50 total
claudio@claudio-think ~/src/project/search (git)-[issue-1738] % sbt
[info] Loading global plugins from /home/claudio/.sbt/0.13/plugins
[info] Loading project definition from /home/claudio/src/project/search/project
[info] Set current project to project-search (in build file:/home/claudio/src/project/search/)
[project-search:1.12.0-SNAPSHOT@2.5.12] (issue-1738) $ test
[info] checking docker version
[info] docker pull exaonline/elasticicu:2.4.4
[info] Updating search
https://jcenter.bintray.com/org/elasticsearch/elasticsearch/2.4.4/elasticsearch-2.4.4.pom
  100.0% [##########] 18.4 KiB (20.8 KiB / s)
https://jcenter.bintray.com/org/elasticsearch/parent/2.4.4/parent-2.4.4.pom
  100.0% [##########] 79.9 KiB (571.0 KiB / s)
[info] Resolved search dependencies
[info] Fetching artifacts of search
[info] Fetched artifacts of searchasticsearch/elasticsearch/2.4.4/elasticsearch-2.4.4.jar
```

It happend once, trying again just worked. I'm currently using sbt coursier 1.0.0-M15-1.

**Comment by larochef** [comment]
Interesting point is that they all occur in some constructor, I'll have a look at some of these with javap to get a better clue of what can be null

**Comment by alexarchambault** [comment]
@larochef The ones here and yours, yes, but not the ones of https://github.com/coursier/coursier/issues/501, https://github.com/coursier/coursier/issues/475, and https://github.com/coursier/coursier/issues/441.

**Comment by tarun29061990** [comment]
Facing the same on osx catalina while running ./activator compile
```
[info] Loading global plugins from /Users/tarun/.sbt/0.13/plugins
[info] Updating {file:/Users/tarun/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1261)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1334)
	at sbt.IO$.pathSplit(IO.scala:744)
	at sbt.IO$.parseClasspath(IO.scala:859)
	at sbt.compiler.CompilerArguments.extClasspath(CompilerArguments.scala:62)
	at sbt.compiler.AggressiveCompile.withBootclasspath(AggressiveCompile.scala:50)
	at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:83)
	at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70)
	at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45)
	at sbt.Compiler$.apply(Compiler.scala:74)
	at sbt.Compiler$.apply(Compiler.scala:65)
	at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:789)
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:781)
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:781)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
[error] (compile:compile) java.lang.NullPointerException
```

**Comment by eed3si9n** [comment]
@tarun29061990 I don't see how this stack trace relates to Coursier.

**Comment by tarun29061990** [comment]
Yeah its not related to Coursier but facing it in a general scenario.  I am stuck on this issue from quite a long time now, so that's why seeking for help.

**Comment by avdv** [comment]
Hi!

Since I reported that a really long time ago, and given that I haven't ever seen this again, should we just close this issue?

**Comment by Sandeep023** [comment]
I am trying to do the below in macOS catalina and it's giving the error. I am stuck on it for two days any help would be appreciated.


`sbt compile
[info] Loading global plugins from /Users/user/.sbt/0.13/plugins
java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1262)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1335)
	at sbt.IO$.pathSplit(IO.scala:797)
	at sbt.IO$.parseClasspath(IO.scala:912)
	at sbt.compiler.CompilerArguments.extClasspath(CompilerArguments.scala:66)
	at sbt.compiler.MixedAnalyzingCompiler$.withBootclasspath(MixedAnalyzingCompiler.scala:188)
	at sbt.compiler.MixedAnalyzingCompiler$.searchClasspathAndLookup(MixedAnalyzingCompiler.scala:166)
	at sbt.compiler.MixedAnalyzingCompiler$.apply(MixedAnalyzingCompiler.scala:176)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:152)
	at sbt.Compiler$.compile(Compiler.scala:138)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:860)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:851)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:849)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
[error] (compile:compileIncremental) java.lang.NullPointerException
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
`

**Comment by avdv** [comment]
@Sandeep023 How is your problem related to coursier? SBT 0.13 is really old. Try to upgrade and better ask for help on stackoverflow.

Closing this issue, since it no longer occurred and seems to be fixed in newer versions.
