### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Found class scalaz.Memo, but interface was expected

### ISSUE THREAD

**Issue by PhilAndrew** [coursier/coursier#435]
I added coursier to my sbt project, tried to compile and got this error and gave up.

java.lang.IncompatibleClassChangeError: Found class scalaz.Memo, but interface was expected
        at argonaut.PrettyParams.<init>(PrettyParams.scala:112)
        at argonaut.PrettyParamss$class.$init$(PrettyParams.scala:252)
        at argonaut.Argonaut$.<init>(Argonaut.scala:3)
        at argonaut.Argonaut$.<clinit>(Argonaut.scala)
        at osgifelix.BndManifestGenerator$.<init>(BndManifestGenerator.scala:33)
        at osgifelix.BndManifestGenerator$.<clinit>(BndManifestGenerator.scala)
        at osgifelix.OsgiTasks$.osgifelix$OsgiTasks$$autoDetect$1(OsgiTasks.scala:33)
        at osgifelix.OsgiTasks$$anonfun$5.apply(OsgiTasks.scala:42)
        at osgifelix.OsgiTasks$$anonfun$5.apply(OsgiTasks.scala:38)
        at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
        at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
        at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:47)
        at osgifelix.OsgiTasks$.convertToInstructions(OsgiTasks.scala:38)
        at osgifelix.OsgiTasks$$anonfun$createInstructionsTask$1.apply(OsgiTasks.scala:237)
        at osgifelix.OsgiTasks$$anonfun$createInstructionsTask$1.apply(OsgiTasks.scala:219)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.IncompatibleClassChangeError: Found class scalaz.Memo, but interface was expected
        at osgifelix.OsgiTasks$$anonfun$jarCacheTask$1.apply(OsgiTasks.scala:68)
        at osgifelix.OsgiTasks$$anonfun$jarCacheTask$1.apply(OsgiTasks.scala:67)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (rootProject/*:osgiRepositoryInstructions) java.lang.IncompatibleClassChangeError: Found class scalaz.Memo, but interface was expected
[error] (*/*:jarCacheKey) java.lang.IncompatibleClassChangeError: Found class scalaz.Memo, but interface was expected
[error] Total time: 15 s, completed Feb 15, 2017 4:20:36 PM

**Comment by alexarchambault** [comment]
Likely conflicting scalaz versions. The plugin that `osgifelix` comes from seem to depend on argonaut 6.1, which itself depends on scalaz 7.1. sbt-coursier pulls scalaz 7.2, hence the error. You should check with the authors of the former plugin to bump the argonaut and scalaz dependencies.

**Comment by alexarchambault** [comment]
Closing this, feel free to re-open if you still face issues once all plugins are on scalaz `7.2` (no more `7.1`).
