### ISSUE TITLE
NPE while building project (stack trace)

### ISSUE THREAD

**Issue by vn971** [coursier/coursier#441]
I don't know where to get more details, so it's just the stack trace:

```text
[info] Done packaging.
java.lang.NullPointerException
	at coursier.ivy.IvyXml$$anonfun$mappings$1$$anonfun$apply$6.apply(IvyXml.scala:41)
	at coursier.ivy.IvyXml$$anonfun$mappings$1$$anonfun$apply$6.apply(IvyXml.scala:40)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:108)
	at coursier.ivy.IvyXml$$anonfun$mappings$1.apply(IvyXml.scala:40)
	at coursier.ivy.IvyXml$$anonfun$mappings$1.apply(IvyXml.scala:33)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:108)
	at coursier.ivy.IvyXml$.mappings(IvyXml.scala:33)
	at coursier.FromSbt$.dependencies(FromSbt.scala:74)
	at coursier.FromSbt$$anonfun$6.apply(FromSbt.scala:117)
	at coursier.FromSbt$$anonfun$6.apply(FromSbt.scala:117)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at coursier.FromSbt$.project(FromSbt.scala:117)
	at coursier.Tasks$$anonfun$coursierProjectTask$1$$anonfun$apply$6.apply(Tasks.scala:128)
	at coursier.Tasks$$anonfun$coursierProjectTask$1$$anonfun$apply$6.apply(Tasks.scala:125)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (robot/*:coursierProject) java.lang.NullPointerException
[error] Total time: 0 s, completed Feb 23, 2017 1:15:03 PM
```

**Comment by vn971** [comment]
I'm using `sbt.version=0.13.12`, `sbt-coursier 1.0.0-M15`.

**Comment by alexarchambault** [comment]
Wow, strange. Does it happen in a somehow consistent fashion (like everytime when you type the same commands)?

**Comment by vn971** [comment]
@alexarchambault no, it's inconsistent. Happens _sometimes_, rarely, and disappears just after a restart (whithout any changes to the sbt file, I'm sure of it, I just run it consequently from the same terminal).

**Comment by alexarchambault** [comment]
Keeping the discussion in https://github.com/coursier/coursier/issues/398.
