### ISSUE TITLE
Unable to reload project after adding the ensime plugin. (sbt-coursier)

### ISSUE THREAD

**Issue by pedromss** [coursier/coursier#464]
The project was loading fine then I added the ensime plugin to `~/.sbt/0.13/plugins/build.sbt` and:

```scala
import org.ensime.EnsimeCoursierKeys._
ensimeServerVersion in ThisBuild := "2.0.0-SNAPSHOT"
```

to `~/.sbt/.0.13/build.sbt`

As it says in the [ensime's documentation](http://ensime.org/build_tools/sbt/#install)

And when I try to load it I get this (output of `last` in sbt): 

```text
[info] Loading global plugins from /Users/pedromss/.sbt/0.13/plugins
[debug] 
[debug] Initial source changes: 
[debug] 	removed:Set()
[debug] 	added: Set()
[debug] 	modified: Set()
[debug] Invalidated products: Set()
[debug] External API changes: API Changes: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set()
[debug] 
[debug] Sources indirectly invalidated by:
[debug] 	product: Set()
[debug] 	binary dep: Set()
[debug] 	external source: Set()
[debug] All initially invalidated sources: Set()
[debug] Copy resource mappings: 
[debug] 	
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] Forcing garbage collection...
[debug] [Loading] Scanning directory /Users/pedromss/repos/coursier-failure-example/project
[debug] [Loading] Found non-root projects 
[debug] [Loading] Done in /Users/pedromss/repos/coursier-failure-example/project, returning: ()
[debug] deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin), Atom(com.softwaremill.clippy.ClippySbtPlugin)) and clauses Clauses(List(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(coursier.CoursierPlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(org.ensime.EnsimeCoursierPlugin),Set(Atom(org.ensime.EnsimePlugin))), Clause(Atom(org.ensime.EnsimeExtrasPlugin),Set(Atom(org.ensime.EnsimePlugin))), Clause(Atom(org.ensime.EnsimePlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(coursier.CoursierPlugin))), Clause(Atom(org.ensime.EnsimePlugin),Set(Atom(org.ensime.EnsimeCoursierPlugin))), Clause(Atom(org.ensime.EnsimePlugin),Set(Atom(org.ensime.EnsimeExtrasPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(org.ensime.EnsimePlugin)))))
[debug]   :: deduced result: Matched(com.softwaremill.clippy.ClippySbtPlugin,sbt.plugins.CorePlugin,sbt.plugins.IvyPlugin,coursier.CoursierPlugin,sbt.plugins.JvmPlugin,org.ensime.EnsimePlugin,sbt.plugins.JUnitXmlReportPlugin,org.ensime.EnsimeExtrasPlugin,org.ensime.EnsimeCoursierPlugin)
[debug] sorting: ns: List(com.softwaremill.clippy.ClippySbtPlugin, sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, coursier.CoursierPlugin, sbt.plugins.JvmPlugin, org.ensime.EnsimePlugin, sbt.plugins.JUnitXmlReportPlugin, org.ensime.EnsimeExtrasPlugin, org.ensime.EnsimeCoursierPlugin)
[debug]   :: sorting:: found: List(com.softwaremill.clippy.ClippySbtPlugin, sbt.plugins.CorePlugin) not found List(sbt.plugins.IvyPlugin, coursier.CoursierPlugin, sbt.plugins.JvmPlugin, org.ensime.EnsimePlugin, sbt.plugins.JUnitXmlReportPlugin, org.ensime.EnsimeExtrasPlugin, org.ensime.EnsimeCoursierPlugin)
[debug]   :: sorting:: found: List(com.softwaremill.clippy.ClippySbtPlugin, sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin) not found List(coursier.CoursierPlugin, sbt.plugins.JvmPlugin, org.ensime.EnsimePlugin, sbt.plugins.JUnitXmlReportPlugin, org.ensime.EnsimeExtrasPlugin, org.ensime.EnsimeCoursierPlugin)
[debug]   :: sorting:: found: List(com.softwaremill.clippy.ClippySbtPlugin, sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, coursier.CoursierPlugin, sbt.plugins.JvmPlugin) not found List(org.ensime.EnsimePlugin, sbt.plugins.JUnitXmlReportPlugin, org.ensime.EnsimeExtrasPlugin, org.ensime.EnsimeCoursierPlugin)
[debug]   :: sorting:: found: List(com.softwaremill.clippy.ClippySbtPlugin, sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, coursier.CoursierPlugin, sbt.plugins.JvmPlugin, org.ensime.EnsimePlugin, sbt.plugins.JUnitXmlReportPlugin) not found List(org.ensime.EnsimeExtrasPlugin, org.ensime.EnsimeCoursierPlugin)
[debug]   :: sorting:: found: List(com.softwaremill.clippy.ClippySbtPlugin, sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, coursier.CoursierPlugin, sbt.plugins.JvmPlugin, org.ensime.EnsimePlugin, sbt.plugins.JUnitXmlReportPlugin, org.ensime.EnsimeExtrasPlugin, org.ensime.EnsimeCoursierPlugin) not found List()
[debug]   :: sorted deduced result: List(com.softwaremill.clippy.ClippySbtPlugin, sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, coursier.CoursierPlugin, sbt.plugins.JvmPlugin, org.ensime.EnsimePlugin, sbt.plugins.JUnitXmlReportPlugin, org.ensime.EnsimeExtrasPlugin, org.ensime.EnsimeCoursierPlugin)
[debug] [Loading] Done in /Users/pedromss/repos/coursier-failure-example/project, returning: (coursier-failure-example-build)
[info] Loading project definition from /Users/pedromss/repos/coursier-failure-example/project
[debug] Running task... Cancel: Null, check cycles: false, forcegc: true
java.lang.NoSuchMethodError: coursier.core.Project$.apply(Lcoursier/core/Module;Ljava/lang/String;Lscala/collection/Seq;Lscala/collection/immutable/Map;Lscala/Option;Lscala/collection/Seq;Lscala/collection/Seq;Lscala/collection/Seq;Lscala/Option;Lscala/Option;Lscala/Option;Lscala/collection/Seq;Lcoursier/core/Info;)Lcoursier/core/Project;
	at coursier.FromSbt$.project(FromSbt.scala:119)
	at coursier.Tasks$$anonfun$coursierProjectTask$1$$anonfun$apply$6.apply(Tasks.scala:128)
	at coursier.Tasks$$anonfun$coursierProjectTask$1$$anonfun$apply$6.apply(Tasks.scala:125)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:coursierProject) java.lang.NoSuchMethodError: coursier.core.Project$.apply(Lcoursier/core/Module;Ljava/lang/String;Lscala/collection/Seq;Lscala/collection/immutable/Map;Lscala/Option;Lscala/collection/Seq;Lscala/collection/Seq;Lscala/collection/Seq;Lscala/Option;Lscala/Option;Lscala/Option;Lscala/collection/Seq;Lcoursier/core/Info;)Lcoursier/core/Project;
[debug] > load-failed
[debug] > last
```

The contents of my `~/.sbt/0.13/plugins/build.sbt` are: 

```scala
addSbtPlugin("com.softwaremill.clippy" % "plugin-sbt" % "0.5.2")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M15")
addSbtPlugin("org.ensime" % "sbt-ensime" % "1.12.7")
```

The contents of my `~/.sbt/0.13/build.sbt` are:

```scala
import com.softwaremill.clippy.ClippySbtPlugin._ // needed in global configuration only
import org.ensime.EnsimeCoursierKeys._
//ensimeServerVersion in ThisBuild := "2.0.0-SNAPSHOT"
clippyColorsEnabled := true
```

Needless to say the project loads and ensime works fine without coursier enabled.

Sample project (from the big data analysis course from coursera, where this happened to me):
https://pedromssilva@bitbucket.org/pedromssilva/cousier-fails-example.git

Is the problem obvious to you?

**Comment by hseeberger** [comment]
Same here! Looks like a Scala version compat issue.

**Comment by alexarchambault** [comment]
You should use ensime-sbt and sbt-coursier versions that are compatible... This is a problem until https://github.com/ensime/ensime-sbt/pull/312 gets fixed. ensime-sbt `1.12.7` along with sbt-coursier `1.0.0-M15-5` should be fine.

**Comment by hseeberger** [comment]
I'm not using ensime, just sbt-coursier.

**Comment by alexarchambault** [comment]
@pedromss You should probably bump the sbt-eclipse version. Former versions of it depend on scalaz 7.1, whereas sbt-coursier depends on scalaz 7.2.

@hseeberger You might be running into a bin compat issue with another plugin then. Issues with scalaz 7.1 were common some time ago.

**Comment by pedromss** [comment]
Worked like a charm! Thank you.

**Comment by hseeberger** [comment]
Hmm ... I wonder which plugin that would be (not using sbt-eclipse).

Here's the error I get:
```
[error] (akka-http-argonaut/compile:scalafmtInc) java.lang.NoSuchMethodError: coursier.maven.MavenRepository$.apply$default$5()Lscala/collection/immutable/Set;
```

**Comment by hseeberger** [comment]
Just ran `dependencyGraph` on my plugins and I'm using scalaz `7.2.8`.

**Comment by alexarchambault** [comment]
sbt-scalafmt depends on a former version of sbt-coursier... I opened https://github.com/scalameta/scalafmt/pull/846 to address that.

**Comment by hseeberger** [comment]
Thanks!

**Comment by olafurpg** [comment]
sbt on 2.12 can't come soon enough...

I've released sbt-scalafmt 0.6.6 with the fix in https://github.com/scalameta/scalafmt/pull/846

**Comment by hseeberger** [comment]
Are there any plans for sbt on Scala 2.12.

**Comment by olafurpg** [comment]
sbt 1.0 will be on 2.12

**Comment by alexarchambault** [comment]
Should be fixed now.
