### ISSUE TITLE
coursier sbt fails with scala-native build

### ISSUE THREAD

**Issue by MasseGuillaume** [coursier/coursier#468]
https://github.com/scala-native/scala-native/blob/master/project/build.sbt#L15

``` java.lang.NoSuchMethodError: fastparse.all$.parserApi(Ljava/lang/Object;Lscala/Function1;)Lfastparse/ParserApi;
  at coursier.ivy.PropertiesPattern$Parser$.<init>(Pattern.scala:127)
  at coursier.ivy.PropertiesPattern$Parser$.<clinit>(Pattern.scala)
  at coursier.ivy.PropertiesPattern$.parser(Pattern.scala:142)
  at coursier.ivy.PropertiesPattern$.parse(Pattern.scala:146)
  at coursier.Tasks$.coursier$Tasks$$globalPluginPattern$lzycompute(Tasks.scala:300)
  at coursier.Tasks$.coursier$Tasks$$globalPluginPattern(Tasks.scala:281)
  at coursier.Tasks$$anonfun$resolutionTask$1.apply(Tasks.scala:460)
  at coursier.Tasks$$anonfun$resolutionTask$1.apply(Tasks.scala:317)
  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
  at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
  at sbt.std.Transform$$anon$4.work(System.scala:63)
  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
  at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
  at sbt.Execute.work(Execute.scala:237)
  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
  at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
  at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
[error] (nscplugin/*:coursierResolution) java.lang.NoSuchMethodError: fastparse.all$.parserApi(Ljava/lang/Object;Lscala/Function1;)Lfastparse/ParserApi;
[error] Total time: 0 s, completed Mar 21, 2017 3:57:09 PM
```

**Comment by alexarchambault** [comment]
Maybe a bin compat issue with fastparse. It is shaded in the latest release of coursier though (`1.0.0-M15-5`), which works for me with the current master of scala-native.

**Comment by alexarchambault** [comment]
(Except that I'm getting some resolution errors when running `update` because of some snapshot dependencies - but no bin compat issues).

**Comment by MasseGuillaume** [comment]
Cool the snapshot problems are solved with `sbt rebuild`. I'm trying it out locally now.

**Comment by MasseGuillaume** [comment]
It still fails. This time is a duplicated compiler plugin in the classpath.

To reproduce:
```sbt rebuild sandbox/run```

**Comment by MasseGuillaume** [comment]
Wow that was fast! How can I try? Do you have nightly build?

**Comment by alexarchambault** [comment]
Ah, it was automatically closed, I was getting some linking errors last time I tried your command. I was about to try again (from another machine).

**Comment by alexarchambault** [comment]
But https://github.com/coursier/coursier/issues/487 could help.

**Comment by MasseGuillaume** [comment]
you need some dependencies: http://www.scala-native.org/en/latest/user/setup.html#installing-llvm-clang-and-boehm-gc

brew install llvm bdw-gc

**Comment by alexarchambault** [comment]
I'm still getting linking errors:
```
[info] Compiling 1 Scala source to /Users/alexandre/projects/scala-native/sandbox/target/scala-2.11/classes...
[info] Error: unable to load class: scala.scalanative.nscplugin.NirPlugin
[info] Ignoring duplicate plugin nir (scala.scalanative.nscplugin.NirPlugin)
[info] Linking (33 ms)
[error] cannot link: @Test$::main_class.ssnr.ObjectArray_unit
[error] cannot link: @java.lang.NoSuchMethodException
[error] cannot link: @java.lang.NoSuchMethodException::init_class.java.lang.String
[error] cannot link: @java.lang.String
...
[error] unable to link
[error] (sandbox/*:nativeLink) unable to link
```

You can test yourself by checking out the sources of coursier, changing the version in `version.sbt`, running `sbt ++2.10.6 publishLocal`, then using this version of sbt-coursier from the sources of scala-native.
