### ISSUE TITLE
NPE while loading project

### ISSUE THREAD

**Issue by vn971** [coursier/coursier#475]
Exception occured while trying to execute the command
`  sbt -Dsbt.log.format=false universal:packageZipTarball`
As far as I see from the log below, it's actually early in the process of loading the project (before the command).

Versions:
`sbt.version=0.13.13`
coursier loaded as a global (user-wide) plugin via `addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M15")`
This is a sporadical exception. Simply restarting the job made everything back OK.

```txt
[info] Loading global plugins from /home/vasya/.sbt/0.13/plugins
[info] Updating {file:/home/vasya/.sbt/0.13/plugins/}global-plugins...
[info] Resolving io.get-coursier#sbt-coursier;1.0.0-M15 ...
[info] Resolving io.get-coursier#coursier_2.10;1.0.0-M15 ...
[info] Resolving org.scala-lang#scala-library;2.10.6 ...
[info] Resolving org.scalaz#scalaz-core_2.10;7.2.7 ...
[info] Resolving com.lihaoyi#fastparse_2.10;0.4.2 ...
[info] Resolving com.lihaoyi#fastparse-utils_2.10;0.4.2 ...
[info] Resolving org.scalamacros#quasiquotes_2.10;2.1.0 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.6 ...
[info] Resolving com.lihaoyi#sourcecode_2.10;0.1.3 ...
[info] Resolving org.jsoup#jsoup;1.9.2 ...
[info] Resolving io.get-coursier#coursier-cache_2.10;1.0.0-M15 ...
[info] Resolving org.scalaz#scalaz-concurrent_2.10;7.2.7 ...
[info] Resolving org.scalaz#scalaz-effect_2.10;7.2.7 ...
[info] Resolving org.scala-sbt#sbt;0.13.13 ...
[info] Resolving org.scala-sbt#main;0.13.13 ...
[info] Resolving org.scala-sbt#actions;0.13.13 ...
[info] Resolving org.scala-sbt#classpath;0.13.13 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.6 ...
[info] Resolving org.scala-sbt#interface;0.13.13 ...
[info] Resolving org.scala-sbt#io;0.13.13 ...
[info] Resolving org.scala-sbt#control;0.13.13 ...
[info] Resolving org.scala-sbt#launcher-interface;1.0.0-M1 ...
[info] Resolving org.scala-sbt#completion;0.13.13 ...
[info] Resolving org.scala-sbt#collections;0.13.13 ...
[info] Resolving jline#jline;2.13 ...
[info] Resolving org.fusesource.jansi#jansi;1.11 ...
[info] Resolving org.scala-sbt#api;0.13.13 ...
[info] Resolving org.scala-sbt#classfile;0.13.13 ...
[info] Resolving org.scala-sbt#logging;0.13.13 ...
[info] Resolving org.scala-sbt#process;0.13.13 ...
[info] Resolving org.scala-sbt#compiler-integration;0.13.13 ...
[info] Resolving org.scala-sbt#incremental-compiler;0.13.13 ...
[info] Resolving org.scala-sbt#relation;0.13.13 ...
[info] Resolving org.scala-sbt#compile;0.13.13 ...
[info] Resolving org.scala-sbt#persist;0.13.13 ...
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.13 ...
[info] Resolving org.scala-sbt#ivy;0.13.13 ...
[info] Resolving org.scala-sbt#cross;0.13.13 ...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-2cf13e211b2cb31f0d3b317289dca70eca3362f6 ...
[info] Resolving com.jcraft#jsch;0.1.50 ...
[info] Resolving org.scala-sbt#serialization_2.10;0.1.2 ...
[info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.1 ...
[info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[info] Resolving org.scala-sbt#run;0.13.13 ...
[info] Resolving org.scala-sbt#task-system;0.13.13 ...
[info] Resolving org.scala-sbt#tasks;0.13.13 ...
[info] Resolving org.scala-sbt#tracking;0.13.13 ...
[info] Resolving org.scala-sbt#cache;0.13.13 ...
[info] Resolving org.scala-sbt#testing;0.13.13 ...
[info] Resolving org.scala-sbt#test-agent;0.13.13 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving org.scala-sbt#main-settings;0.13.13 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.13 ...
[info] Resolving org.scala-sbt#command;0.13.13 ...
[info] Resolving org.scala-sbt#template-resolver;0.1 ...
[info] Resolving org.scala-sbt#logic;0.13.13 ...
[info] Resolving org.scala-sbt#compiler-interface;0.13.13 ...
[info] Resolving org.scala-lang#jline;2.10.6 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /home/vasya/data/dev/luka/robot/project
coursier.ResolutionException: Exception during resolution
Caused by: java.lang.NullPointerException
	at coursier.maven.Pom$.property(Pom.scala:12)
	at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$33$$anonfun$apply$38$$anonfun$apply$40$$anonfun$apply$46$$anonfun$apply$51$$anonfun$apply$54$$anonfun$apply$58$$anonfun$apply$59.apply(Pom.scala:183)
	at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$33$$anonfun$apply$38$$anonfun$apply$40$$anonfun$apply$46$$anonfun$apply$51$$anonfun$apply$54$$anonfun$apply$58$$anonfun$apply$59.apply(Pom.scala:183)
	at scalaz.std.ListInstances$$anon$1$$anonfun$traverseImpl$2$$anonfun$apply$1.apply(List.scala:63)
	at scalaz.Need$$anon$4.value0$lzycompute(Name.scala:58)
	at scalaz.Need$$anon$4.value0(Name.scala:58)
	at scalaz.Need$$anon$4.value(Name.scala:59)
	at scalaz.Bind$$anonfun$ap$1.apply(Bind.scala:20)
	at scalaz.Bind$$anonfun$ap$1.apply(Bind.scala:20)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at scalaz.DisjunctionInstances1$$anon$1.bind(Either.scala:452)
	at scalaz.DisjunctionInstances1$$anon$1.bind(Either.scala:439)
	at scalaz.Bind$class.ap(Bind.scala:20)
	at scalaz.DisjunctionInstances1$$anon$1.ap(Either.scala:439)
	at scalaz.Apply$$anonfun$ap2$1.apply(Apply.scala:49)
	at scalaz.Bind$class.ap(Bind.scala:20)
	at scalaz.DisjunctionInstances1$$anon$1.ap(Either.scala:439)
	at scalaz.Apply$class.ap2(Apply.scala:49)
	at scalaz.DisjunctionInstances1$$anon$1.ap2(Either.scala:439)
	at scalaz.Applicative$class.apply2(Applicative.scala:32)
	at scalaz.DisjunctionInstances1$$anon$1.apply2(Either.scala:439)
	at scalaz.std.ListInstances$$anon$1$$anonfun$traverseImpl$2.apply(List.scala:63)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at scalaz.std.ListInstances$$anon$1.traverseImpl(List.scala:62)
	at scalaz.std.ListInstances$$anon$1.traverseImpl(List.scala:14)
	at scalaz.Traverse$Traversal.run(Traverse.scala:50)
	at scalaz.Traverse$class.traverse(Traverse.scala:62)
	at scalaz.std.ListInstances$$anon$1.traverse(List.scala:14)
	at scalaz.Applicative$class.traverse(Applicative.scala:37)
	at scalaz.DisjunctionInstances1$$anon$1.traverse(Either.scala:439)
	at scalaz.Traverse$class.traverseU(Traverse.scala:66)
	at scalaz.std.ListInstances$$anon$1.traverseU(List.scala:14)
	at scalaz.syntax.TraverseOps.traverseU(TraverseSyntax.scala:18)
	at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$33$$anonfun$apply$38$$anonfun$apply$40$$anonfun$apply$46$$anonfun$apply$51$$anonfun$apply$54$$anonfun$apply$58.apply(Pom.scala:183)
	at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$33$$anonfun$apply$38$$anonfun$apply$40$$anonfun$apply$46$$anonfun$apply$51$$anonfun$apply$54$$anonfun$apply$58.apply(Pom.scala:175)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$33$$anonfun$apply$38$$anonfun$apply$40$$anonfun$apply$46$$anonfun$apply$51$$anonfun$apply$54.apply(Pom.scala:175)
	at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$33$$anonfun$apply$38$$anonfun$apply$40$$anonfun$apply$46$$anonfun$apply$51$$anonfun$apply$54.apply(Pom.scala:172)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$33$$anonfun$apply$38$$anonfun$apply$40$$anonfun$apply$46$$anonfun$apply$51.apply(Pom.scala:172)
	at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$33$$anonfun$apply$38$$anonfun$apply$40$$anonfun$apply$46$$anonfun$apply$51.apply(Pom.scala:168)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$33$$anonfun$apply$38$$anonfun$apply$40$$anonfun$apply$46.apply(Pom.scala:168)
	at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$33$$anonfun$apply$38$$anonfun$apply$40$$anonfun$apply$46.apply(Pom.scala:165)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$33$$anonfun$apply$38$$anonfun$apply$40.apply(Pom.scala:165)
	at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$33$$anonfun$apply$38$$anonfun$apply$40.apply(Pom.scala:163)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$33$$anonfun$apply$38.apply(Pom.scala:163)
	at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$33$$anonfun$apply$38.apply(Pom.scala:156)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$33.apply(Pom.scala:156)
	at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$33.apply(Pom.scala:146)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at coursier.maven.Pom$$anonfun$project$2.apply(Pom.scala:146)
	at coursier.maven.Pom$$anonfun$project$2.apply(Pom.scala:141)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at coursier.maven.Pom$.project(Pom.scala:141)
	at coursier.maven.MavenRepository$$anonfun$findVersioning$1$$anonfun$apply$14$$anonfun$apply$15$$anonfun$apply$16.apply(MavenRepository.scala:266)
	at coursier.maven.MavenRepository$$anonfun$findVersioning$1$$anonfun$apply$14$$anonfun$apply$15$$anonfun$apply$16.apply(MavenRepository.scala:265)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at coursier.maven.MavenRepository$$anonfun$findVersioning$1$$anonfun$apply$14$$anonfun$apply$15.apply(MavenRepository.scala:265)
	at coursier.maven.MavenRepository$$anonfun$findVersioning$1$$anonfun$apply$14$$anonfun$apply$15.apply(MavenRepository.scala:264)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at coursier.maven.MavenRepository$$anonfun$findVersioning$1$$anonfun$apply$14.apply(MavenRepository.scala:264)
	at coursier.maven.MavenRepository$$anonfun$findVersioning$1$$anonfun$apply$14.apply(MavenRepository.scala:264)
	at scalaz.concurrent.Task$.Try(Task.scala:457)
	at scalaz.concurrent.Task$$anonfun$point$1.apply(Task.scala:324)
	at scalaz.concurrent.Task$$anonfun$point$1.apply(Task.scala:324)
	at scalaz.concurrent.Future$$anonfun$delay$1.apply(Future.scala:402)
	at scalaz.concurrent.Future$$anonfun$delay$1.apply(Future.scala:402)
	at scalaz.concurrent.Future.step(Future.scala:119)
	at scalaz.concurrent.Future.unsafePerformListen(Future.scala:75)
	at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:91)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:91)
	at scalaz.Free.resume(Free.scala:109)
	at scalaz.Free.go2$1(Free.scala:153)
	at scalaz.Free.go(Free.scala:157)
	at scalaz.Free.run(Free.scala:263)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:coursierResolution) coursier.ResolutionException: Exception during resolution
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? r
```

**Comment by vn971** [comment]
(Note: I raised a similarly looking issue before https://github.com/coursier/coursier/issues/441 , but the stack trace is completely different now, so I guessed it's OK to raise a new issue.)

**Comment by alexarchambault** [comment]
Keeping the discussion in https://github.com/coursier/coursier/issues/398.
