### ISSUE TITLE
NPE while loading the project

### ISSUE THREAD

**Issue by vn971** [coursier/coursier#501]
New NPE when loading a project:

```text
[info] Loading global plugins from /home/vasya/.sbt/0.13/plugins
[info] Loading project definition from /home/vasya/data/dev/luka/robot/project
coursier.ResolutionException: Exception during resolution
Caused by: java.lang.NullPointerException
	at coursier.ivy.IvyXml$$anonfun$project$3$$anonfun$apply$20.apply(IvyXml.scala:113)
	at coursier.ivy.IvyXml$$anonfun$project$3$$anonfun$apply$20.apply(IvyXml.scala:110)
	at scalaz.$bslash$div.map(Either.scala:112)
	at coursier.ivy.IvyXml$$anonfun$project$3.apply(IvyXml.scala:110)
	at coursier.ivy.IvyXml$$anonfun$project$3.apply(IvyXml.scala:106)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at coursier.ivy.IvyXml$.project(IvyXml.scala:106)
	at coursier.ivy.IvyRepository$$anonfun$findNoInverval$2$$anonfun$apply$5$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$8.apply(IvyRepository.scala:222)
	at coursier.ivy.IvyRepository$$anonfun$findNoInverval$2$$anonfun$apply$5$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$8.apply(IvyRepository.scala:221)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at coursier.ivy.IvyRepository$$anonfun$findNoInverval$2$$anonfun$apply$5$$anonfun$apply$6$$anonfun$apply$7.apply(IvyRepository.scala:221)
	at coursier.ivy.IvyRepository$$anonfun$findNoInverval$2$$anonfun$apply$5$$anonfun$apply$6$$anonfun$apply$7.apply(IvyRepository.scala:220)
	at scalaz.$bslash$div.flatMap(Either.scala:135)
	at coursier.ivy.IvyRepository$$anonfun$findNoInverval$2$$anonfun$apply$5$$anonfun$apply$6.apply(IvyRepository.scala:220)
	at coursier.ivy.IvyRepository$$anonfun$findNoInverval$2$$anonfun$apply$5$$anonfun$apply$6.apply(IvyRepository.scala:220)
	at scalaz.concurrent.Task$.Try(Task.scala:457)
	at scalaz.concurrent.Task$$anonfun$point$1.apply(Task.scala:324)
	at scalaz.concurrent.Task$$anonfun$point$1.apply(Task.scala:324)
	at scalaz.concurrent.Future$$anonfun$delay$1.apply(Future.scala:402)
	at scalaz.concurrent.Future$$anonfun$delay$1.apply(Future.scala:402)
	at scalaz.concurrent.Future.step(Future.scala:119)
	at scalaz.concurrent.Future.unsafePerformListen(Future.scala:75)
	at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:91)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:91)
	at scalaz.Free.resume(Free.scala:109)
	at scalaz.Free.go2$1(Free.scala:153)
	at scalaz.Free.go(Free.scala:157)
	at scalaz.Free.run(Free.scala:263)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:coursierResolution) coursier.ResolutionException: Exception during resolution
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

sbt.version=0.13.13
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC1")

It occurs while initially loading the project, retrying to load the project made everything normal again. Note that I had 2 different SBT instances working on a single project (one in background waiting with the command `~compile`, one just loading the project).

(I haven't seen the exact stack in the exception, yet, so I decited to open a yet-another issue.)

**Comment by alexarchambault** [comment]
Like https://github.com/coursier/coursier/issues/398, https://github.com/coursier/coursier/issues/441, and https://github.com/coursier/coursier/issues/475, I have no idea what could trigger that... Any extra detail would be welcome (e.g. what do the `ivy.xml` files that trigger that look like?)

**Comment by vn971** [comment]
@alexarchambault is there any way get the exact file that causes the issue? Maybe add some kind of loggig to coursier so that it'll catch the exception and throw it back with a custom text (name of the file included).
IDK actually, just thinking. You probably know better.

P.S. Feel free to close the issue if it's not useful.

**Comment by eddsteel** [comment]
I got this today and switching to RC2 made it go away. I didn't investigate further.

**Comment by alexarchambault** [comment]
Keeping the discussion in https://github.com/coursier/coursier/issues/398. Thanks for the extra error case (although what can cause that is still not clear to me).
