### ISSUE TITLE
Random NPE when loading sbt project

### ISSUE THREAD

**Issue by larochef** [coursier/coursier#553]
I have this kind of NPE on a regular basis when loading projects (basically on sbt startup or sbt reload)

Fortunately, when reloading, it usually then works.

```
coursier.ResolutionException: Exception during resolution
Caused by: java.lang.NullPointerException
        at coursier.maven.Pom$$anonfun$dependency$1.<init>(Pom.scala:42)
        at coursier.maven.Pom$.dependency(Pom.scala:42)
        at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$32$$anonfun$apply$33.apply(Pom.scala:168)
        at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$32$$anonfun$apply$33.apply(Pom.scala:168)
        at scalaz.std.ListInstances$$anon$1$$anonfun$traverseImpl$2$$anonfun$apply$1.apply(List.scala:63)
        at scalaz.Need$$anon$4.value0$lzycompute(Name.scala:58)
        at scalaz.Need$$anon$4.value0(Name.scala:58)
        at scalaz.Need$$anon$4.value(Name.scala:59)
        at scalaz.Bind$$anonfun$ap$1.apply(Bind.scala:20)
        at scalaz.Bind$$anonfun$ap$1.apply(Bind.scala:20)
        at scalaz.$bslash$div.flatMap(Either.scala:135)
        at scalaz.DisjunctionInstances1$$anon$1.bind(Either.scala:452)
        at scalaz.DisjunctionInstances1$$anon$1.bind(Either.scala:439)
        at scalaz.Bind$class.ap(Bind.scala:20)
        at scalaz.DisjunctionInstances1$$anon$1.ap(Either.scala:439)
        at scalaz.Apply$$anonfun$ap2$1.apply(Apply.scala:49)
        at scalaz.Bind$class.ap(Bind.scala:20)
        at scalaz.DisjunctionInstances1$$anon$1.ap(Either.scala:439)
        at scalaz.Apply$class.ap2(Apply.scala:49)
        at scalaz.DisjunctionInstances1$$anon$1.ap2(Either.scala:439)
        at scalaz.Applicative$class.apply2(Applicative.scala:32)
        at scalaz.DisjunctionInstances1$$anon$1.apply2(Either.scala:439)
        at scalaz.std.ListInstances$$anon$1$$anonfun$traverseImpl$2.apply(List.scala:63)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at scalaz.std.ListInstances$$anon$1.traverseImpl(List.scala:62)
        at scalaz.std.ListInstances$$anon$1.traverseImpl(List.scala:14)
        at scalaz.Traverse$Traversal.run(Traverse.scala:50)
        at scalaz.Traverse$class.traverse(Traverse.scala:62)
        at scalaz.std.ListInstances$$anon$1.traverse(List.scala:14)
        at scalaz.Applicative$class.traverse(Applicative.scala:37)
        at scalaz.DisjunctionInstances1$$anon$1.traverse(Either.scala:439)
        at scalaz.Traverse$class.traverseU(Traverse.scala:66)
        at scalaz.std.ListInstances$$anon$1.traverseU(List.scala:14)
        at scalaz.syntax.TraverseOps.traverseU(TraverseSyntax.scala:18)
        at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$32.apply(Pom.scala:168)
        at coursier.maven.Pom$$anonfun$project$2$$anonfun$apply$32.apply(Pom.scala:158)
        at scalaz.$bslash$div.flatMap(Either.scala:135)
        at coursier.maven.Pom$$anonfun$project$2.apply(Pom.scala:158)
        at coursier.maven.Pom$$anonfun$project$2.apply(Pom.scala:153)
        at scalaz.$bslash$div.flatMap(Either.scala:135)
        at coursier.maven.Pom$.project(Pom.scala:153)
        at coursier.maven.MavenRepository$$anonfun$coursier$maven$MavenRepository$$parseRawPom$1$1$$anonfun$apply$14.apply(MavenRepository.scala:255)
        at coursier.maven.MavenRepository$$anonfun$coursier$maven$MavenRepository$$parseRawPom$1$1$$anonfun$apply$14.apply(MavenRepository.scala:254)
        at scalaz.$bslash$div.flatMap(Either.scala:135)
        at coursier.maven.MavenRepository$$anonfun$coursier$maven$MavenRepository$$parseRawPom$1$1.apply(MavenRepository.scala:254)
        at coursier.maven.MavenRepository$$anonfun$coursier$maven$MavenRepository$$parseRawPom$1$1.apply(MavenRepository.scala:253)
        at scalaz.$bslash$div.flatMap(Either.scala:135)
        at coursier.maven.MavenRepository.coursier$maven$MavenRepository$$parseRawPom$1(MavenRepository.scala:253)
        at coursier.maven.MavenRepository$$anonfun$findVersioning$1$$anonfun$apply$17$$anonfun$apply$18.apply(MavenRepository.scala:319)
        at coursier.maven.MavenRepository$$anonfun$findVersioning$1$$anonfun$apply$17$$anonfun$apply$18.apply(MavenRepository.scala:319)
        at scalaz.concurrent.Task$.Try(Task.scala:457)
        at scalaz.concurrent.Task$$anonfun$point$1.apply(Task.scala:324)
        at scalaz.concurrent.Task$$anonfun$point$1.apply(Task.scala:324)
        at scalaz.concurrent.Future$$anonfun$delay$1.apply(Future.scala:402)
        at scalaz.concurrent.Future$$anonfun$delay$1.apply(Future.scala:402)
        at scalaz.concurrent.Future.step(Future.scala:119)
        at scalaz.concurrent.Future.unsafePerformListen(Future.scala:75)
        at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
        at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
        at scalaz.Free$$anonfun$map$1.apply(Free.scala:91)
        at scalaz.Free$$anonfun$map$1.apply(Free.scala:91)
        at scalaz.Free.resume(Free.scala:109)
        at scalaz.Free.go2$1(Free.scala:153)
        at scalaz.Free.go(Free.scala:157)
        at scalaz.Free.run(Free.scala:263)
        at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
        at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by alexarchambault** [comment]
That looks like the same issue as https://github.com/coursier/coursier/issues/398. Keeping the discussion there. Thanks for the extra case though (although I still have no clue what could cause those... there can't be nulls where these happen. I'm not personally running into those).
