### ISSUE TITLE
Write a coursier-based implem of sbt lib management API

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#601]
See https://github.com/sbt/librarymanagement/pull/123.

cc @eed3si9n

**Comment by alexarchambault** [comment]
@eed3si9n coursier doesn't handle publishing for now... Is a fallback on another API implementation (the default one?) possible in a first time?

**Comment by alexarchambault** [comment]
Is it related to https://github.com/sbt/sbt/issues/2997? This might be of interest to @jvican, then.

**Comment by eed3si9n** [comment]
You/I/someone can start the impl to get the feel for it, but plz note that the API is still in flux. As noted in the Gitter, Coursier is the primary customer of the API to plz don't hesitate to provide feedback.

I am fine with either moving publishing related thing to another interface or you falling back to using Ivy based implementation for publishing.

**Comment by jvican** [comment]
> I am fine with either moving publishing related thing to another interface or you falling back to using Ivy based implementation for publishing.
  
I think moving publishing to another interface is strictly the right thing to do. IIRC the ivy interfaces for publishing and downloading dependencies are also split.

**Comment by eed3si9n** [comment]
LM API is making good on what I've been advocating, which is keep Ivy in sbt 1.0 but abstract it with API, so we can switch during 1.x or provide some options for ppl to use Coursier easier.

**Comment by alexarchambault** [comment]
Yeah, if any of you want to take a cut at it, please do!

It would make sense to split the interface, fetching dependencies and publishing are different concerns IMO.

**Comment by leonardehrenfried** [comment]
I'm taking a stab at this by copying copious amounts of code from the sbt plugin.

My progress can be viewed here: https://github.com/sbt/librarymanagement/compare/1.x...leonardehrenfried:coursier

Right now it's very early days and I haven't even got it to compile yet, however it looks promising. If anyone wants to help me out, advice and/or code would be very welcome.

**Comment by leonardehrenfried** [comment]
Today managed to get the new sbt module to compile (albeit with some information missing) and even  a very simple sbt project to sort-of resolve:

```
$ sbt
Getting org.scala-sbt sbt 10.0.4-SNAPSHOT ...
:: retrieving :: org.scala-sbt#boot-app
        confs: [default]
        76 artifacts copied, 0 already retrieved (32442kB/50ms)
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/lehrenfried/dev/play-json-traits/project
[info] Updating ProjectRef(uri("file:/home/lehrenfried/dev/play-json-traits/project/"), "play-json-traits-build")...
https://repo1.maven.org/maven2/org/scala-sbt/zinc-ivy-integration_2.12/1.0.2/zinc-ivy-integration_2.12-1.0.2.jar
  100.0% [##########] 46.6 KiB (98.0 KiB / s)
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.3.1/protobuf-java-3.3.1.jar
  100.0% [##########] 1.3 MiB (4.5 MiB / s)
https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-scalajson_2.12/0.8.1/sjson-new-scalajson_2.12-0.8.1.jar
  100.0% [##########] 36.3 KiB (363.3 KiB / s)
https://repo1.maven.org/maven2/org/scala-sbt/zinc-classpath_2.12/1.0.2/zinc-classpath_2.12-1.0.2.jar
  100.0% [##########] 70.7 KiB (609.5 KiB / s)
https://repo1.maven.org/maven2/org/scala-sbt/zinc-apiinfo_2.12/1.0.2/zinc-apiinfo_2.12-1.0.2.jar
  100.0% [##########] 150.6 KiB (515.9 KiB / s)
https://repo1.maven.org/maven2/org/scala-sbt/zinc-core_2.12/1.0.2/zinc-core_2.12-1.0.2.jar
  100.0% [##########] 327.9 KiB (2.9 MiB / s)
https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-core_2.12/0.8.1/sjson-new-core_2.12-0.8.1.jar
  100.0% [##########] 766.7 KiB (7.3 MiB / s)
https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile-core_2.12/1.0.2/zinc-compile-core_2.12-1.0.2.jar
  100.0% [##########] 214.7 KiB (2.4 MiB / s)
https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.0.2/compiler-interface-1.0.2.jar
  100.0% [##########] 86.6 KiB (931.1 KiB / s)
https://repo1.maven.org/maven2/org/scala-sbt/zinc-classfile_2.12/1.0.2/zinc-classfile_2.12-1.0.2.jar
  100.0% [##########] 50.6 KiB (871.6 KiB / s)
https://repo1.maven.org/maven2/org/scala-sbt/zinc_2.12/1.0.2/zinc_2.12-1.0.2.jar
  100.0% [##########] 56.4 KiB (1.1 MiB / s)
https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.1.0/io_2.12-1.1.0.jar
  100.0% [##########] 187.0 KiB (1.2 MiB / s)
https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.0.2/compiler-bridge_2.12-1.0.2.jar
  100.0% [##########] 208.2 KiB (2.7 MiB / s)
https://repo1.maven.org/maven2/io/get-coursier/coursier_2.12/1.0.0-RC13/coursier_2.12-1.0.0-RC13.jar
  100.0% [##########] 1.4 MiB (10.7 MiB / s)
https://repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.12/1.0.0-RC13/coursier-cache_2.12-1.0.0-RC13.jar
  100.0% [##########] 183.3 KiB (2.6 MiB / s)
https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.46/jsch-0.1.46.jar
  100.0% [##########] 220.5 KiB (3.7 MiB / s)
https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile_2.12/1.0.2/zinc-compile_2.12-1.0.2.jar
  100.0% [##########] 15.8 KiB (226.3 KiB / s)
https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-a3314352b638afbf0dca19f127e8263ed6f898bd/ivy-2.3.0-sbt-a3314352b638a…
  100.0% [##########] 1.1 MiB (6.6 MiB / s)
https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.0.5/scala-parser-combinators_2.12-1.0.5.jar
  100.0% [##########] 205.1 KiB (1.3 MiB / s)
[info] Done updating.
[info] Updating ProjectRef(uri("file:/home/lehrenfried/dev/play-json-traits/project/"), "play-json-traits-build")...
[info] Done updating.
[warn] Update task caching failed due to NullPointerException.
[warn] Report the following output to sbt:
[warn] Update report:
[warn]  Resolve time: -1 ms, Download time: -1 ms, Download size: -1 bytes
[error] java.lang.NullPointerException
[error]         at sjsonnew.JavaExtraFormats.$anonfun$fileStringIso$1(JavaExtraFormats.scala:43)
[error]         at sjsonnew.IsoString$$anon$1.to(IsoString.scala:26)
[error]         at sjsonnew.IsoFormats$$anon$2.write(IsoFormats.scala:31)
[error]         at sjsonnew.JsonWriter.addField(JsonFormat.scala:40)
[error]         at sjsonnew.JsonWriter.addField$(JsonFormat.scala:37)
[error]         at sjsonnew.IsoFormats$$anon$2.addField(IsoFormats.scala:28)
[error]         at sjsonnew.Builder.addField(Builder.scala:43)
[error]         at sbt.librarymanagement.UpdateReportFormats$$anon$1.write(UpdateReportFormats.scala:26)
[error]         at sbt.librarymanagement.UpdateReportFormats$$anon$1.write(UpdateReportFormats.scala:9)
[error]         at sjsonnew.SupportConverter.toJsonUnsafe(SupportConverter.scala:23)
[error]         at sjsonnew.SupportConverter.toJsonUnsafe$(SupportConverter.scala:20)
[error]         at sjsonnew.support.scalajson.unsafe.Converter$.toJsonUnsafe(Converter.scala:7)
[error]         at sjsonnew.SupportConverter.$anonfun$toJson$1(SupportConverter.scala:14)
[error]         at scala.util.Try$.apply(Try.scala:209)
[error]         at sjsonnew.SupportConverter.toJson(SupportConverter.scala:14)
[error]         at sjsonnew.SupportConverter.toJson$(SupportConverter.scala:13)
[error]         at sjsonnew.support.scalajson.unsafe.Converter$.toJson(Converter.scala:7)
[error]         at sbt.util.PlainOutput.write(Output.scala:16)
[error]         at sbt.util.FileBasedStore.$anonfun$write$1(CacheStore.scala:73)
[error]         at sbt.util.FileBasedStore.$anonfun$write$1$adapted(CacheStore.scala:72)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.util.FileBasedStore.write(CacheStore.scala:72)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:111)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:111)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:94)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:125)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2371)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Configuration to use for managed classpath must be explicitly defined when default configurations are not present.
[error]         at scala.sys.package$.error(package.scala:27)
[error]         at sbt.Classpaths$.notFound$1(Defaults.scala:1685)
[error]         at sbt.Classpaths$.$anonfun$findClasspathConfig$2(Defaults.scala:1688)
[error]         at scala.Option.getOrElse(Option.scala:121)
[error]         at sbt.Classpaths$.findClasspathConfig(Defaults.scala:1688)
[error]         at sbt.Classpaths$.$anonfun$configSettings$3(Defaults.scala:1636)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / classpathConfiguration) Configuration to use for managed classpath must be explicitly defined when default configurations are not present.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? %                                                                     
```

**Comment by leonardehrenfried** [comment]
The problem is that testing it out is pretty slow due to having to compile `sbt/librarymanagement` and then `sbt/sbt`.

I probably need to set up a easily runnable test that resolves a test build, along the lines of `BaseIvySpecification`.

**Comment by leonardehrenfried** [comment]
@alexarchambault I've copied the `ToSbt` file from the sbt plugin and have a question about it. What is the expected value of the following parameter: https://github.com/coursier/coursier/blob/master/sbt-coursier/src/main/scala/coursier/ToSbt.scala#L202

`configs` is a `Map[String, Set[String]]`. Is the key supposed to be the config value, like "test", and the value the set of dependent configs?

**Comment by alexarchambault** [comment]
Fixed by https://github.com/sbt/librarymanagement/pull/270 and https://github.com/coursier/sbt-coursier/pull/7.
