### ISSUE TITLE
updateSbtClassifiers SBT task yields empty data with Coursier enabled

### ISSUE THREAD

**Issue by netvl** [coursier/coursier#617]
I found out that if I enable Coursier, then SBT dependency sources no longer appear in my IDEA project. It seems that to obtain sources/javadocs IDEA eventually delegates to the `updateSbtClassifiers` task which, when Coursier is enabled, yields the following thing:
```
[IJ]> show updateSbtClassifiers
[info] Update report:
[info] 	Resolve time: -1 ms, Download time: -1 ms, Download size: -1 bytes
[info] 	default:
[success] Total time: 1 s, completed Jul 20, 2017 3:23:23 PM
```

If Coursier is disabled, then this task returns correct results:
```
[info] Update report:
[info] 	Resolve time: 158 ms, Download time: 14 ms, Download size: 0 bytes
[info] 	default:
[info] 	com.typesafe.sbt:sbt-native-packager
[info] 		- 1.2.0
[info] 			status: release
[info] 			publicationDate: Wed Jun 07 21:44:12 PDT 2017
[info] 			resolver: sbt-chain
[info] 			artifactResolver: sbt-chain
[info] 			evicted: false
[info] 			textraAttributes: Map(scalaVersion -> 2.10, sbtVersion -> 0.13)
[info] 			isDefault: false
[info] 			configurations: compile, default(compile)
[info] 			callers: default:testsbt$sources_2.10:1.0
[info] 
... lots of entries like the above one follow
```

I observe this with 1.0.0-RC8 version of Coursier. Apparently, versions RC7 through RC5 exhibit the same behavior, while RC4 and RC3 throw an exception:
```
[IJ]> show updateSbtClassifiers
[trace] Stack trace suppressed: run last *:updateSbtClassifiers for the full output.
[error] (*:updateSbtClassifiers) java.util.NoSuchElementException: key not found: plugin
[error] Total time: 2 s, completed Jul 20, 2017 3:31:03 PM
[IJ]> last updateSbtClassifiers
java.util.NoSuchElementException: key not found: plugin
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:58)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:58)
	at coursier.ToSbt$$anonfun$19.apply(ToSbt.scala:215)
	at coursier.ToSbt$$anonfun$19.apply(ToSbt.scala:212)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:224)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at coursier.ToSbt$.updateReport(ToSbt.scala:212)
	at coursier.Tasks$$anonfun$updateTask$1.coursier$Tasks$$anonfun$$report$1(Tasks.scala:1192)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$55.apply(Tasks.scala:1219)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$55.apply(Tasks.scala:1219)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
	at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:1211)
	at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:1044)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:updateSbtClassifiers) java.util.NoSuchElementException: key not found: plugin
```
I didn't test versions below that.

**Comment by alexarchambault** [comment]
Should be fixed by https://github.com/coursier/coursier/pull/620/commits/d3bedc838fa438742039b4fb693b05791d9a668a, that will be included in `1.0.0-RC9`.

**Comment by alexarchambault** [comment]
Should work again since 1.0.0-RC9. Re-open if ever that doesn't work for you.

**Comment by netvl** [comment]
Yes, it seems to be working. Thank you very much!
