### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by mr-git** [coursier/coursier#674]
Tried 1.0.0-RC12 with Java 9, got strange error:
```
[error] java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class coursier/shaded/fastparse/core/LowestPriSequencer. Method $anonfun$Sequencer1$1(Ljava/lang/Object;Ljava/lang/Object;)Lscala/Tuple2; at index 39 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
[error] 	at coursier.shaded.fastparse.core.LowestPriSequencer.Sequencer1(SequencerGen.scala:88)
[error] 	at coursier.shaded.fastparse.core.LowestPriSequencer.Sequencer1$(SequencerGen.scala:88)
[error] 	at coursier.shaded.fastparse.core.Implicits$Sequencer$.Sequencer1(Implicits.scala:16)
[error] 	at coursier.ivy.PropertiesPattern$.$anonfun$parser$6(Pattern.scala:132)
[error] 	at coursier.shaded.fastparse.parsers.Combinators$Rule.pCached$lzycompute(Combinators.scala:155)
[error] 	at coursier.shaded.fastparse.parsers.Combinators$Rule.pCached(Combinators.scala:155)
[error] 	at coursier.shaded.fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:160)
[error] 	at coursier.shaded.fastparse.parsers.Transformers$Mapper.parseRec(Transformers.scala:19)
[error] 	at coursier.shaded.fastparse.parsers.Combinators$Either.rec$4(Combinators.scala:528)
[error] 	at coursier.shaded.fastparse.parsers.Combinators$Either.parseRec(Combinators.scala:544)
[error] 	at coursier.shaded.fastparse.parsers.Combinators$Repeat.rec$3(Combinators.scala:452)
[error] 	at coursier.shaded.fastparse.parsers.Combinators$Repeat.parseRec(Combinators.scala:489)
[error] 	at coursier.shaded.fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:160)
[error] 	at coursier.shaded.fastparse.parsers.Transformers$Mapper.parseRec(Transformers.scala:19)
[error] 	at coursier.shaded.fastparse.core.Parser.parseInput(Parsing.scala:376)
[error] 	at coursier.shaded.fastparse.core.Parser.parse(Parsing.scala:358)
[error] 	at coursier.ivy.PropertiesPattern$.parse(Pattern.scala:148)
[error] 	at coursier.Tasks$.$anonfun$exceptionPatternParser$2(Tasks.scala:452)
[error] 	at coursier.CoursierPlugin$.<init>(CoursierPlugin.scala:149)
[error] 	at coursier.CoursierPlugin$.<clinit>(CoursierPlugin.scala)
[error] 	at java.base/java.lang.Class.forName0(Native Method)
[error] 	at java.base/java.lang.Class.forName(Class.java:375)
[error] 	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:20)
[error] 	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:27)
[error] 	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:31)
[error] 	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:415)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1169)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1159)
[error] 	at scala.collection.generic.Growable.loop$1(Growable.scala:54)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:58)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:186)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:44)
[error] 	at scala.collection.TraversableLike.$plus$plus(TraversableLike.scala:147)
[error] 	at scala.collection.TraversableLike.$plus$plus$(TraversableLike.scala:143)
[error] 	at scala.collection.immutable.List.$plus$plus(List.scala:207)
[error] 	at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:47)
[error] 	at sbt.internal.Load$.loadPlugins(Load.scala:1267)
[error] 	at sbt.internal.Load$.loadPluginDefinition(Load.scala:1212)
[error] 	at sbt.internal.Load$.buildPlugins(Load.scala:1191)
[error] 	at sbt.internal.Load$.plugins(Load.scala:1174)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:683)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:683)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:677)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:477)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:154)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:219)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:539)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:555)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:485)
[error] 	at sbt.internal.Load$.load(Load.scala:464)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:249)
[error] 	at sbt.internal.Load$.timed(Load.scala:1343)
[error] 	at sbt.internal.Load$.apply(Load.scala:249)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:65)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:696)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:696)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:688)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:125)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:227)
[error] 	at sbt.State$$anon$1.process(State.scala:233)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:98)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:104)
[error] 	at sbt.xMain.run(Main.scala:71)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
```

**Comment by alexarchambault** [comment]
I guess shading messes things up… Maybe one of the jarjar libs is now fine with java 9, and it should be used here.

**Comment by alexarchambault** [comment]
Closing this, 1.0.0-RC13 should be fine with Java 9. Re-open if you still run into errors with it.
