### ISSUE TITLE
[question] how to build coursier cli for standalone distribution?

### ISSUE THREAD

**Issue by wisechengyi** [coursier/coursier#681]
My understanding from https://github.com/coursier/coursier/blob/master/DEVELOPMENT.md#compile-and-run-the-cli is that it will build a launcher, judging by its size
```bash
$ ls -lh cli/target/pack/bin/coursier
-rwxr-xr-x  1 yic  wheel   4.0K Oct 29 16:39 cli/target/pack/bin/coursier
```
so is there a way to build the standalone distribution, in a jar for example? Reason being when we want to integrate it into our airgapped infrastructure, we need to have the fully built binary instead of just a launcher.

**Comment by alexarchambault** [comment]
The launcher in the sources of coursier is generated via the [generate-launcher.sh script](https://github.com/coursier/coursier/blob/dbd229198b6a4826a05d1bc06d6331be7ea0221f/scripts/generate-launcher.sh), roughly via a command like
```
$ coursier bootstrap \
  --intransitive io.get-coursier::coursier-cli:$VERSION \
  --classifier standalone \
  -J "-noverify" \
  --no-default \
  -r central \
  -r sonatype:releases \
  -f -o coursier
```

The `-s` option allows to generate a launcher that includes the JARs it would have downloaded else. Adding it to the command above generates a standalone launcher (that doesn't need to download JARs).

**Comment by wisechengyi** [comment]
Thanks @alexarchambault . If I understand correctly, this is to generate a one/fat jar of a published version. Is there a way to the jar directly from source on master?

**Comment by alexarchambault** [comment]
Something like
```
$ sbt ++2.11.11 cli/publishLocal
```
then the command above with `VERSION=1.0.0-SNAPSHOT`, should do. This uses the local Ivy cache, as the bootstrap command from coursier only gets things from repositories, not checked out sources.

**Comment by wisechengyi** [comment]
Hmm this process feels a bit awkward. We can certainly improve on that. A single sbt command to build the jar would be ideal.

**Comment by wisechengyi** [comment]
On top of that, it would be nice to publish an a fat jar for every master commit. We do this for https://github.com/pantsbuild/intellij-pants-plugin on https://plugins.jetbrains.com/plugin/7412-pants-support -> bleeding edge channel

**Comment by alexarchambault** [comment]
Ok, I forgot, there's this command:
```
$ sbt ++2.11.11 cli/proguard:proguard
```
which generates a standalone JAR, that can be launched as is like
```
$ java -jar cli/target/scala-2.11/proguard/coursier-standalone-with-bootstrap-and-prelude.jar resolve com.chuusai::shapeless:2.3.2
…
```
(full path of the JAR above is printed by `show cli/proguard:proguard`).

IIRC there were issues with it when using the launch command, but resolve and fetch should be fine.

**Comment by wisechengyi** [comment]
Hi @alexarchambault, 

1. How can I build a non-proguarded jar? as I am running into issues building https://github.com/coursier/coursier/pull/692
```
$ java -jar cli/target/scala-2.11/proguard/coursier-standalone-with-bootstrap.jar  fetch --json-output-file  x.out org.apache.commons:commons-compress:1.4.1
Exception in thread "main" java.lang.ExceptionInInitializerError
	at c.a.a.c.x.<clinit>(Unknown Source)
	at coursier.f.k.a(Unknown Source)
	at coursier.f.H.a(Unknown Source)
	at coursier.cli.oz.b(Unknown Source)
	at coursier.cli.ot.h(Unknown Source)
	at coursier.cli.ow.a(Unknown Source)
	at c.a.a.c.h.a.d.h(Unknown Source)
	at f.h.a.c(Unknown Source)
	at b.b.c_(Unknown Source)
	at f.b.d.E.g(Unknown Source)
	at c.a.a.c.h.a.d.a(Unknown Source)
	at f.b.e.aW.g(Unknown Source)
	at c.a.a.c.h.a.d.a(Unknown Source)
	at coursier.cli.ot.b(Unknown Source)
	at coursier.cli.Q.b(Unknown Source)
	at b.I.c_(Unknown Source)
	at f.F.h(Unknown Source)
	at f.b.f.b.aa.a(Unknown Source)
	at coursier.cli.Coursier.main(Unknown Source)
Caused by: java.lang.NullPointerException
	at c.a.a.c.e.P.<init>(Unknown Source)
	at c.a.a.c.e.P.<clinit>(Unknown Source)
	... 19 more
```
and I am suspecting proguard over-optimized some jackson stuff (which probably uses reflections and what not). 

2. Where can I find the proguard config? I see ./cli/target/scala-2.11/proguard/configuration.pro but it is generated at build time.
```
-injars "/Users/yic/workspace/coursier_dev/cli/target/scala-2.11/classes"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/workspace/coursier_dev/core/jvm/target/scala-2.11/classes"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/workspace/coursier_dev/cache/target/scala-2.11/classes"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/workspace/coursier_dev/extra/target/scala-2.11/classes"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scalaz/scalaz-effect_2.11/7.2.16/scalaz-effect_2.11-7.2.16.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/get-coursier/scala-native/util_2.11/0.3.0-coursier-1/util_2.11-0.3.0-coursier-1.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/fastparse-utils_2.11/1.0.0/fastparse-utils_2.11-1.0.0.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.11/0.1.4/sourcecode_2.11-0.1.4.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/github/alexarchambault/case-app_2.11/1.1.3/case-app_2.11-1.1.3.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/github/alexarchambault/case-app-annotations_2.11/1.1.3/case-app-annotations_2.11-1.1.3.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.6/scala-xml_2.11-1.0.6.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/fastparse_2.11/1.0.0/fastparse_2.11-1.0.0.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/github/alexarchambault/case-app-util_2.11/1.1.3/case-app-util_2.11-1.1.3.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.8.4/jackson-annotations-2.8.4.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/typelevel/macro-compat_2.11/1.1.1/macro-compat_2.11-1.1.1.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.11/scala-library-2.11.11.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.11/2.8.4/jackson-module-scala_2.11-2.8.4.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/argonaut/argonaut_2.11/6.2/argonaut_2.11-6.2.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-paranamer/2.8.4/jackson-module-paranamer-2.8.4.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/get-coursier/scala-native/tools_2.11/0.3.0-coursier-1/tools_2.11-0.3.0-coursier-1.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/jsoup/jsoup/1.10.3/jsoup-1.10.3.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scalaz/scalaz-core_2.11/7.2.16/scalaz-core_2.11-7.2.16.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.8.4/jackson-databind-2.8.4.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/scalaparse_2.11/0.4.2/scalaparse_2.11-0.4.2.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/chuusai/shapeless_2.11/2.3.2/shapeless_2.11-2.3.2.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/get-coursier/scala-native/nir_2.11/0.3.0-coursier-1/nir_2.11-0.3.0-coursier-1.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.8.4/jackson-core-2.8.4.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/github/alexarchambault/argonaut-shapeless_6.2_2.11/1.2.0-M6/argonaut-shapeless_6.2_2.11-1.2.0-M6.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.11/scala-reflect-2.11.11.jar"(!META-INF/MANIFEST.MF)
-injars "/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scalaz/scalaz-concurrent_2.11/7.2.16/scalaz-concurrent_2.11-7.2.16.jar"(!META-INF/MANIFEST.MF)
-libraryjars "/opt/twitter_mde/package/TwitterJDK/0a51fda964681a98da6ba4033ca7608c8b96ddf820501439b6a99af144f15f26/Contents/Home/jre/lib/rt.jar"
-outjars "/Users/yic/workspace/coursier_dev/cli/target/scala-2.11/proguard/coursier-standalone.jar"
-dontwarn
-keep class coursier.cli.Coursier {
  public static void main(java.lang.String[]);
}
-keep class coursier.cli.IsolatedClassLoader {
  public java.lang.String[] getIsolationTargets();
}
-adaptresourcefilenames **.properties
```

**Comment by wisechengyi** [comment]
figured out 2) by adding a few things to keep from progurad. https://github.com/coursier/coursier/pull/692/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceR450

1) still remains. I'd imagine it should be easy, but I am not good with sbt at the moment.

**Comment by wisechengyi** [comment]
closing this one since I can use pants to build a fat binary now.
