### ISSUE TITLE
coursier interacts poorly with sbt-pgp

### ISSUE THREAD

**Issue by mosesn** [coursier/coursier#694]
I'm not sure what's happening here, but +publishLocalSigned fails on my host when coursier is turned on.  At the same time, +publishLocal works with coursier.  However, +publishLocalSigned succeeds when coursier is removed.

I'm using sbt 1.0.x, coursier 1.0.0-RC12, and sbt-pgp 1.1.0.

Here's the error I'm getting.

```
[error] java.lang.IllegalStateException: Ivy file not found in cache for com.twitter#util_2.12;17.11.0!
[error] 	at sbt.internal.librarymanagement.ResolutionCache.getResolvedModuleDescriptor(ResolutionCache.scala:66)
[error] 	at org.apache.ivy.core.deliver.DeliverEngine.deliver(DeliverEngine.java:111)
[error] 	at org.apache.ivy.Ivy.deliver(Ivy.java:601)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$deliver$2(IvyActions.scala:97)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error] 	at sbt.internal.librarymanagement.IvyActions$.deliver(IvyActions.scala:92)
[error] 	at sbt.Classpaths$.$anonfun$deliverTask$1(Defaults.scala:2205)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (util/*:deliverLocal) java.lang.IllegalStateException: Ivy file not found in cache for com.twitter#util_2.12;17.11.0!
[error] Total time: 31 s, completed Nov 15, 2017 1:37:06 PM
```

And here's the build file: https://github.com/twitter/util/blob/develop/build.sbt#L109-L124

**Comment by alexarchambault** [comment]
sbt-coursier `1.0.0-RC13` should be fine (thanks to https://github.com/coursier/coursier/commit/d27c0ee46eeb9573403262d5ee9556aa99cf8d6c).

**Comment by mosesn** [comment]
Thanks, we'll try it out.
