### ISSUE TITLE
possible memory inefficiency

### ISSUE THREAD

**Issue by wisechengyi** [coursier/coursier#699]
This is the stacktrace given 4G Xmx. 
```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at scala.collection.immutable.HashSet$HashTrieSet.updated0(HashSet.scala:549)
	at scala.collection.immutable.HashSet$HashTrieSet.updated0(HashSet.scala:543)
	at scala.collection.immutable.HashSet.$plus(HashSet.scala:84)
	at scala.collection.immutable.HashSet.$plus(HashSet.scala:35)
	at scala.collection.SetLike$$anonfun$$plus$plus$1.apply(SetLike.scala:141)
	at scala.collection.SetLike$$anonfun$$plus$plus$1.apply(SetLike.scala:141)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:316)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:151)
	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
	at scala.collection.SetLike$class.$plus$plus(SetLike.scala:141)
	at scala.collection.AbstractSet.$plus$plus(Set.scala:47)
	at coursier.core.Exclusions$.meet(Exclusions.scala:77)
	at coursier.core.Orders$$anonfun$4$$anonfun$5.apply(Orders.scala:152)
	at coursier.core.Orders$$anonfun$4$$anonfun$5.apply(Orders.scala:152)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at coursier.core.Orders$$anonfun$4.apply(Orders.scala:152)
	at coursier.core.Orders$$anonfun$4.apply(Orders.scala:152)
	at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
	at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)

==== stdout ====
Could not allocate an instance of scala/collection/immutable/HashSet$HashTrieSet (size = 24 bytes) due to: GC overhead limit exceeded
```
wonder if there is any memory inefficiency going on around https://github.com/coursier/coursier/blob/01ad96413e00da505cac9f126bfe7b3d7a8f97e6/core/shared/src/main/scala/coursier/core/Exclusions.scala#L58-L85 @alexarchambault 

This happened at the fetching stage with ~350 roots, and total number of lines to print the tree is ~5500.

**Comment by wisechengyi** [comment]
Sorry false alarm again. It was introduced in the wip PR, fixed in 
 https://github.com/coursier/coursier/pull/692/commits/f4b1a8036b3e405dec9d4bff4eaa749eedbf1120
