### ISSUE TITLE
coursier doesn't work under FreeBSD anymore

### ISSUE THREAD

**Issue by j-keck** [coursier/coursier#707]
The actual version (1.0.0-RC13) doesn't work under FreeBSD:
```⟩ ./coursier 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at coursier.CoursierPaths.cacheDirectory(CoursierPaths.java:61)
	at coursier.CachePath.defaultCacheDirectory(CachePath.java:88)
	at coursier.Bootstrap.main(Bootstrap.java:376)
Caused by: io.github.soc.directories.UnsupportedOperatingSystemException: Base directories are not supported on FreeBSD
	at io.github.soc.directories.ProjectDirectories.<clinit>(ProjectDirectories.java:113)
	... 3 more
```
pr is pending upstream: soc/directories/pull/5

**Comment by soc** [comment]
I merged the PRs kindly offered by @j-keck to stop it from crashing for now, but I think it makes sense to think about what the accepted standard on BSD is ... I kind of feel that they are kind of stuck with the old ways of `.app`, is that right?
