### ISSUE TITLE
downloading fails

### ISSUE THREAD

**Issue by wisechengyi** [coursier/coursier#734]
```
Exception in thread "main" java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at coursier.TermDisplay$UpdateDisplayRunnable.newEntry(TermDisplay.scala:165)
	at coursier.TermDisplay.downloadingArtifact(TermDisplay.scala:444)
	at coursier.Cache$$anonfun$remote$1$1$$anonfun$apply$26.apply(Cache.scala:669)
	at coursier.Cache$$anonfun$remote$1$1$$anonfun$apply$26.apply(Cache.scala:669)
	at scala.Option.foreach(Option.scala:257)
	at coursier.Cache$$anonfun$remote$1$1.apply(Cache.scala:669)
	at coursier.Cache$$anonfun$remote$1$1.apply(Cache.scala:556)
	at scalaz.concurrent.Task$.Try(Task.scala:456)
	at scalaz.concurrent.Task$$anonfun$apply$25.apply(Task.scala:353)
	at scalaz.concurrent.Task$$anonfun$apply$25.apply(Task.scala:353)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
https://github.com/coursier/coursier/blob/dd3e8be410fc908790a036ac136d1946ef1f8ad1/cache/src/main/scala/coursier/TermDisplay.scala#L160-L180

What does this imply? Is it that two coursier processes are trying to download the same file at the same time?

It is hard to reproduce this locally.

**Comment by wisechengyi** [comment]
investigating..can repro locally with a single coursier run.

**Comment by wisechengyi** [comment]
It appears to be only related to display, so passing `-q` works around the issue. will investigate a bit more along with #735

**Comment by alexarchambault** [comment]
`TermDisplay` uses urls as a key (to manage progress bars). That assertion checks that we don't download the same url twice at the same time. There should be ways to manage beforehand not to download the same url twice.

**Comment by alexarchambault** [comment]
Unless you ran into that with the current master? It's a bug then…

**Comment by wisechengyi** [comment]
I found and corrected the issue in my change, although still a bit confused about the behaviors.

https://github.com/coursier/coursier/blob/master/core/shared/src/main/scala/coursier/core/Resolution.scala#L1061

Instead of passing `overrideClassifiers` which is `Option.empty` on master, I passed `Option(Seq())`

This can be repro'ed as followed with *clean cache* in order to trigger the download
```
fetch -t --cache x  -n 20 -A jar,bundle,test-jar,maven-plugin,src,doc --json-output-file y.json org.apache.hadoop:hadoop-minicluster:2.6.0 org.apache.hadoop:hadoop-hdfs:2.6.0
```

**Comment by alexarchambault** [comment]
Closing this.
