### ISSUE TITLE
IPv6-only networks

### ISSUE THREAD

**Issue by raboof** [coursier/coursier#765]
Downloading dependencies from maven central failed on the IPv6-only FOSDEM network:
```
[error] (update) coursier.ResolutionException: 5 download error
[error]     Caught java.net.SocketException: Network is unreachable (connect failed) (Ne
twork is unreachable (connect failed)) while downloading https://repo1.maven.org/maven2/
org/scala-lang/scala-compiler/2.12.3/scala-compiler-2.12.3.jar
[error]     Caught java.net.SocketException: Network is unreachable (connect failed) (Network is unreachable (connect failed)) while downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.3/scala-library-2.12.3.jar
[error]     Caught java.net.SocketException: Network is unreachable (connect failed) (Network is unreachable (connect failed)) while downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.3/scala-reflect-2.12.3.jar
[error]     Caught java.net.SocketException: Network is unreachable (connect failed) (Network is unreachable (connect failed)) while downloading https://repo1.maven.org/maven2/org/scala-sbt/launcher/1.0.0/launcher-1.0.0.jar
[error]     Caught java.net.SocketException: Network is unreachable (connect failed) (Network is unreachable (connect failed)) while downloading https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.0.0/sbt-launch-1.0.0.jar
[error] Total time: 2 s, completed Feb 3, 2018 5:16:17 PM
```

It worked after switching to the FOSDEM-dualstack network, which does support IPv4. Could this point to a problem in coursier?

**Comment by alexarchambault** [comment]
No idea… Are you able to curl or wget the URLs in the error message?

**Comment by raboof** [comment]
Yes, it worked with curl and with firefox (over ipv6). Not on fosdem anymore, but I guess I'll try to set up a test environment at some point :)

**Comment by raboof** [comment]
Looks like they used NAT64/DNS64, and that can be tested through https://go6lab.si/current-ipv6-tests/nat64dns64-public-test/ . To be continued ;)

**Comment by raboof** [comment]
Got a stacktrace:
```
java.net.SocketException: Network is unreachable (connect failed)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1040)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1038)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1037)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at coursier.Cache$.responseCode$1(Cache.scala:536)
	at coursier.Cache$.$anonfun$download$28(Cache.scala:589)
	at coursier.Cache$.liftedTree1$1(Cache.scala:169)
	at coursier.Cache$.helper$2(Cache.scala:169)
	at coursier.Cache$.downloading(Cache.scala:203)
	at coursier.Cache$.doDownload$1(Cache.scala:563)
	at coursier.Cache$.$anonfun$download$48(Cache.scala:675)
	at coursier.Cache$.loop$1(Cache.scala:109)
	at coursier.Cache$.withLockOr(Cache.scala:132)
	at coursier.Cache$.$anonfun$download$27(Cache.scala:676)
	at scalaz.concurrent.Task$.Try(Task.scala:456)
	at scalaz.concurrent.Task$.$anonfun$apply$1(Task.scala:353)
	at scalaz.concurrent.Future$$anon$3.call(Future.scala:432)
	at scalaz.concurrent.Future$$anon$3.call(Future.scala:432)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Looking closer it's a problem in the JRE, where at least on my version (openjdk 1.8.0_151) `sun.net.NetworkClient.doConnect` does a `new InetSocketAddress(server, port)`. In this case there is both an IPv4 and an IPv6 socket available for this hostname, and this `InetSocketAddress` just 'randomly' picks the IPv4 one, without considering that my interface only supports IPv6 sockets at that point.

So I guess it's actually surprising that it works quite well for other applications :).

**Comment by raboof** [comment]
(something as simple as `new URL("https://nu.nl").openConnection().getDate()` should reproduce it. I failed to set up a nice reproduction environment and just ended up disabling my IPv4 address on my laptop and setting 2001:67c:27e4:15::6411 as my DNS)

**Comment by raboof** [comment]
For reference, this is basically upstream bug https://bugs.openjdk.java.net/browse/JDK-8170568

**Comment by wisechengyi** [comment]
Thanks for closing the loop on this!
