### ISSUE TITLE
NoSuchMethodError with Coursier 1.0.2 and SBT 0.13.16 in sbt.librarymanagement.package$.CrossVersion

### ISSUE THREAD

**Issue by JoshRosen** [coursier/coursier#778]
When trying to use Coursier 1.0.2 with SBT 0.13.16, I encountered the following NoSuchMethodError:

```
java.lang.NoSuchMethodError: sbt.librarymanagement.package$.CrossVersion()Lsbt/CrossVersion$;
	at coursier.FromSbt$.sbtCrossVersionName(FromSbt.scala:30)
	at coursier.FromSbt$.sbtModuleIdName(FromSbt.scala:22)
	at coursier.FromSbt$.moduleVersion(FromSbt.scala:46)
	at coursier.FromSbt$.dependencies(FromSbt.scala:62)
	at coursier.FromSbt$$anonfun$8.apply(FromSbt.scala:141)
	at coursier.FromSbt$$anonfun$8.apply(FromSbt.scala:141)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at coursier.FromSbt$.project(FromSbt.scala:141)
	at coursier.Tasks$$anonfun$coursierProjectTask$1$$anonfun$apply$13.apply(Tasks.scala:204)
	at coursier.Tasks$$anonfun$coursierProjectTask$1$$anonfun$apply$13.apply(Tasks.scala:198)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This problem does not occur with Coursier 1.0.

**Comment by JoshRosen** [comment]
Coursier 1.0.1 has a similar issue:

```scala
java.lang.NoSuchMethodError: sbt.librarymanagement.package$.ArtifactOps(Lsbt/Artifact;)Lsbt/Artifact;
	at coursier.ToSbt$$anonfun$4.apply(ToSbt.scala:54)
	at coursier.ToSbt$$anonfun$4.apply(ToSbt.scala:52)
	at coursier.ToSbt$$anonfun$caching$1$$anonfun$apply$1.apply(ToSbt.scala:21)
	at scala.Option.getOrElse(Option.scala:120)
	at coursier.ToSbt$$anonfun$caching$1.apply(ToSbt.scala:20)
	at coursier.ToSbt$$anonfun$5$$anonfun$1.applyOrElse(ToSbt.scala:73)
	at coursier.ToSbt$$anonfun$5$$anonfun$1.applyOrElse(ToSbt.scala:71)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
	at scala.collection.TraversableLike$$anonfun$collect$1.apply(TraversableLike.scala:278)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.collect(TraversableLike.scala:278)
	at scala.collection.AbstractTraversable.collect(Traversable.scala:105)
	at coursier.ToSbt$$anonfun$5.apply(ToSbt.scala:71)
	at coursier.ToSbt$$anonfun$5.apply(ToSbt.scala:68)
	at coursier.ToSbt$$anonfun$caching$1$$anonfun$apply$1.apply(ToSbt.scala:21)
	at scala.Option.getOrElse(Option.scala:120)
	at coursier.ToSbt$$anonfun$caching$1.apply(ToSbt.scala:20)
	at coursier.ToSbt$$anonfun$moduleReports$1.apply(ToSbt.scala:203)
	at coursier.ToSbt$$anonfun$moduleReports$1.apply(ToSbt.scala:189)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:224)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at coursier.ToSbt$.moduleReports(ToSbt.scala:189)
	at coursier.ToSbt$$anonfun$19.apply(ToSbt.scala:228)
	at coursier.ToSbt$$anonfun$19.apply(ToSbt.scala:223)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:224)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at coursier.ToSbt$.updateReport(ToSbt.scala:223)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$coursier$Tasks$$anonfun$$reportTask$1$1.report$1(Tasks.scala:1299)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$coursier$Tasks$$anonfun$$reportTask$1$1.apply(Tasks.scala:1321)
	at coursier.Tasks$$anonfun$updateTask$1$$anonfun$coursier$Tasks$$anonfun$$reportTask$1$1.apply(Tasks.scala:1237)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by leonardehrenfried** [comment]
Thanks for reporting this.

It is probably because of the changes I've made to sbt-shared. I will add
more backwards compatibility code.

You can work around this by using sbt 1 or downgrading to coursier 1.0.0.

Am 14.02.2018 4:18 vorm. schrieb "Josh Rosen" <notifications@github.com>:

**Comment by leonardehrenfried** [comment]
Hmm, I'm a bit puzzled since the compatibility code is there: https://github.com/dwijnand/sbt-compat/blob/master/src/main/scala-sbt-0.13/compat.scala#L30

Has sbt-compat been correctly resolved?

**Comment by alexarchambault** [comment]
Bumping the sources of Ammonite or spark (2.2.1) to sbt 0.13.16, and adding sbt-coursier 1.0.2, works fine for both for me.

@JoshRosen I guess you only added sbt-coursier to `project/plugins.sbt`. In that case, the plugins themselves are fetched by the default resolution mechanism of sbt. It might pull an old version of `sbt-compat` because of another plugin. If that's the case, adding sbt-coursier to `project/project/plugins.sbt` too should solve that.

**Comment by alexarchambault** [comment]
@therealpxc Do you have global plugins (set up under `~/.sbt/0.13/…`)? If yes, would it work with these disabled?

**Comment by leonardehrenfried** [comment]
I also downgraded a project of mine to 0.13.16 and could not reproduce this.

**Comment by gcnew** [comment]
I also hit this issue. The problem was caused by `sbt-ensime` (version `2.1.0`) which I had added globally.

**Comment by therealpxc** [comment]
@alexarchambault @gcnew `sbt-ensime` (`v2.1.0`) is the only SBT plugin I have globally enabled.

I don't much want to disable, it, though, since ENSIME + Emacs is how I've learned to do Scala :-(

**Comment by alexarchambault** [comment]
If I add the following to `~/.sbt/0.13/plugins/plugins.sbt`, it seems to be ok
```scala
addSbtPlugin("com.dwijnand" % "sbt-compat" % "1.2.6")
addSbtPlugin("org.ensime" % "sbt-ensime" % "2.1.0")
```
(and the order seems to matter :| )

**Comment by alexarchambault** [comment]
As the conflict originates from the default sbt resolution… I don't. Maybe sbt-dependency-graph could help, if it can be added at the right level to analyze global plugins.

**Comment by fommil** [comment]
is this because ensime has a different version of `sbt-compat`?

**Comment by fommil** [comment]
I'm releasing 2.5.2 with an upgrade.

**Comment by fommil** [comment]
ok, that didn't fix it... so probably not an ensime bug.

**Comment by NightMachinary** [comment]
I had this issue, too. Adding `addSbtPlugin("com.dwijnand" % "sbt-compat" % "1.2.6")` fixed it. Just using the latest ensime didn't work, though.

**Comment by gravityrahul** [comment]
Works like a charm
