### ISSUE TITLE
Error on fetching dependencies

### ISSUE THREAD

**Issue by NightMachinary** [coursier/coursier#865]
```
sbt:DeathSpell> ensimeConfig
[info] ENSIME update.
[error] java.lang.RuntimeException: failed to resolve ((org.scala-lang:scalap,2.12.6),List(download error: Caught java.io.IOException: Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom (Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom) while downloading https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom))
[error] 	at org.ensime.CoursierHelper$.$anonfun$resolve$4(CoursierHelper.scala:85)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:944)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at org.ensime.CoursierHelper$.resolve(CoursierHelper.scala:84)
[error] 	at org.ensime.CoursierHelper$.resolveEnsimeJarsImpl(CoursierHelper.scala:42)
[error] 	at org.ensime.CoursierHelper$.resolveEnsimeJars(CoursierHelper.scala:22)
[error] 	at org.ensime.EnsimeCoursierPlugin$.$anonfun$buildSettings$4(EnsimeCoursierPlugin.scala:50)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: failed to resolve ((org.scala-lang:scalap,2.12.6),List(download error: Caught java.io.IOException: Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom (Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom) while downloading https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom))
[error] 	at org.ensime.CoursierHelper$.$anonfun$resolve$4(CoursierHelper.scala:85)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:944)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at org.ensime.CoursierHelper$.resolve(CoursierHelper.scala:84)
[error] 	at org.ensime.CoursierHelper$.resolveScalaJarsImpl(CoursierHelper.scala:28)
[error] 	at org.ensime.CoursierHelper$.resolveScalaJars(CoursierHelper.scala:20)
[error] 	at org.ensime.EnsimeCoursierPlugin$.$anonfun$buildSettings$2(EnsimeCoursierPlugin.scala:48)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (ThisBuild / ensimeServerJars) failed to resolve ((org.scala-lang:scalap,2.12.6),List(download error: Caught java.io.IOException: Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom (Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom) while downloading https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom))
[error] (ThisBuild / ensimeScalaJars) failed to resolve ((org.scala-lang:scalap,2.12.6),List(download error: Caught java.io.IOException: Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom (Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom) while downloading https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom))
[error] Total time: 5 s, completed Jun 1, 2018 4:31:06 PM
sbt:DeathSpell> ensimeConfig
[info] ENSIME update.
[error] java.lang.RuntimeException: failed to resolve ((org.scala-lang:scalap,2.12.6),List(download error: Caught java.io.IOException: Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom (Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom) while downloading https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom))
[error] 	at org.ensime.CoursierHelper$.$anonfun$resolve$4(CoursierHelper.scala:85)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:944)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at org.ensime.CoursierHelper$.resolve(CoursierHelper.scala:84)
[error] 	at org.ensime.CoursierHelper$.resolveEnsimeJarsImpl(CoursierHelper.scala:42)
[error] 	at org.ensime.CoursierHelper$.resolveEnsimeJars(CoursierHelper.scala:22)
[error] 	at org.ensime.EnsimeCoursierPlugin$.$anonfun$buildSettings$4(EnsimeCoursierPlugin.scala:50)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: failed to resolve ((org.scala-lang:scalap,2.12.6),List(download error: Caught java.io.IOException: Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom (Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom) while downloading https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom))
[error] 	at org.ensime.CoursierHelper$.$anonfun$resolve$4(CoursierHelper.scala:85)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:944)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at org.ensime.CoursierHelper$.resolve(CoursierHelper.scala:84)
[error] 	at org.ensime.CoursierHelper$.resolveScalaJarsImpl(CoursierHelper.scala:28)
[error] 	at org.ensime.CoursierHelper$.resolveScalaJars(CoursierHelper.scala:20)
[error] 	at org.ensime.EnsimeCoursierPlugin$.$anonfun$buildSettings$2(EnsimeCoursierPlugin.scala:48)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (ThisBuild / ensimeServerJars) failed to resolve ((org.scala-lang:scalap,2.12.6),List(download error: Caught java.io.IOException: Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom (Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom) while downloading https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom))
[error] (ThisBuild / ensimeScalaJars) failed to resolve ((org.scala-lang:scalap,2.12.6),List(download error: Caught java.io.IOException: Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom (Server returned HTTP response code: 416 for URL: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom) while downloading https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.6/scalap-2.12.6.pom))
[error] Total time: 3 s, completed Jun 1, 2018 4:31:48 PM
```
I repeated `ensimeConfig` several times, the result was the same. This is the second and third runs' output, in fact. This is just a new project created with `sbt new shadaj/create-react-scala-app.g8`. I remember I had problems using Coursier before as well, and I gave it up then, because I didn't know I could just open an issue. :) So, I don't think it is related to the specific project.

**Comment by NightMachinary** [comment]
Perhaps this is related to https://github.com/coursier/coursier/pull/795 . I use `addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.3")`.

**Comment by NightMachinary** [comment]
Removing `~/.coursier` and rerunning with `1.1.0-M4` solved the issue. I will report if it should surface again. Anyways, I suggest hotfixing #795 in the current stable version.

**Comment by alexarchambault** [comment]
Seems this is fixed, closing this.
