### ISSUE TITLE
Version specified in pom.xml is not checked to make sure it is the same specified in build.sbt

### ISSUE THREAD

**Issue by mkalish** [coursier/coursier#871]
**Expected:** Coursier validates that the version specified in the pom.xml is the version that was specified in the library dependencies

**Actual:** The value is not checked and dependency is added without a problem.

**Steps to recreate:**

build.sbt

```
name := "BugExample"

version := "0.1"

scalaVersion := "2.12.6"

libraryDependencies ++= Seq("org.jgroups" % "jgroups" % "3.6.15.Final")
```

This will fail when coursier is not used because [pom.xml](https://repo1.maven.org/maven2/org/jgroups/jgroups/3.6.15.Final/jgroups-3.6.15.Final.pom) has `<version>3.6.16-SNAPSHOT</version>`. See error below

```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from /Users/mkalish/.sbt/1.0/plugins
[info] Loading project definition from /Users/mkalish/Developer/CoursierBugExample/project
[info] Loading settings from build.sbt ...
[info] Set current project to CoursierBugExample (in build file:/Users/mkalish/Developer/CoursierBugExample/)
[info] sbt server started at local:///Users/mkalish/.sbt/1.0/server/99e7d0e2b0bb88039721/sock
sbt:CoursierBugExample>
[info] Defining Global / sbtStructureOptions, Global / sbtStructureOutputFile, shellPrompt
[info] The new values will be used by no settings or tasks.
[info] Reapplying settings...
[info] Set current project to CoursierBugExample (in build file:/Users/mkalish/Developer/CoursierBugExample/)
[info] Applying State transformations org.jetbrains.sbt.CreateTasks from /Users/mkalish/Library/Application Support/IdeaIC2017.3/Scala/launcher/sbt-structure-1.0.jar
[info] Reapplying settings...
[info] Set current project to CoursierBugExample (in build file:/Users/mkalish/Developer/CoursierBugExample/)
[info] Updating ...
[error] 	public: bad revision found in https://repo1.maven.org/maven2/org/jgroups/jgroups/3.6.15.Final/jgroups-3.6.15.Final.pom: expected='3.6.15.Final found='3.6.16-SNAPSHOT'
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.jgroups#jgroups;3.6.15.Final: java.text.ParseException: inconsistent module descriptor file found in 'https://repo1.maven.org/maven2/org/jgroups/jgroups/3.6.15.Final/jgroups-3.6.15.Final.pom': bad revision: expected='3.6.15.Final' found='3.6.16-SNAPSHOT';
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.jgroups:jgroups:3.6.15.Final (/Users/mkalish/Developer/CoursierBugExample/build.sbt#L7-8)
[warn] 		  +- default:coursierbugexample_2.12:0.1
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.jgroups#jgroups;3.6.15.Final: java.text.ParseException: inconsistent module descriptor file found in 'https://repo1.maven.org/maven2/org/jgroups/jgroups/3.6.15.Final/jgroups-3.6.15.Final.pom': bad revision: expected='3.6.15.Final' found='3.6.16-SNAPSHOT';
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2398)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.jgroups#jgroups;3.6.15.Final: java.text.ParseException: inconsistent module descriptor file found in 'https://repo1.maven.org/maven2/org/jgroups/jgroups/3.6.15.Final/jgroups-3.6.15.Final.pom': bad revision: expected='3.6.15.Final' found='3.6.16-SNAPSHOT';
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error] 	at sbt.int
ernal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2398)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: org.jgroups#jgroups;3.6.15.Final: java.text.ParseException: inconsistent module descriptor file found in 'https://repo1.maven.org/maven2/org/jgroups/jgroups/3.6.15.Final/jgroups-3.6.15.Final.pom': bad revision: expected='3.6.15.Final' found='3.6.16-SNAPSHOT';
[error] (ssExtractDependencies) sbt.librarymanagement.ResolveException: unresolved dependency: org.jgroups#jgroups;3.6.15.Final: java.text.ParseException: inconsistent module descriptor file found in 'https://repo1.maven.org/maven2/org/jgroups/jgroups/3.6.15.Final/jgroups-3.6.15.Final.pom': bad revision: expected='3.6.15.Final' found='3.6.16-SNAPSHOT';
[error] Total time: 1 s, completed Jun 14, 2018 8:15:21 AM
[info] shutting down server
```
 
If
```
addSbtPlugin("io.get-coursier"  % "sbt-coursier" % "1.0.0")
```
is added to project/plugins.sbt there is no error.

**Comment by alexarchambault** [comment]
@mkalish Why would you want that to fail? It seems Maven itself is ok with
```
<dependency>
  <groupId>org.jgroups</groupId>
  <artifactId>jgroups</artifactId>
  <version>3.6.15.Final</version>
</dependency>
```

**Comment by alexarchambault** [comment]
cc @eed3si9n, this is a case where ivy and coursier behave differently

**Comment by alexarchambault** [comment]
Closing this as "won't fix" for now, as coursier seems to have the same behavior as Maven, which seems fine. (Unless anyone comes up with compelling reasons to have coursier fail in that case too.)

**Comment by eed3si9n** [comment]
> this is a case where ivy and coursier behave differently

if the POM is invalid, I think it's fine for the implementation to make up its own reasonable behavior.
