### ISSUE TITLE
Add support for proxy authentication

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#930]
AFAIK, proxy authentication isn't automatically handled via [Java properties](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html). Some extra setup is needed, see e.g. [this question](https://stackoverflow.com/questions/1626549/authenticated-http-proxy-with-java) or https://github.com/almond-sh/almond/pull/182.

The CLI of coursier should allow one to set up proxy authentication, and helpers should be available for that for the API users.

**Comment by ekrich** [comment]
I just added this to the sbt issue so I am copying here as requested by @eed3si9n 

I have some additional information on this issue related to Basic auth and the redirect need to download plugins - normal dependencies download ok.

```
[error]   download error: Caught java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy
Authentication Required" (Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required") while 
downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-
M2/ivys/ivy.xml
... (full error below)
```

I am able to access via `curl` with `-L` required for redirect:

```
$ curl -I -L -v  --proxy-user user:pass  https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
```

I found this SOF: https://stackoverflow.com/questions/41505219/unable-to-tunnel-through-proxy-proxy-returns-http-1-1-407-via-https
Which points to this Oracle notice for jdk 8 and above about Basic auth excluded: https://www.oracle.com/java/technologies/javase/8u111-relnotes.html

I tried adding the following to `JAVA_OPTS` with no luck. I have the same output as the original issue plus these.

```
-Djdk.http.auth.tunneling.disabledSchemes=
-Djdk.http.auth.proxying.disabledSchemes=
```

Somehow I got this to work using `sbt` `1.4.0-M2` but not `1.3.13`. Now I can not repeat. I can get a normal Scala app to work but not a Scala Native that requires a plugin and thus a redirect via a proxy with Basic auth.

```
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          org.scala-native:sbt-scala-native:0.4.0-M2 (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scala-native:sbt-scala-native;sbtVersion=1.0;scalaVersion=2.12:0.4.0-M2
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala-native/sbt-scala-native_2.12_1.0/0.4.0-M2/sbt-scala-native-0.4.0-M2.pom
[error]   not found: /home/eric/.ivy2/local/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required" (Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required") while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required" (Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required") while downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:218)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[error]         at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3118)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:210)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:52)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-native:sbt-scala-native;sbtVersion=1.0;scalaVersion=2.12:0.4.0-M2
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala-native/sbt-scala-native_2.12_1.0/0.4.0-M2/sbt-scala-native-0.4.0-M2.pom
[error]   not found: /home/eric/.ivy2/local/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required" (Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required") while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required" (Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required") while downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
```

**Comment by ekrich** [comment]
Some additional testing. I think I have gotten the correct command although I may be missing something on the credential side of the house. There seems to be no way to specify the proxy port.

I am also wondering if coursier should just use the standard proxy settings in `JAVA_OPTS` rather than the `COURSIER_CREDENTIALS` direction. Sometimes the need for calculating values makes using a script to generate `JAVA_OPTS` the most convenient. This seems better that the `http_proxy`, `https_proxy`, `no_proxy` and friends on the "UNIX" side of the house. Either way using something that is standard seems best.

```
$ cs fetch --credentials "proxy-host user:pass" --repository bintray-ivy:repo.scala-sbt.org/scalasbt --sbt-plugin org.scala-native:sbt-scala-native:0.4.0-M2
```
```
Resolution error: Error downloading org.scala-native:sbt-scala-native;sbtVersion=1.0;scalaVersion=2.12:0.4.0-M2
  not found: /home/eric/.ivy2/local/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scala-native/sbt-scala-native_2.12_1.0/0.4.0-M2/sbt-scala-native-0.4.0-M2.pom
  download error: Caught java.net.ConnectException: Connection refused (Connection refused) (Connection refused (Connection refused)) while downloading 
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
  download error: Caught java.net.ConnectException: Connection refused (Connection refused) (Connection refused (Connection refused)) while downloading 
https://dl.bintray.com/repo.scala-sbt.org/scalasbt/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
```

**Comment by ekrich** [comment]
When passing credentials on the command line there is no way to add a port number to the host that I can see.
```
Malformed credentials
```
I decided to run without the credentials and I got the same as above. I have `JAVA_OPTS` set. I am guessing that coursier is doing fine with the request to `repo.scala-sbt.org` but then it gets the redirect to `dl.bintray.com` and then it doesn't pass the credentials. That is when things fail.

**Comment by alexarchambault** [comment]
@ekrich Do you know a way to reproduce that locally? Like spinning up an authenticated proxy via docker, then having the ability to curl things via it? That would help debugging / testing that.

**Comment by alexarchambault** [comment]
Nevermind, seems this does it:
```text
$ docker run -d -p 8080:80 bahamat/authenticated-proxy
$ https_proxy="http://localhost:8080" curl -fLv --proxy-user jack:insecure https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
```

**Comment by ekrich** [comment]
Wow, you are way faster than I would have been.

**Comment by alexarchambault** [comment]
I had started googl-ing things a bit before my first comment :)

>  I like the `jack:insecure`. I have been talking to our IT.

These are the default credentials of the docker image `bahamat/authenticated-proxy`.

**Comment by NickP82** [comment]
@alexarchambault : I am stuck at the same step. I can curl without problems but cannot fetch the binaries. 
I have installed that docker container and reset my environment variables but now I don't have a clue what to do next. 

When I follow the instructions from bahamat setting the url to "www.google.com" then I just retrieve a website in my brower "It works!"  

I would expect that this would work now:
`cs fetch --repository bintray-ivy:repo.scala-sbt.org/scalasbt --sbt-plugin org.scala-native:sbt-scala-native:0.4.0-M2`

**Comment by ekrich** [comment]
You can try in a browser too.
If you go to `https://repo.scala-sbt.org/scalasbt`
it should redirect to `https://dl.bintray.com/sbt/`

**Comment by NickP82** [comment]
I can confirm that this works. 
But how do I get the sources with coursier?

**Comment by NickP82** [comment]
I got my issue getting metals to work done in a different way. 

works in my git bash:
coursier -J-Dhttps.proxyHost=corporate.proxy.com -J-Dhttps.proxyPort=8080 fetch org.scalameta:semanticdb-scalac_212.10:4.3.20

does NOT work in windows powershell
coursier -Dhttps.proxyHost=corporate.proxy.com -Dhttps.proxyPort=8080 fetch org.scalameta:semanticdb-scalac_212.10:4.3.20

Strange. Do I have a syntax error with powershell?

**Comment by tomasjura** [comment]
a solution can be add into initialization stage something like 
```scala
import java.net.Authenticator
import java.net.PasswordAuthentication

class EnvironmentAuthenticator extends Authenticator {
  override def getPasswordAuthentication() : PasswordAuthentication = {
    return new PasswordAuthentication (System.getenv("PROXY_USER"), System.getenv("PROXY_PASSWORD"));
  }
}

if ( System.getenv("PROXY_USER") != null && System.getenv("PROXY_PASSWORD") != null ) {
   Authenticator.setDefault( new EnvironmentAuthenticator )
}
```

IMHO writing password in any config file is a security risk. Writing password in command line parameters is inherently insecure. System environment variables as a password storage seems to be the safest option.
