### ISSUE TITLE
Stale file handle when running parallel build stages

### ISSUE THREAD

**Issue by dpennell** [coursier/coursier#955]
I have an sbt build that fails when running in a Jenkins on AWS pipeline with:

> 21:32:59 [Build UI] [error] coursier.ResolutionException: Exception during resolution
> 21:32:59 [Build UI] [error] Caused by: java.io.IOException: Stale file handle
> 21:32:59 [Build UI] [error] at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
> 21:32:59 [Build UI] [error] at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:90)
> 21:32:59 [Build UI] [error] at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1073)
> 21:32:59 [Build UI] [error] at java.nio.channels.FileChannel.lock(FileChannel.java:1053)

The pipeline runs two stages in parallel that execute sbt tasks on disjoint projects (but not disjoint dependencies).

I see lots of the following:

> 21:30:13 [Build Core] Downloading https://repo1.maven.org/maven2/io/confluent/kafka-avro-serializer/4.1.0/kafka-avro-serializer-4.1.0.pom.sha1
> 21:30:13 [Build Core] Downloading https://repo1.maven.org/maven2/io/confluent/kafka-avro-serializer/4.1.0/kafka-avro-serializer-4.1.0.pom
21:30:13 [Build Core] Downloading http://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/4.1.0/
21:30:13 [Build Core] Downloading https://repo1.maven.org/maven2/io/confluent/kafka-schema-registry-parent/4.1.0/kafka-schema-registry-parent-4.1.0.pom
21:30:13 [Build Core] Downloading https://repo1.maven.org/maven2/io/confluent/kafka-schema-registry-parent/4.1.0/kafka-schema-registry-parent-4.1.0.pom.sha1
21:30:13 [Build Core] Downloading http://packages.confluent.io/maven/io/confluent/kafka-schema-registry-parent/4.1.0/
21:30:13 [Build Core] Downloading https://repo1.maven.org/maven2/io/confluent/rest-utils-parent/4.1.0/rest-utils-parent-4.1.0.pom
21:30:13 [Build Core] Downloading https://repo1.maven.org/maven2/io/confluent/rest-utils-parent/4.1.0/rest-utils-parent-4.1.0.pom.sha1

which I interpret as snapshot-like resolution, presumably related to the ` Maven metadata files listing available versions, etc.` comment from https://coursier.github.io/coursier/1.1.0-SNAPSHOT/docs/ttl.

Note that I only see this behavior for apache-kafka and confluent-kafka artifacts.  I tried adding

> coursierTtl in ThisBuild := Some(Duration("Inf"))
but it does not stick across an sbt invocation (or reload).

This sbt project has 60+ sub-projects.  I switched to coursier because IntelliJ/sbt synchs were taking 20-30 minutes.  With coursier, they are under 2 minutes.

**Comment by alexarchambault** [comment]
@dpennell Does it consistently fail this way? Or is it transient?

The downloading messages above aren't related to snapshots, their versions are stable / release ones. So TTL doesn't matter for those. (Once they're in cache, they're used from there, and no attempt is made to download them again.)

**Comment by dpennell** [comment]
@alexarchambault I've seen it succeed once in almost a dozen tries.  I know they aren't snapshots, but if I restart sbt or reload, and then run update, I see those `downloading` messages all sub-projects that have these dependencies.  If you then run update again, it's quiet.  It seems like snapshot behavior.  The doc I referenced indicated that there were other conditions than "SNAPSHOT" that could trigger this behavior.

**Comment by dpennell** [comment]
also - I changed the build to not add the coursier plugin if running on Jenkins and the issue disappeared.  We get the benefit of coursier for dev and the build is OK, but this is just a workaround.
