### ISSUE TITLE
javax.ws.rs-api does not resolve

### ISSUE THREAD

**Issue by adam-singer** [coursier/coursier#987]
There is a long history of this issue, but wanted to bring it up with coursier. The following exception is thrown while trying to resolve javax.ws.rs-api

```
$ brew tap coursier/formulas
$ brew install --HEAD coursier/formulas/coursier
$ coursier fetch "javax.ws.rs" % "javax.ws.rs-api" % "2.1.1"

Exception in thread "main" java.util.concurrent.ExecutionException: Boxed Error
    0.0%at scala.concurrent.impl.Promise$.resolver(Unknown Source)
https://at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Unknown Source)
    0.0%at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Unknown Source)
    at scala.concurrent.Promise.complete(Unknown Source)
    at scala.concurrent.Promise.complete$(Unknown Source)
    at scala.concurrent.impl.Promise$DefaultPromise.complete(Unknown Source)
    at scala.concurrent.impl.Promise.$anonfun$transform$1(Unknown Source)
    at scala.concurrent.impl.CallbackRunnable.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: assertion failed: Attempts to download https://index.scala-lang.org/api/search?q=%&target=JVM&scalaVersion=2.12.7 twice in parallel (second check)
    at scala.Predef$.assert(Unknown Source)
    at coursier.P.a(Unknown Source)
    at coursier.I.b(Unknown Source)
    at coursier.c.a(Unknown Source)
    at coursier.c.c(Unknown Source)
    at scala.Option.foreach(Unknown Source)
    at coursier.c.a(Unknown Source)
    at scala.concurrent.Future$.$anonfun$apply$1(Unknown Source)
    at scala.util.Success.$anonfun$map$1(Unknown Source)
    at scala.util.Success.map(Unknown Source)
    at scala.concurrent.Future.$anonfun$map$1(Unknown Source)
    at scala.concurrent

```

This issue affects users of sbt who use the coursier sbt plugin, so I've commented on an open issue https://github.com/sbt/sbt/issues/4005 and attempted hacks mentioned in https://github.com/sbt/sbt/issues/3618. 

What we are able todo is the following, its specific to kafka streams since our project brings in the deps from `connect-api` via `kafka-streams`. Exclusion rule `ExclusionRule("javax.ws.rs", "javax.ws.rs-api")` needs to be added along any dependency path that `kafka-streams` is introduced.
Add the following library dependency `"jakarta.ws.rs" % "jakarta.ws.rs-api" % "2.1.3"` to ensure any possible connect-api interfaces are supported.  

Some other relative information:
https://github.com/gradle/gradle/issues/3065 
https://repo1.maven.org/maven2/javax/ws/rs/javax.ws.rs-api/2.1.1/javax.ws.rs-api-2.1.1.pom  `TODO: maven-bundle-plugin doesn't understand module-info yet.`
https://groups.google.com/forum/#!topic/play-framework/3CGZDJIffC4

**Comment by adam-singer** [comment]
Just found that https://github.com/coursier/coursier/issues/956 was filed, hopefully the instructions here are consistent with reproduction. If not able to reproduce locally, try to blow out all caches, thats what usually tripped us up thinking resolution actually worked.

**Comment by alexarchambault** [comment]
@adam-singer The coursier command you're using can't work, the syntax for dependencies of the CLI is different than the one from sbt. The following works fine for me
```bash
$ coursier fetch javax.ws.rs:javax.ws.rs-api:2.1.1
~/.coursier/cache/v1/https/repo1.maven.org/maven2/javax/ws/rs/javax.ws.rs-api/2.1.1/javax.ws.rs-api-2.1.1.jar
```

The following sbt project also works fine
```bash
$ cat project/build.properties
sbt.version=1.2.7
$ cat project/plugins.sbt
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M8")
$ cat build.sbt
libraryDependencies += "javax.ws.rs" % "javax.ws.rs-api" % "2.1.1"
$ sbt update updateClassifiers
```

Same kind of tests with `org.apache.kafka:kafka-streams:2.1.0` also work fine me…

**Comment by adam-singer** [comment]
Going to close out, tried to reproduce again, I don't seem to have a easy way to reproduce the environment where this failed. What you have mentioned directly does work. Will be happy to show a better example in an open source project once it is ready.
